/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Physical serial port in ASCII mode. Factory for device clients. */
export declare class AsyncAsciiTransport {
  /** Opens the serial port in ASCII mode. */
  static open(opts: AsciiTransportOptions): Promise<AsyncAsciiTransport>
  /** Creates a device client bound to the specified unit ID. */
  createClient(opts: CreateClientOptions): AsyncSerialModbusClient
  /** Sets the per-request timeout in milliseconds. */
  setRequestTimeout(timeoutMs: number): void
  /** Clears the per-request timeout. */
  clearRequestTimeout(): void
  /** Returns whether there are pending requests. */
  get pendingRequests(): boolean
  /** Closes the transport. */
  close(): Promise<void>
  /** Reconnects the transport after a disconnect. */
  reconnect(): Promise<void>
}

/** Physical serial port in RTU mode. Factory for device clients. */
export declare class AsyncRtuTransport {
  /** Opens the serial port in RTU mode. */
  static open(opts: RtuTransportOptions): Promise<AsyncRtuTransport>
  /** Creates a device client bound to the specified unit ID. */
  createClient(opts: CreateClientOptions): AsyncSerialModbusClient
  /** Sets the per-request timeout in milliseconds. */
  setRequestTimeout(timeoutMs: number): void
  /** Clears the per-request timeout. */
  clearRequestTimeout(): void
  /** Returns whether there are pending requests. */
  get pendingRequests(): boolean
  /** Closes the transport. */
  close(): Promise<void>
  /** Reconnects the transport after a disconnect. */
  reconnect(): Promise<void>
}

/** Lightweight device client sharing the serial transport. */
export declare class AsyncSerialModbusClient {
  /** Reads holding registers (FC03). */
  readHoldingRegisters(opts: ReadRegistersOptions): Promise<number[]>
  /** Reads input registers (FC04). */
  readInputRegisters(opts: ReadRegistersOptions): Promise<number[]>
  /** Writes a single register (FC06). */
  writeSingleRegister(opts: WriteSingleRegisterOptions): Promise<void>
  /** Writes multiple registers (FC16). */
  writeMultipleRegisters(opts: WriteMultipleRegistersOptions): Promise<void>
  /** Reads and writes multiple registers atomically (FC23). */
  readWriteMultipleRegisters(opts: ReadWriteMultipleRegistersOptions): Promise<number[]>
  /** Reads coils (FC01). */
  readCoils(opts: ReadBitsOptions): Promise<boolean[]>
  /** Writes a single coil (FC05). */
  writeSingleCoil(opts: WriteSingleCoilOptions): Promise<void>
  /** Writes multiple coils (FC15). */
  writeMultipleCoils(opts: WriteMultipleCoilsOptions): Promise<void>
  /** Reads discrete inputs (FC02). */
  readDiscreteInputs(opts: ReadBitsOptions): Promise<boolean[]>
  /** Reads FIFO queue (FC24). */
  readFifoQueue(opts: ReadFifoQueueOptions): Promise<FifoQueueResponse>
  /** Reads file records (FC20). */
  readFileRecord(opts: ReadFileRecordOptions): Promise<number[][]>
  /** Writes file records (FC21). */
  writeFileRecord(opts: WriteFileRecordOptions): Promise<void>
  /** Reads exception status (FC07). */
  readExceptionStatus(): Promise<number>
  /** Sends a diagnostics request (FC08). */
  diagnostics(opts: DiagnosticsOptions): Promise<DiagnosticsResponse>
  /** Reads device identification (FC43/MEI14). */
  readDeviceIdentification(opts: ReadDeviceIdentificationOptions): Promise<DeviceIdentificationResponse>
}

/** Async Modbus Serial server supporting RTU and ASCII transports. */
export declare class AsyncSerialModbusServer {
  static bindRtu(opts: SerialServerOptions, handlers: ServerHandlers): Promise<AsyncSerialModbusServer>
  static bindAscii(opts: SerialServerOptions, handlers: ServerHandlers): Promise<AsyncSerialModbusServer>
  /** Stops the server. */
  shutdown(): Promise<void>
}

/**
 * Async Modbus TCP gateway.
 *
 * Forwards incoming Modbus requests to downstream servers based on unit ID routing.
 */
export declare class AsyncTcpGateway {
  /**
   * Creates and starts a new TCP gateway.
   *
   * @param opts - Gateway bind options.
   * @param config - Gateway configuration including downstreams and routes.
   * @returns A running gateway instance.
   */
  static bind(opts: GatewayBindOptions, config: GatewayConfig): Promise<AsyncTcpGateway>
  /** Stops the gateway. */
  shutdown(): Promise<void>
}

/** Lightweight device client sharing the TCP transport. */
export declare class AsyncTcpModbusClient {
  /** Reads holding registers (FC03). */
  readHoldingRegisters(opts: ReadRegistersOptions): Promise<number[]>
  /** Reads input registers (FC04). */
  readInputRegisters(opts: ReadRegistersOptions): Promise<number[]>
  /** Writes a single register (FC06). */
  writeSingleRegister(opts: WriteSingleRegisterOptions): Promise<void>
  /** Writes multiple registers (FC16). */
  writeMultipleRegisters(opts: WriteMultipleRegistersOptions): Promise<void>
  /** Reads and writes multiple registers atomically (FC23). */
  readWriteMultipleRegisters(opts: ReadWriteMultipleRegistersOptions): Promise<number[]>
  /** Reads coils (FC01). */
  readCoils(opts: ReadBitsOptions): Promise<boolean[]>
  /** Writes a single coil (FC05). */
  writeSingleCoil(opts: WriteSingleCoilOptions): Promise<void>
  /** Writes multiple coils (FC15). */
  writeMultipleCoils(opts: WriteMultipleCoilsOptions): Promise<void>
  /** Reads discrete inputs (FC02). */
  readDiscreteInputs(opts: ReadBitsOptions): Promise<boolean[]>
  /** Reads FIFO queue (FC24). */
  readFifoQueue(opts: ReadFifoQueueOptions): Promise<FifoQueueResponse>
  /** Reads file records (FC20). */
  readFileRecord(opts: ReadFileRecordOptions): Promise<number[][]>
  /** Writes file records (FC21). */
  writeFileRecord(opts: WriteFileRecordOptions): Promise<void>
  /** Reads exception status (FC07). */
  readExceptionStatus(): Promise<number>
  /** Sends a diagnostics request (FC08). */
  diagnostics(opts: DiagnosticsOptions): Promise<DiagnosticsResponse>
  /** Reads device identification (FC43/MEI14). */
  readDeviceIdentification(opts: ReadDeviceIdentificationOptions): Promise<DeviceIdentificationResponse>
}

/**
 * Async Modbus TCP server.
 *
 * Binds to a TCP port and handles incoming Modbus requests using JS callbacks.
 */
export declare class AsyncTcpModbusServer {
  /**
   * Creates and starts a new TCP server.
   *
   * @param opts - Server bind options.
   * @param handlers - Object containing handler functions for each Modbus operation.
   * @returns A running server instance.
   */
  static bind(opts: TcpServerOptions, handlers: ServerHandlers): Promise<AsyncTcpModbusServer>
  /** Stops the server. */
  shutdown(): Promise<void>
}

/** Physical TCP socket connection to a Modbus device or gateway. */
export declare class AsyncTcpTransport {
  /** Connects to a Modbus TCP device or gateway. */
  static connect(opts: TcpTransportOptions): Promise<AsyncTcpTransport>
  /** Creates a device client bound to the specified unit ID. */
  createClient(opts: CreateClientOptions): AsyncTcpModbusClient
  /** Sets the per-request timeout in milliseconds. */
  setRequestTimeout(timeoutMs: number): void
  /** Clears the per-request timeout. */
  clearRequestTimeout(): void
  /** Returns whether there are pending requests. */
  get pendingRequests(): boolean
  /** Closes the connection. */
  close(): Promise<void>
  /** Reconnects the transport after a disconnect. */
  reconnect(): Promise<void>
}

/** Connection options for the serial ASCII transport. */
export interface AsciiTransportOptions {
  /** Serial port path (e.g., "/dev/ttyUSB0", "COM3"). */
  portPath: string
  /** Baud rate (e.g., 9600, 19200, 38400, 57600, 115200). */
  baudRate: number
  /** Data bits (5, 6, 7, or 8). */
  dataBits?: number
  /** Parity ("none", "even", "odd"). */
  parity?: string
  /** Stop bits (1 or 2). */
  stopBits?: number
  /** Response timeout in milliseconds. */
  responseTimeoutMs?: number
  /** Per-request timeout in milliseconds. */
  requestTimeoutMs?: number
  /** Number of retry attempts on failure (0 = none). Default: 0. */
  retryAttempts?: number
  /** Backoff strategy: "immediate", "fixed", or "exponential". Default: "immediate". */
  retryBackoffStrategy?: string
}

/** Options for creating a device client. */
export interface CreateClientOptions {
  /** Modbus unit ID (1-247). */
  unitId: number
}

/** Device identification object. */
export interface DeviceIdentificationObject {
  /** Object ID. */
  id: number
  /** Object value as string. */
  value: string
}

/** Response from device identification request. */
export interface DeviceIdentificationResponse {
  /** Conformity level. */
  conformityLevel: number
  /** Whether more objects follow. */
  moreFollows: boolean
  /** Next object ID if more follows. */
  nextObjectId: number
  /** Retrieved objects. */
  objects: Array<DeviceIdentificationObject>
}

/** Options for diagnostics request. */
export interface DiagnosticsOptions {
  /** Diagnostic sub-function code. */
  subFunction: number
  /** Data words for the request. */
  data: Array<number>
  /** Optional abort signal to cancel the request. */
  signal?: AbortSignal
}

/** Handler request for diagnostics. */
export interface DiagnosticsRequest {
  unitId: number
  subFunction: number
  data: Array<number>
}

/** Response from diagnostics request. */
export interface DiagnosticsResponse {
  /** Echoed sub-function code. */
  subFunction: number
  /** Response data words. */
  data: Array<number>
}

/** Downstream server configuration. */
export interface DownstreamConfig {
  /** Downstream server host. */
  host: string
  /** Downstream server port. */
  port: number
}

/** Response from reading FIFO queue. */
export interface FifoQueueResponse {
  /** Queue values. */
  values: Array<number>
}

/** A single file record read sub-request. */
export interface FileRecordReadRequest {
  /** File number (1-65535). */
  fileNumber: number
  /** Starting record number. */
  recordNumber: number
  /** Number of records to read. */
  recordLength: number
}

/** A single file record read sub-request on the server side. */
export interface FileRecordReadServerSubRequest {
  fileNumber: number
  recordNumber: number
  recordLength: number
}

/** A single file record write sub-request. */
export interface FileRecordWriteRequest {
  /** File number (1-65535). */
  fileNumber: number
  /** Starting record number. */
  recordNumber: number
  /** Record data to write. */
  recordData: Array<number>
}

/** A single file record write sub-request on the server side. */
export interface FileRecordWriteSubRequest {
  fileNumber: number
  recordNumber: number
  recordData: Array<number>
}

/** Gateway bind options. */
export interface GatewayBindOptions {
  /** Bind host address (e.g., "0.0.0.0"). */
  host: string
  /** Bind port. */
  port: number
}

/** Gateway configuration. */
export interface GatewayConfig {
  /** List of downstream servers. */
  downstreams: Array<DownstreamConfig>
  /** Routing table mapping unit IDs to downstream channels. */
  routes: Array<RouteEntry>
}

/** Stable error code: The connection was closed. */
export const MODBUS_ERROR_CODE_CONNECTION_CLOSED: string

/** Stable error code: Modbus protocol exception received. */
export const MODBUS_ERROR_CODE_EXCEPTION: string

/** Stable error code: Internal library error. */
export const MODBUS_ERROR_CODE_INTERNAL: string

/** Stable error code: Invalid argument passed to the API. */
export const MODBUS_ERROR_CODE_INVALID_ARGUMENT: string

/** Stable error code: Request timed out. */
export const MODBUS_ERROR_CODE_TIMEOUT: string

/** Stable error code: Transport/framing error. */
export const MODBUS_ERROR_CODE_TRANSPORT: string

/** Options for reading coils or discrete inputs. */
export interface ReadBitsOptions {
  /** Starting address. */
  address: number
  /** Number of bits to read. */
  quantity: number
  /** Optional abort signal to cancel the request. */
  signal?: AbortSignal
}

/** Handler request for reading coils. */
export interface ReadCoilsRequest {
  unitId: number
  address: number
  quantity: number
}

/** Options for device identification. */
export interface ReadDeviceIdentificationOptions {
  /** Read device ID code (1=basic, 2=regular, 3=extended, 4=individual). */
  readDeviceIdCode: number
  /** Starting object ID. */
  objectId: number
  /** Optional abort signal to cancel the request. */
  signal?: AbortSignal
}

/** Handler request for reading discrete inputs. */
export interface ReadDiscreteInputsRequest {
  unitId: number
  address: number
  quantity: number
}

/** Handler request for reading exception status. */
export interface ReadExceptionStatusRequest {
  unitId: number
}

/** Options for reading FIFO queue. */
export interface ReadFifoQueueOptions {
  /** FIFO pointer address. */
  address: number
  /** Optional abort signal to cancel the request. */
  signal?: AbortSignal
}

/** Handler request for reading FIFO queue. */
export interface ReadFifoQueueRequest {
  unitId: number
  address: number
}

/** Options for reading file records. */
export interface ReadFileRecordOptions {
  /** Array of sub-requests. */
  requests: Array<FileRecordReadRequest>
  /** Optional abort signal to cancel the request. */
  signal?: AbortSignal
}

/** Handler request for reading file records. */
export interface ReadFileRecordRequest {
  unitId: number
  requests: Array<FileRecordReadServerSubRequest>
}

/** Handler request for reading holding registers. */
export interface ReadHoldingRegistersRequest {
  unitId: number
  address: number
  quantity: number
}

/** Handler request for reading input registers. */
export interface ReadInputRegistersRequest {
  unitId: number
  address: number
  quantity: number
}

/** Options for reading registers. */
export interface ReadRegistersOptions {
  /** Starting register address. */
  address: number
  /** Number of registers to read. */
  quantity: number
  /** Optional abort signal to cancel the request. */
  signal?: AbortSignal
}

/** Options for read/write multiple registers (FC23). */
export interface ReadWriteMultipleRegistersOptions {
  /** Starting address for read operation. */
  readAddress: number
  /** Number of registers to read. */
  readQuantity: number
  /** Starting address for write operation. */
  writeAddress: number
  /** Values to write. */
  writeValues: Array<number>
  /** Optional abort signal to cancel the request. */
  signal?: AbortSignal
}

/** Handler request for read/write multiple registers (FC23). */
export interface ReadWriteMultipleRegistersRequest {
  unitId: number
  readAddress: number
  readQuantity: number
  writeAddress: number
  writeValues: Array<number>
}

/** Route entry mapping unit ID to a downstream channel. */
export interface RouteEntry {
  /** Modbus unit ID (1-247). */
  unitId: number
  /** Index into the downstreams array. */
  channel: number
}

/** Connection options for the serial RTU transport. */
export interface RtuTransportOptions {
  /** Serial port path (e.g., "/dev/ttyUSB0", "COM3"). */
  portPath: string
  /** Baud rate (e.g., 9600, 19200, 38400, 57600, 115200). */
  baudRate: number
  /** Data bits (5, 6, 7, or 8). */
  dataBits?: number
  /** Parity ("none", "even", "odd"). */
  parity?: string
  /** Stop bits (1 or 2). */
  stopBits?: number
  /** Response timeout in milliseconds. */
  responseTimeoutMs?: number
  /** Per-request timeout in milliseconds. */
  requestTimeoutMs?: number
  /** Number of retry attempts on failure (0 = none). Default: 0. */
  retryAttempts?: number
  /** Backoff strategy: "immediate", "fixed", or "exponential". Default: "immediate". */
  retryBackoffStrategy?: string
}

/** Server bind options for serial port. */
export interface SerialServerOptions {
  /** Serial port path (e.g., "/dev/ttyUSB0", "COM3"). */
  portPath: string
  /** Baud rate (e.g., 9600, 19200, 38400, 57600, 115200). */
  baudRate: number
  /** Data bits (5, 6, 7, or 8). */
  dataBits?: number
  /** Parity ("none", "even", "odd"). */
  parity?: string
  /** Stop bits (1 or 2). */
  stopBits?: number
  /** Modbus unit ID (1-247). */
  unitId: number
  /** Response timeout in milliseconds. */
  responseTimeoutMs?: number
}

/** Handler response for diagnostics. */
export interface ServerDiagnosticsResponse {
  subFunction: number
  data: Array<number>
}

/** Response that may include an exception code. */
export interface ServerExceptionResponse {
  /** Modbus exception code if this is an error response. */
  exception?: number
}

/** Server bind options. */
export interface TcpServerOptions {
  /** Bind host address (e.g., "0.0.0.0"). */
  host: string
  /** Bind port. */
  port: number
  /** Modbus unit ID to respond to. */
  unitId: number
}

/** Connection options for the TCP transport. */
export interface TcpTransportOptions {
  /** Target host address (IP or hostname). */
  host: string
  /** Target TCP port (typically 502). */
  port: number
  /** Per-request timeout in milliseconds (optional). */
  requestTimeoutMs?: number
  /** Number of retry attempts on failure (0 = none). Default: 0. */
  retryAttempts?: number
  /** Backoff strategy: "immediate", "fixed", or "exponential". Default: "immediate". */
  retryBackoffStrategy?: string
}

/** Options for writing file records. */
export interface WriteFileRecordOptions {
  /** Array of sub-requests. */
  requests: Array<FileRecordWriteRequest>
  /** Optional abort signal to cancel the request. */
  signal?: AbortSignal
}

/** Handler request for writing file records. */
export interface WriteFileRecordRequest {
  unitId: number
  requests: Array<FileRecordWriteSubRequest>
}

/** Options for writing multiple coils. */
export interface WriteMultipleCoilsOptions {
  /** Starting coil address. */
  address: number
  /** Values to write. */
  values: Array<boolean>
  /** Optional abort signal to cancel the request. */
  signal?: AbortSignal
}

/** Handler request for writing multiple coils. */
export interface WriteMultipleCoilsRequest {
  unitId: number
  address: number
  values: Array<boolean>
}

/** Options for writing multiple registers. */
export interface WriteMultipleRegistersOptions {
  /** Starting register address. */
  address: number
  /** Values to write. */
  values: Array<number>
  /** Optional abort signal to cancel the request. */
  signal?: AbortSignal
}

/** Handler request for writing multiple registers. */
export interface WriteMultipleRegistersRequest {
  unitId: number
  address: number
  values: Array<number>
}

/** Options for writing a single coil. */
export interface WriteSingleCoilOptions {
  /** Coil address. */
  address: number
  /** Value to write. */
  value: boolean
  /** Optional abort signal to cancel the request. */
  signal?: AbortSignal
}

/** Handler request for writing a single coil. */
export interface WriteSingleCoilRequest {
  unitId: number
  address: number
  value: boolean
}

/** Options for writing a single register. */
export interface WriteSingleRegisterOptions {
  /** Register address. */
  address: number
  /** Value to write. */
  value: number
  /** Optional abort signal to cancel the request. */
  signal?: AbortSignal
}

/** Handler request for writing a single register. */
export interface WriteSingleRegisterRequest {
  unitId: number
  address: number
  value: number
}

export interface ModbusException {
  exception: number;
}

export interface ServerHandlers {
  onReadCoils?: (req: ReadCoilsRequest) => boolean[] | ModbusException | Promise<boolean[] | ModbusException>;
  onReadDiscreteInputs?: (req: ReadDiscreteInputsRequest) => boolean[] | ModbusException | Promise<boolean[] | ModbusException>;
  onReadHoldingRegisters?: (req: ReadHoldingRegistersRequest) => number[] | ModbusException | Promise<number[] | ModbusException>;
  onReadInputRegisters?: (req: ReadInputRegistersRequest) => number[] | ModbusException | Promise<number[] | ModbusException>;
  onWriteSingleCoil?: (req: WriteSingleCoilRequest) => void | ModbusException | Promise<void | ModbusException>;
  onWriteSingleRegister?: (req: WriteSingleRegisterRequest) => void | ModbusException | Promise<void | ModbusException>;
  onReadExceptionStatus?: (req: ReadExceptionStatusRequest) => number | ModbusException | Promise<number | ModbusException>;
  onDiagnostics?: (req: DiagnosticsRequest) => ServerDiagnosticsResponse | ModbusException | Promise<ServerDiagnosticsResponse | ModbusException>;
  onWriteMultipleCoils?: (req: WriteMultipleCoilsRequest) => void | ModbusException | Promise<void | ModbusException>;
  onWriteMultipleRegisters?: (req: WriteMultipleRegistersRequest) => void | ModbusException | Promise<void | ModbusException>;
  onReadFileRecord?: (req: ReadFileRecordRequest) => number[][] | ModbusException | Promise<number[][] | ModbusException>;
  onWriteFileRecord?: (req: WriteFileRecordRequest) => void | ModbusException | Promise<void | ModbusException>;
  onReadWriteMultipleRegisters?: (req: ReadWriteMultipleRegistersRequest) => number[] | ModbusException | Promise<number[] | ModbusException>;
  onReadFifoQueue?: (req: ReadFifoQueueRequest) => number[] | ModbusException | Promise<number[] | ModbusException>;
}

export declare const ModbusErrorCode: {
  readonly EXCEPTION: 'MODBUS_EXCEPTION';
  readonly TIMEOUT: 'MODBUS_TIMEOUT';
  readonly TRANSPORT: 'MODBUS_TRANSPORT';
  readonly INVALID_ARGUMENT: 'MODBUS_INVALID_ARGUMENT';
  readonly CONNECTION_CLOSED: 'MODBUS_CONNECTION_CLOSED';
  readonly INTERNAL: 'MODBUS_INTERNAL';
};

export declare function getModbusErrorCode(err: Error): string | undefined;
