/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Connection options for the TCP client. */
export interface TcpClientOptions {
  /** Target host address (IP or hostname). */
  host: string
  /** Target TCP port (typically 502). */
  port: number
  /** Modbus unit ID (1-247). */
  unitId: number
  /** Per-request timeout in milliseconds (optional). */
  timeoutMs?: number
}
/** Options for reading registers. */
export interface ReadRegistersOptions {
  /** Starting register address. */
  address: number
  /** Number of registers to read. */
  quantity: number
}
/** Options for writing a single register. */
export interface WriteSingleRegisterOptions {
  /** Register address. */
  address: number
  /** Value to write. */
  value: number
}
/** Options for writing multiple registers. */
export interface WriteMultipleRegistersOptions {
  /** Starting register address. */
  address: number
  /** Values to write. */
  values: Array<number>
}
/** Options for read/write multiple registers (FC23). */
export interface ReadWriteMultipleRegistersOptions {
  /** Starting address for read operation. */
  readAddress: number
  /** Number of registers to read. */
  readQuantity: number
  /** Starting address for write operation. */
  writeAddress: number
  /** Values to write. */
  writeValues: Array<number>
}
/** Options for reading coils or discrete inputs. */
export interface ReadBitsOptions {
  /** Starting address. */
  address: number
  /** Number of bits to read. */
  quantity: number
}
/** Options for writing a single coil. */
export interface WriteSingleCoilOptions {
  /** Coil address. */
  address: number
  /** Value to write. */
  value: boolean
}
/** Options for writing multiple coils. */
export interface WriteMultipleCoilsOptions {
  /** Starting coil address. */
  address: number
  /** Values to write. */
  values: Array<boolean>
}
/** Options for reading FIFO queue. */
export interface ReadFifoQueueOptions {
  /** FIFO pointer address. */
  address: number
}
/** A single file record read sub-request. */
export interface FileRecordReadRequest {
  /** File number (1-65535). */
  fileNumber: number
  /** Starting record number. */
  recordNumber: number
  /** Number of records to read. */
  recordLength: number
}
/** Options for reading file records. */
export interface ReadFileRecordOptions {
  /** Array of sub-requests. */
  requests: Array<FileRecordReadRequest>
}
/** A single file record write sub-request. */
export interface FileRecordWriteRequest {
  /** File number (1-65535). */
  fileNumber: number
  /** Starting record number. */
  recordNumber: number
  /** Record data to write. */
  recordData: Array<number>
}
/** Options for writing file records. */
export interface WriteFileRecordOptions {
  /** Array of sub-requests. */
  requests: Array<FileRecordWriteRequest>
}
/** Options for device identification. */
export interface ReadDeviceIdentificationOptions {
  /** Read device ID code (1=basic, 2=regular, 3=extended, 4=individual). */
  readDeviceIdCode: number
  /** Starting object ID. */
  objectId: number
}
/** Options for diagnostics request. */
export interface DiagnosticsOptions {
  /** Diagnostic sub-function code. */
  subFunction: number
  /** Data words for the request. */
  data: Array<number>
}
/** Response from diagnostics request. */
export interface DiagnosticsResponse {
  /** Echoed sub-function code. */
  subFunction: number
  /** Response data words. */
  data: Array<number>
}
/** Device identification object. */
export interface DeviceIdentificationObject {
  /** Object ID. */
  id: number
  /** Object value as string. */
  value: string
}
/** Response from device identification request. */
export interface DeviceIdentificationResponse {
  /** Conformity level. */
  conformityLevel: number
  /** Whether more objects follow. */
  moreFollows: boolean
  /** Next object ID if more follows. */
  nextObjectId: number
  /** Retrieved objects. */
  objects: Array<DeviceIdentificationObject>
}
/** Connection options for the serial client. */
export interface SerialClientOptions {
  /** Serial port path (e.g., "/dev/ttyUSB0", "COM3"). */
  portPath: string
  /** Baud rate (e.g., 9600, 19200, 38400, 57600, 115200). */
  baudRate: number
  /** Data bits (5, 6, 7, or 8). */
  dataBits?: number
  /** Parity ("none", "even", "odd"). */
  parity?: string
  /** Stop bits (1 or 2). */
  stopBits?: number
  /** Modbus unit ID (1-247). */
  unitId: number
  /** Response timeout in milliseconds. */
  responseTimeoutMs?: number
  /** Per-request timeout in milliseconds. */
  requestTimeoutMs?: number
}
/** Server bind options. */
export interface TcpServerOptions {
  /** Bind host address (e.g., "0.0.0.0"). */
  host: string
  /** Bind port. */
  port: number
  /** Modbus unit ID to respond to. */
  unitId: number
}
/** Handler request for reading coils. */
export interface ReadCoilsRequest {
  unitId: number
  address: number
  quantity: number
}
/** Handler request for writing a single coil. */
export interface WriteSingleCoilRequest {
  unitId: number
  address: number
  value: boolean
}
/** Handler request for writing multiple coils. */
export interface WriteMultipleCoilsRequest {
  unitId: number
  address: number
  values: Array<boolean>
}
/** Handler request for reading discrete inputs. */
export interface ReadDiscreteInputsRequest {
  unitId: number
  address: number
  quantity: number
}
/** Handler request for reading holding registers. */
export interface ReadHoldingRegistersRequest {
  unitId: number
  address: number
  quantity: number
}
/** Handler request for reading input registers. */
export interface ReadInputRegistersRequest {
  unitId: number
  address: number
  quantity: number
}
/** Handler request for writing a single register. */
export interface WriteSingleRegisterRequest {
  unitId: number
  address: number
  value: number
}
/** Handler request for writing multiple registers. */
export interface WriteMultipleRegistersRequest {
  unitId: number
  address: number
  values: Array<number>
}
/** Handler request for reading FIFO queue. */
export interface ReadFifoQueueRequest {
  unitId: number
  address: number
}
/** Handler request for diagnostics. */
export interface DiagnosticsRequest {
  unitId: number
  subFunction: number
  data: Array<number>
}
/** Response that may include an exception code. */
export interface ServerExceptionResponse {
  /** Modbus exception code if this is an error response. */
  exception?: number
}
/** Gateway bind options. */
export interface GatewayBindOptions {
  /** Bind host address (e.g., "0.0.0.0"). */
  host: string
  /** Bind port. */
  port: number
}
/** Downstream server configuration. */
export interface DownstreamConfig {
  /** Downstream server host. */
  host: string
  /** Downstream server port. */
  port: number
}
/** Route entry mapping unit ID to a downstream channel. */
export interface RouteEntry {
  /** Modbus unit ID (1-247). */
  unitId: number
  /** Index into the downstreams array. */
  channel: number
}
/** Gateway configuration. */
export interface GatewayConfig {
  /** List of downstream servers. */
  downstreams: Array<DownstreamConfig>
  /** Routing table mapping unit IDs to downstream channels. */
  routes: Array<RouteEntry>
}
/**
 * Async Modbus TCP client.
 *
 * All methods are async and return Promises. The client must be connected
 * before issuing Modbus requests.
 */
export declare class AsyncTcpModbusClient {
  /**
   * Creates and connects a new TCP client.
   *
   * @param opts - Connection options including host, port, unitId, and optional timeout.
   * @returns A connected client instance.
   */
  static connect(opts: TcpClientOptions): Promise<AsyncTcpModbusClient>
  /** Sets the per-request timeout in milliseconds. */
  setRequestTimeout(timeoutMs: number): void
  /** Clears the per-request timeout. */
  clearRequestTimeout(): void
  /** Returns whether there are pending requests. */
  get pendingRequests(): boolean
  /** Closes the client connection. */
  close(): Promise<void>
  /** Reconnects the client after a disconnect. */
  reconnect(): Promise<void>
  /** Reads holding registers (FC03). */
  readHoldingRegisters(opts: ReadRegistersOptions): Promise<Array<number>>
  /** Reads input registers (FC04). */
  readInputRegisters(opts: ReadRegistersOptions): Promise<Array<number>>
  /** Writes a single register (FC06). */
  writeSingleRegister(opts: WriteSingleRegisterOptions): Promise<void>
  /** Writes multiple registers (FC16). */
  writeMultipleRegisters(opts: WriteMultipleRegistersOptions): Promise<void>
  /** Reads and writes multiple registers atomically (FC23). */
  readWriteMultipleRegisters(opts: ReadWriteMultipleRegistersOptions): Promise<Array<number>>
  /** Reads coils (FC01). */
  readCoils(opts: ReadBitsOptions): Promise<Array<boolean>>
  /** Writes a single coil (FC05). */
  writeSingleCoil(opts: WriteSingleCoilOptions): Promise<void>
  /** Writes multiple coils (FC15). */
  writeMultipleCoils(opts: WriteMultipleCoilsOptions): Promise<void>
  /** Reads discrete inputs (FC02). */
  readDiscreteInputs(opts: ReadBitsOptions): Promise<Array<boolean>>
  /** Reads FIFO queue (FC24). */
  readFifoQueue(opts: ReadFifoQueueOptions): Promise<Array<number>>
  /** Reads file records (FC20). */
  readFileRecord(opts: ReadFileRecordOptions): Promise<Array<Array<number>>>
  /** Writes file records (FC21). */
  writeFileRecord(opts: WriteFileRecordOptions): Promise<void>
  /** Reads exception status (FC07). */
  readExceptionStatus(): Promise<number>
  /** Sends a diagnostics request (FC08). */
  diagnostics(opts: DiagnosticsOptions): Promise<DiagnosticsResponse>
  /** Reads device identification (FC43/MEI14). */
  readDeviceIdentification(opts: ReadDeviceIdentificationOptions): Promise<DeviceIdentificationResponse>
}
/** Async Modbus Serial client supporting RTU and ASCII transports. */
export declare class AsyncSerialModbusClient {
  /** Creates and connects a new Serial RTU client. */
  static connectRtu(opts: SerialClientOptions): Promise<AsyncSerialModbusClient>
  /** Creates and connects a new Serial ASCII client. */
  static connectAscii(opts: SerialClientOptions): Promise<AsyncSerialModbusClient>
  /** Sets the per-request timeout in milliseconds. */
  setRequestTimeout(timeoutMs: number): void
  /** Clears the per-request timeout. */
  clearRequestTimeout(): void
  /** Returns whether there are pending requests. */
  get pendingRequests(): boolean
  /** Closes the client connection. */
  close(): Promise<void>
  /** Reconnects the client after a disconnect. */
  reconnect(): Promise<void>
  /** Reads holding registers (FC03). */
  readHoldingRegisters(opts: ReadRegistersOptions): Promise<Array<number>>
  /** Reads input registers (FC04). */
  readInputRegisters(opts: ReadRegistersOptions): Promise<Array<number>>
  /** Writes a single register (FC06). */
  writeSingleRegister(opts: WriteSingleRegisterOptions): Promise<void>
  /** Writes multiple registers (FC16). */
  writeMultipleRegisters(opts: WriteMultipleRegistersOptions): Promise<void>
  /** Reads and writes multiple registers atomically (FC23). */
  readWriteMultipleRegisters(opts: ReadWriteMultipleRegistersOptions): Promise<Array<number>>
  /** Reads coils (FC01). */
  readCoils(opts: ReadBitsOptions): Promise<Array<boolean>>
  /** Writes a single coil (FC05). */
  writeSingleCoil(opts: WriteSingleCoilOptions): Promise<void>
  /** Writes multiple coils (FC15). */
  writeMultipleCoils(opts: WriteMultipleCoilsOptions): Promise<void>
  /** Reads discrete inputs (FC02). */
  readDiscreteInputs(opts: ReadBitsOptions): Promise<Array<boolean>>
  /** Reads FIFO queue (FC24). */
  readFifoQueue(opts: ReadFifoQueueOptions): Promise<Array<number>>
  /** Reads file records (FC20). */
  readFileRecord(opts: ReadFileRecordOptions): Promise<Array<Array<number>>>
  /** Writes file records (FC21). */
  writeFileRecord(opts: WriteFileRecordOptions): Promise<void>
  /** Reads exception status (FC07). */
  readExceptionStatus(): Promise<number>
  /** Sends a diagnostics request (FC08). */
  diagnostics(opts: DiagnosticsOptions): Promise<DiagnosticsResponse>
  /** Reads device identification (FC43/MEI14). */
  readDeviceIdentification(opts: ReadDeviceIdentificationOptions): Promise<DeviceIdentificationResponse>
}
/**
 * Async Modbus TCP server.
 *
 * Binds to a TCP port and handles incoming Modbus requests using JS callbacks.
 */
export declare class AsyncTcpModbusServer {
  /**
   * Creates and starts a new TCP server.
   *
   * @param opts - Server bind options.
   * @param handlers - Object containing handler functions for each Modbus operation.
   * @returns A running server instance.
   */
  static bind(opts: TcpServerOptions, handlers: object): AsyncTcpModbusServer
  /** Stops the server. */
  shutdown(): Promise<void>
}
/**
 * Async Modbus TCP gateway.
 *
 * Forwards incoming Modbus requests to downstream servers based on unit ID routing.
 */
export declare class AsyncTcpGateway {
  /**
   * Creates and starts a new TCP gateway.
   *
   * @param opts - Gateway bind options.
   * @param config - Gateway configuration including downstreams and routes.
   * @returns A running gateway instance.
   */
  static bind(opts: GatewayBindOptions, config: GatewayConfig): Promise<AsyncTcpGateway>
  /** Stops the gateway. */
  shutdown(): Promise<void>
}
