/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 *  Physical serial port in ASCII mode. Factory for device clients.
 * Manages a physical serial port connection in ASCII mode.
 * This class is a factory for creating lightweight `AsyncSerialModbusClient` instances
 * that are bound to a specific unit ID and share the underlying serial connection.
 *
 * Use the static `open` method to establish a connection.
 */
export declare class AsyncAsciiTransport {
  /**
   *  Opens the serial port in ASCII mode.
   * Opens a serial port and establishes a connection in ASCII mode.
   * @param opts Options for the serial ASCII transport.
   * @param opts.portPath The path to the serial port (e.g., '/dev/ttyUSB0', 'COM3').
   * @param opts.baudRate The baud rate for the serial communication.
   * @returns A `Promise` that resolves to an `AsyncAsciiTransport` instance.
   */
  static open(opts: AsciiTransportOptions): Promise<AsyncAsciiTransport>
  /**
   *  Creates a device client bound to the specified unit ID.
   * Creates a lightweight device client that communicates through this transport.
   * The client is bound to a specific Modbus unit ID.
   * @param opts Options specifying the unit ID.
   */
  createClient(opts: CreateClientOptions): AsyncSerialModbusClient
  /**
   *  Sets the per-request timeout in milliseconds.
   * Sets the timeout for individual Modbus requests made through this transport.
   * @param timeout_ms The timeout duration in milliseconds.
   */
  setRequestTimeout(timeoutMs: number): void
  /**
   *  Clears the per-request timeout.
   * Clears any previously set per-request timeout.
   */
  clearRequestTimeout(): void
  /**
   *  Returns whether there are pending requests.
   * Checks if there are any Modbus requests currently in-flight on this transport.
   */
  get pendingRequests(): boolean
  /**
   *  Closes the transport.
   * Closes the underlying serial port connection.
   */
  close(): Promise<void>
  /**
   *  Reconnects the transport after a disconnect.
   * Attempts to re-establish the serial connection if it has been closed.
   */
  reconnect(): Promise<void>
}

/**
 *  Physical serial port in RTU mode. Factory for device clients.
 * Manages a physical serial port connection in RTU mode.
 * This class is a factory for creating lightweight `AsyncSerialModbusClient` instances
 * that are bound to a specific unit ID and share the underlying serial connection.
 *
 * Use the static `open` method to establish a connection.
 */
export declare class AsyncRtuTransport {
  /**
   *  Opens the serial port in RTU mode.
   * Opens a serial port and establishes a connection in RTU mode.
   * @param opts Options for the serial RTU transport.
   * @param opts.portPath The path to the serial port (e.g., '/dev/ttyUSB0', 'COM3').
   * @param opts.baudRate The baud rate for the serial communication.
   * @returns A `Promise` that resolves to an `AsyncRtuTransport` instance.
   */
  static open(opts: RtuTransportOptions): Promise<AsyncRtuTransport>
  /**
   *  Creates a device client bound to the specified unit ID.
   * Creates a lightweight device client that communicates through this transport.
   * The client is bound to a specific Modbus unit ID.
   * @param opts Options specifying the unit ID.
   */
  createClient(opts: CreateClientOptions): AsyncSerialModbusClient
  /**
   *  Sets the per-request timeout in milliseconds.
   * Sets the timeout for individual Modbus requests made through this transport.
   * @param timeout_ms The timeout duration in milliseconds.
   */
  setRequestTimeout(timeoutMs: number): void
  /**
   *  Clears the per-request timeout.
   * Clears any previously set per-request timeout.
   */
  clearRequestTimeout(): void
  /**
   *  Returns whether there are pending requests.
   * Checks if there are any Modbus requests currently in-flight on this transport.
   */
  get pendingRequests(): boolean
  /**
   *  Closes the transport.
   * Closes the underlying serial port connection.
   */
  close(): Promise<void>
  /**
   *  Reconnects the transport after a disconnect.
   * Attempts to re-establish the serial connection if it has been closed.
   */
  reconnect(): Promise<void>
}

/**
 *  Lightweight device client sharing the serial transport.
 * A lightweight Modbus client that sends requests for a specific unit ID
 * over a shared `AsyncRtuTransport` or `AsyncAsciiTransport`.
 */
export declare class AsyncSerialModbusClient {
  /**
   *  Reads holding registers (FC03).
   * Reads one or more holding registers (Function Code 03).
   * @param opts Options for reading registers.
   * @param opts.address The starting register address.
   * @param opts.quantity The number of registers to read.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  readHoldingRegisters(opts: ReadRegistersOptions): Promise<number[]>
  /**
   *  Reads input registers (FC04).
   * Reads one or more input registers (Function Code 04).
   * @param opts Options for reading registers.
   * @param opts.address The starting register address.
   * @param opts.quantity The number of registers to read.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  readInputRegisters(opts: ReadRegistersOptions): Promise<number[]>
  /**
   *  Writes a single register (FC06).
   * Writes a single holding register (Function Code 06).
   * @param opts Options for writing a single register.
   * @param opts.address The register address.
   * @param opts.value The 16-bit value to write.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  writeSingleRegister(opts: WriteSingleRegisterOptions): Promise<void>
  /**
   *  Writes multiple registers (FC16).
   * Writes multiple consecutive holding registers (Function Code 16).
   * @param opts Options for writing multiple registers.
   * @param opts.address The starting register address.
   * @param opts.values An array of 16-bit values to write.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  writeMultipleRegisters(opts: WriteMultipleRegistersOptions): Promise<void>
  /**
   *  Reads and writes multiple registers atomically (FC23).
   * Performs an atomic read/write operation on multiple registers (Function Code 23).
   * @param opts Options for the read/write operation.
   * @param opts.read_address The starting address for the read operation.
   * @param opts.read_quantity The number of registers to read.
   * @param opts.write_address The starting address for the write operation.
   * @param opts.write_values An array of 16-bit values to write.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  readWriteMultipleRegisters(opts: ReadWriteMultipleRegistersOptions): Promise<number[]>
  /**
   *  Reads coils (FC01).
   * Reads the status of one or more coils (Function Code 01).
   * @param opts Options for reading bits.
   * @param opts.address The starting coil address.
   * @param opts.quantity The number of coils to read.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  readCoils(opts: ReadBitsOptions): Promise<boolean[]>
  /**
   *  Writes a single coil (FC05).
   * Writes a single coil (Function Code 05).
   * @param opts Options for writing a single coil.
   * @param opts.address The coil address.
   * @param opts.value The boolean value to write (true for ON, false for OFF).
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  writeSingleCoil(opts: WriteSingleCoilOptions): Promise<void>
  /**
   *  Writes multiple coils (FC15).
   * Writes multiple consecutive coils (Function Code 15).
   * @param opts Options for writing multiple coils.
   * @param opts.address The starting coil address.
   * @param opts.values An array of boolean values to write.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  writeMultipleCoils(opts: WriteMultipleCoilsOptions): Promise<void>
  /**
   *  Reads discrete inputs (FC02).
   * Reads the status of one or more discrete inputs (Function Code 02).
   * @param opts Options for reading bits.
   * @param opts.address The starting discrete input address.
   * @param opts.quantity The number of discrete inputs to read.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  readDiscreteInputs(opts: ReadBitsOptions): Promise<boolean[]>
  /**
   *  Reads FIFO queue (FC24).
   * Reads from a FIFO queue register (Function Code 24).
   * @param opts Options for reading the FIFO queue.
   * @param opts.address The FIFO pointer address.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  readFifoQueue(opts: ReadFifoQueueOptions): Promise<FifoQueueResponse>
  /**
   *  Reads file records (FC20).
   * Reads one or more file records (Function Code 20).
   * @param opts Options for reading file records.
   * @param opts.requests An array of file record read sub-requests.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  readFileRecord(opts: ReadFileRecordOptions): Promise<number[][]>
  /**
   *  Writes file records (FC21).
   * Writes one or more file records (Function Code 21).
   * @param opts Options for writing file records.
   * @param opts.requests An array of file record write sub-requests.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  writeFileRecord(opts: WriteFileRecordOptions): Promise<void>
  /**
   *  Reads exception status (FC07).
   * Reads the device's exception status byte (Function Code 07).
   */
  readExceptionStatus(): Promise<number>
  /**
   *  Sends a diagnostics request (FC08).
   * Executes a diagnostic function on the device (Function Code 08).
   * @param opts Options for the diagnostics request.
   * @param opts.sub_function The diagnostic sub-function code.
   * @param opts.data Data to be sent with the request.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  diagnostics(opts: DiagnosticsOptions): Promise<DiagnosticsResponse>
  /**
   *  Reads device identification (FC43/MEI14).
   * Reads device identification information (Function Code 43, MEI 14).
   * @param opts Options for reading device identification.
   * @param opts.read_device_id_code The category of objects to read (e.g., basic, regular).
   * @param opts.object_id The ID of the first object to read.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  readDeviceIdentification(opts: ReadDeviceIdentificationOptions): Promise<DeviceIdentificationResponse>
}

/**
 *  Async Modbus Serial server supporting RTU and ASCII transports.
 * An asynchronous Modbus server that listens on a serial port for incoming requests.
 * It supports both RTU and ASCII transport modes.
 * Use the static `bindRtu` or `bindAscii` methods to create and start a server instance.
 */
export declare class AsyncSerialModbusServer {
  /**
   * Creates and starts a new Modbus RTU server on a serial port.
   *
   * @param opts Server configuration options.
   * @param opts.portPath The path to the serial port (e.g., '/dev/ttyUSB0', 'COM3').
   * @param opts.baudRate The communication speed (e.g., 9600, 19200).
   * @param opts.unitId The Modbus unit ID the server will respond to.
   * @param opts.dataBits Optional number of data bits (5, 6, 7, or 8). Defaults to 8.
   * @param opts.parity Optional parity setting ('none', 'even', 'odd'). Defaults to 'none'.
   * @param opts.stopBits Optional number of stop bits (1 or 2). Defaults to 1.
   * @param opts.responseTimeoutMs Optional response timeout in milliseconds. Defaults to 1000.
   *
   * @param handlers An object containing callback functions to handle Modbus requests (matches the `ServerHandlers` interface in TypeScript).
   * @returns A `Promise` that resolves to a running `AsyncSerialModbusServer` instance.
   */
  static bindRtu(opts: SerialServerOptions, handlers: ServerHandlers): Promise<AsyncSerialModbusServer>
  /**
   * Creates and starts a new Modbus ASCII server on a serial port.
   *
   * @param opts Server configuration options.
   * @param opts.portPath The path to the serial port (e.g., '/dev/ttyUSB0', 'COM3').
   * @param opts.baudRate The communication speed (e.g., 9600, 19200).
   * @param opts.unitId The Modbus unit ID the server will respond to.
   * @param opts.dataBits Optional number of data bits (7 or 8). Defaults to 8.
   * @param opts.parity Optional parity setting ('none', 'even', 'odd'). Defaults to 'none'.
   * @param opts.stopBits Optional number of stop bits (1 or 2). Defaults to 1.
   * @param opts.responseTimeoutMs Optional response timeout in milliseconds. Defaults to 1000.
   *
   * @param handlers An object containing callback functions to handle Modbus requests (matches the `ServerHandlers` interface in TypeScript).
   * @returns A `Promise` that resolves to a running `AsyncSerialModbusServer` instance.
   */
  static bindAscii(opts: SerialServerOptions, handlers: ServerHandlers): Promise<AsyncSerialModbusServer>
  /**
   *  Stops the server.
   * Stops the server and closes the serial port.
   */
  shutdown(): Promise<void>
}

/**
 * Async Modbus TCP gateway.
 *
 * Forwards incoming Modbus requests to downstream servers based on unit ID routing.
 */
export declare class AsyncTcpGateway {
  /**
   * Creates and starts a new TCP gateway.
   *
   * @param opts - Gateway bind options.
   * @param config - Gateway configuration including downstreams and routes.
   * @returns A running gateway instance.
   */
  static bind(opts: GatewayBindOptions, config: GatewayConfig): Promise<AsyncTcpGateway>
  /** Stops the gateway. */
  shutdown(): Promise<void>
}

/**
 *  Lightweight device client sharing the TCP transport.
 * A lightweight Modbus client that sends requests for a specific unit ID
 * over a shared `AsyncTcpTransport`.
 */
export declare class AsyncTcpModbusClient {
  /**
   *  Reads holding registers (FC03).
   * Reads one or more holding registers (Function Code 03).
   * @param opts Options for reading registers.
   * @param opts.address The starting register address.
   * @param opts.quantity The number of registers to read.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  readHoldingRegisters(opts: ReadRegistersOptions): Promise<number[]>
  /**
   *  Reads input registers (FC04).
   * Reads one or more input registers (Function Code 04).
   * @param opts Options for reading registers.
   * @param opts.address The starting register address.
   * @param opts.quantity The number of registers to read.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  readInputRegisters(opts: ReadRegistersOptions): Promise<number[]>
  /**
   *  Writes a single register (FC06).
   * Writes a single holding register (Function Code 06).
   * @param opts Options for writing a single register.
   * @param opts.address The register address.
   * @param opts.value The 16-bit value to write.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  writeSingleRegister(opts: WriteSingleRegisterOptions): Promise<void>
  /**
   *  Writes multiple registers (FC16).
   * Writes multiple consecutive holding registers (Function Code 16).
   * @param opts Options for writing multiple registers.
   * @param opts.address The starting register address.
   * @param opts.values An array of 16-bit values to write.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  writeMultipleRegisters(opts: WriteMultipleRegistersOptions): Promise<void>
  /**
   *  Reads and writes multiple registers atomically (FC23).
   * Performs an atomic read/write operation on multiple registers (Function Code 23).
   * @param opts Options for the read/write operation.
   * @param opts.read_address The starting address for the read operation.
   * @param opts.read_quantity The number of registers to read.
   * @param opts.write_address The starting address for the write operation.
   * @param opts.write_values An array of 16-bit values to write.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  readWriteMultipleRegisters(opts: ReadWriteMultipleRegistersOptions): Promise<number[]>
  /**
   *  Reads coils (FC01).
   * Reads the status of one or more coils (Function Code 01).
   * @param opts Options for reading bits.
   * @param opts.address The starting coil address.
   * @param opts.quantity The number of coils to read.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  readCoils(opts: ReadBitsOptions): Promise<boolean[]>
  /**
   *  Writes a single coil (FC05).
   * Writes a single coil (Function Code 05).
   * @param opts Options for writing a single coil.
   * @param opts.address The coil address.
   * @param opts.value The boolean value to write (true for ON, false for OFF).
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  writeSingleCoil(opts: WriteSingleCoilOptions): Promise<void>
  /**
   *  Writes multiple coils (FC15).
   * Writes multiple consecutive coils (Function Code 15).
   * @param opts Options for writing multiple coils.
   * @param opts.address The starting coil address.
   * @param opts.values An array of boolean values to write.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  writeMultipleCoils(opts: WriteMultipleCoilsOptions): Promise<void>
  /**
   *  Reads discrete inputs (FC02).
   * Reads the status of one or more discrete inputs (Function Code 02).
   * @param opts Options for reading bits.
   * @param opts.address The starting discrete input address.
   * @param opts.quantity The number of discrete inputs to read.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  readDiscreteInputs(opts: ReadBitsOptions): Promise<boolean[]>
  /**
   *  Reads FIFO queue (FC24).
   * Reads from a FIFO queue register (Function Code 24).
   * @param opts Options for reading the FIFO queue.
   * @param opts.address The FIFO pointer address.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  readFifoQueue(opts: ReadFifoQueueOptions): Promise<FifoQueueResponse>
  /**
   *  Reads file records (FC20).
   * Reads one or more file records (Function Code 20).
   * @param opts Options for reading file records.
   * @param opts.requests An array of file record read sub-requests.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  readFileRecord(opts: ReadFileRecordOptions): Promise<number[][]>
  /**
   *  Writes file records (FC21).
   * Writes one or more file records (Function Code 21).
   * @param opts Options for writing file records.
   * @param opts.requests An array of file record write sub-requests.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  writeFileRecord(opts: WriteFileRecordOptions): Promise<void>
  /**
   *  Reads exception status (FC07).
   * Reads the device's exception status byte (Function Code 07).
   */
  readExceptionStatus(): Promise<number>
  /**
   *  Sends a diagnostics request (FC08).
   * Executes a diagnostic function on the device (Function Code 08).
   * @param opts Options for the diagnostics request.
   * @param opts.sub_function The diagnostic sub-function code.
   * @param opts.data Data to be sent with the request.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  diagnostics(opts: DiagnosticsOptions): Promise<DiagnosticsResponse>
  /**
   *  Reads device identification (FC43/MEI14).
   * Reads device identification information (Function Code 43, MEI 14).
   * @param opts Options for reading device identification.
   * @param opts.read_device_id_code The category of objects to read (e.g., basic, regular).
   * @param opts.object_id The ID of the first object to read.
   * @param opts.signal An optional `AbortSignal` to cancel the operation.
   */
  readDeviceIdentification(opts: ReadDeviceIdentificationOptions): Promise<DeviceIdentificationResponse>
}

/**
 *  Async Modbus TCP server.
 *
 *  Binds to a TCP port and handles incoming Modbus requests using JS callbacks.
 * An asynchronous Modbus TCP server that listens for incoming client connections.
 */
export declare class AsyncTcpModbusServer {
  /**
   *  Creates and starts a new TCP server.
   * Creates and starts a new Modbus TCP server.
   *
   * @param opts Server bind options.
   * @param opts.host The host address to bind to (e.g., '0.0.0.0').
   * @param opts.port The TCP port to listen on.
   * @param opts.unitId The Modbus unit ID the server will respond to.
   * @param handlers An object containing callback functions to handle Modbus requests (matches the `ServerHandlers` interface in TypeScript).
   * @returns A `Promise` that resolves to a running `AsyncTcpModbusServer` instance.
   */
  static bind(opts: TcpServerOptions, handlers: ServerHandlers): Promise<AsyncTcpModbusServer>
  /**
   *  Stops the server.
   * Stops the server and closes all active connections.
   */
  shutdown(): Promise<void>
}

/**
 *  Physical TCP socket connection to a Modbus device or gateway.
 * Manages a physical TCP socket connection to a Modbus device or gateway.
 * This class is a factory for creating lightweight `AsyncTcpModbusClient` instances
 * that are bound to a specific unit ID and share the underlying TCP connection.
 *
 * Use the static `connect` method to establish a connection.
 */
export declare class AsyncTcpTransport {
  /**
   *  Connects to a Modbus TCP device or gateway.
   * Establishes a connection to a Modbus TCP device or gateway.
   *
   * @param opts - Connection options including host, port, and timeout settings.
   * @param opts.host - Target host address (IP or hostname).
   * @param opts.port - Target TCP port (typically 502).
   */
  static connect(opts: TcpTransportOptions): Promise<AsyncTcpTransport>
  /**
   *  Creates a device client bound to the specified unit ID.
   * Creates a lightweight device client that communicates through this transport.
   * The client is bound to a specific Modbus unit ID.
   *
   * @param opts - Options specifying the unit ID.
   */
  createClient(opts: CreateClientOptions): AsyncTcpModbusClient
  /**
   *  Sets the per-request timeout in milliseconds.
   * Sets the timeout for individual Modbus requests made through this transport.
   *
   * @param timeout_ms - The timeout duration in milliseconds.
   */
  setRequestTimeout(timeoutMs: number): void
  /**
   *  Clears the per-request timeout.
   * Clears any previously set per-request timeout, reverting to the default behavior.
   */
  clearRequestTimeout(): void
  /**
   *  Returns whether there are pending requests.
   * Checks if there are any Modbus requests currently in-flight on this transport.
   */
  get pendingRequests(): boolean
  /**
   *  Closes the connection.
   * Closes the underlying TCP connection and shuts down the transport.
   */
  close(): Promise<void>
  /**
   *  Reconnects the transport after a disconnect.
   * Attempts to re-establish the TCP connection if it has been closed.
   */
  reconnect(): Promise<void>
}

/** Connection options for the serial ASCII transport. */
export interface AsciiTransportOptions {
  /** Serial port path (e.g., "/dev/ttyUSB0", "COM3"). */
  portPath: string
  /** Baud rate (e.g., 9600, 19200, 38400, 57600, 115200). */
  baudRate: number
  /** Data bits (5, 6, 7, or 8). */
  dataBits?: number
  /** Parity ("none", "even", "odd"). */
  parity?: string
  /** Stop bits (1 or 2). */
  stopBits?: number
  /** Response timeout in milliseconds. */
  responseTimeoutMs?: number
  /** Per-request timeout in milliseconds. */
  requestTimeoutMs?: number
  /** Number of retry attempts on failure (0 = none). Default: 0. */
  retryAttempts?: number
  /** Delay between retry attempts in milliseconds. */
  retryDelayMs?: number
  /** Backoff strategy: "immediate", "fixed", or "exponential". Default: "immediate". */
  retryBackoffStrategy?: string
}

/** Options for creating a device client. */
export interface CreateClientOptions {
  /** Modbus unit ID (slave address) from 1 to 247. */
  unitId: number
}

/** Device identification object. */
export interface DeviceIdentificationObject {
  /** The object ID. */
  id: number
  /** The value of the object, represented as a string. */
  value: string
}

/** Response from device identification request. */
export interface DeviceIdentificationResponse {
  /** The conformity level of the device. */
  conformityLevel: number
  /** Indicates if more objects are available to be read. */
  moreFollows: boolean
  /** The ID of the next object to read if `moreFollows` is true. */
  nextObjectId: number
  /** An array of device identification objects. */
  objects: Array<DeviceIdentificationObject>
}

/** Options for diagnostics request. */
export interface DiagnosticsOptions {
  /** Diagnostic sub-function code. */
  subFunction: number
  /** Data to be sent with the diagnostics request. */
  data: Array<number>
  /** An optional `AbortSignal` to cancel the asynchronous operation. */
  signal?: AbortSignal
}

/** Handler request for diagnostics. */
export interface DiagnosticsRequest {
  /** The unit ID of the device that sent the request. */
  unitId: number
  /** The diagnostic sub-function code to execute. */
  subFunction: number
  /** Data sent with the diagnostics request. */
  data: Array<number>
}

/** Response from diagnostics request. */
export interface DiagnosticsResponse {
  /** The sub-function code from the request. */
  subFunction: number
  /** The data returned by the diagnostics function. */
  data: Array<number>
}

/** Downstream server configuration. */
export interface DownstreamConfig {
  /** Downstream server host. */
  host: string
  /** Downstream server port. */
  port: number
}

/** Response from reading FIFO queue. */
export interface FifoQueueResponse {
  /** Queue values. */
  values: Array<number>
}

/** A single file record read sub-request. */
export interface FileRecordReadRequest {
  /** The file number (1-65535). */
  fileNumber: number
  /** The starting record number within the file. */
  recordNumber: number
  /** The number of records to read. */
  recordLength: number
}

/** A single file record read sub-request on the server side. */
export interface FileRecordReadServerSubRequest {
  /** The file number (1-65535). */
  fileNumber: number
  /** The starting record number within the file. */
  recordNumber: number
  /** The number of records to read. */
  recordLength: number
}

/** A single file record write sub-request. */
export interface FileRecordWriteRequest {
  /** The file number (1-65535). */
  fileNumber: number
  /** The starting record number within the file. */
  recordNumber: number
  /** The record data to write, as an array of 16-bit values. */
  recordData: Array<number>
}

/** A single file record write sub-request on the server side. */
export interface FileRecordWriteSubRequest {
  /** The file number (1-65535). */
  fileNumber: number
  /** The starting record number within the file. */
  recordNumber: number
  /** The record data to write, as an array of 16-bit values. */
  recordData: Array<number>
}

/** Gateway bind options. */
export interface GatewayBindOptions {
  /** Bind host address (e.g., "0.0.0.0"). */
  host: string
  /** Bind port. */
  port: number
}

/** Gateway configuration. */
export interface GatewayConfig {
  /** List of downstream servers. */
  downstreams: Array<DownstreamConfig>
  /** Routing table mapping unit IDs to downstream channels. */
  routes: Array<RouteEntry>
}

/** Stable error code: The connection was closed. */
export const MODBUS_ERROR_CODE_CONNECTION_CLOSED: string

/** Stable error code: Modbus protocol exception received. */
export const MODBUS_ERROR_CODE_EXCEPTION: string

/** Stable error code: Internal library error. */
export const MODBUS_ERROR_CODE_INTERNAL: string

/** Stable error code: Invalid argument passed to the API. */
export const MODBUS_ERROR_CODE_INVALID_ARGUMENT: string

/** Stable error code: Request timed out. */
export const MODBUS_ERROR_CODE_TIMEOUT: string

/** Stable error code: Transport/framing error. */
export const MODBUS_ERROR_CODE_TRANSPORT: string

/** Options for reading coils or discrete inputs. */
export interface ReadBitsOptions {
  /** Starting address. */
  address: number
  /** Number of bits (coils or discrete inputs) to read. */
  quantity: number
  /** An optional `AbortSignal` to cancel the asynchronous operation. */
  signal?: AbortSignal
}

/** Handler request for reading coils. */
export interface ReadCoilsRequest {
  /** The unit ID of the device that sent the request. */
  unitId: number
  /** The starting address of the coils to read. */
  address: number
  /** The number of coils to read. */
  quantity: number
}

/** Options for device identification. */
export interface ReadDeviceIdentificationOptions {
  /** Read device ID code (1=basic, 2=regular, 3=extended, 4=individual). */
  readDeviceIdCode: number
  /** The ID of the first object to read. */
  objectId: number
  /** An optional `AbortSignal` to cancel the asynchronous operation. */
  signal?: AbortSignal
}

/** Handler request for reading discrete inputs. */
export interface ReadDiscreteInputsRequest {
  /** The unit ID of the device that sent the request. */
  unitId: number
  /** The starting address of the discrete inputs to read. */
  address: number
  /** The number of discrete inputs to read. */
  quantity: number
}

/** Handler request for reading exception status. */
export interface ReadExceptionStatusRequest {
  /** The unit ID of the device that sent the request. */
  unitId: number
}

/** Options for reading FIFO queue. */
export interface ReadFifoQueueOptions {
  /** FIFO pointer address. */
  address: number
  /** An optional `AbortSignal` to cancel the asynchronous operation. */
  signal?: AbortSignal
}

/** Handler request for reading FIFO queue. */
export interface ReadFifoQueueRequest {
  /** The unit ID of the device that sent the request. */
  unitId: number
  /** The address of the FIFO queue pointer register. */
  address: number
}

/** Options for reading file records. */
export interface ReadFileRecordOptions {
  /** An array of file record read sub-requests. */
  requests: Array<FileRecordReadRequest>
  /** An optional `AbortSignal` to cancel the asynchronous operation. */
  signal?: AbortSignal
}

/** Handler request for reading file records. */
export interface ReadFileRecordRequest {
  /** The unit ID of the device that sent the request. */
  unitId: number
  /** An array of file record read sub-requests. */
  requests: Array<FileRecordReadServerSubRequest>
}

/** Handler request for reading holding registers. */
export interface ReadHoldingRegistersRequest {
  /** The unit ID of the device that sent the request. */
  unitId: number
  /** The starting address of the holding registers to read. */
  address: number
  /** The number of holding registers to read. */
  quantity: number
}

/** Handler request for reading input registers. */
export interface ReadInputRegistersRequest {
  /** The unit ID of the device that sent the request. */
  unitId: number
  /** The starting address of the input registers to read. */
  address: number
  /** The number of input registers to read. */
  quantity: number
}

/** Options for reading registers. */
export interface ReadRegistersOptions {
  /** Starting register address. */
  address: number
  /** Number of registers to read (quantity). */
  quantity: number
  /** An optional `AbortSignal` to cancel the asynchronous operation. */
  signal?: AbortSignal
}

/** Options for read/write multiple registers (FC23). */
export interface ReadWriteMultipleRegistersOptions {
  /** Starting address for read operation. */
  readAddress: number
  /** Number of registers to read (quantity). */
  readQuantity: number
  /** Starting address for write operation. */
  writeAddress: number
  /** An array of 16-bit values to write. */
  writeValues: Array<number>
  /** An optional `AbortSignal` to cancel the asynchronous operation. */
  signal?: AbortSignal
}

/** Handler request for read/write multiple registers (FC23). */
export interface ReadWriteMultipleRegistersRequest {
  /** The unit ID of the device that sent the request. */
  unitId: number
  /** The starting address for the read operation. */
  readAddress: number
  /** The number of registers to read. */
  readQuantity: number
  /** The starting address for the write operation. */
  writeAddress: number
  /** The array of 16-bit values to write. */
  writeValues: Array<number>
}

/** Route entry mapping unit ID to a downstream channel. */
export interface RouteEntry {
  /** Modbus unit ID (1-247). */
  unitId: number
  /** Index into the downstreams array. */
  channel: number
}

/** Connection options for the serial RTU transport. */
export interface RtuTransportOptions {
  /** Serial port path (e.g., "/dev/ttyUSB0", "COM3"). */
  portPath: string
  /** Baud rate (e.g., 9600, 19200, 38400, 57600, 115200). */
  baudRate: number
  /** Data bits (5, 6, 7, or 8). */
  dataBits?: number
  /** Parity ("none", "even", "odd"). */
  parity?: string
  /** Stop bits (1 or 2). */
  stopBits?: number
  /** Response timeout in milliseconds. */
  responseTimeoutMs?: number
  /** Per-request timeout in milliseconds. */
  requestTimeoutMs?: number
  /** Number of retry attempts on failure (0 = none). Default: 0. */
  retryAttempts?: number
  /** Delay between retry attempts in milliseconds. */
  retryDelayMs?: number
  /** Backoff strategy: "immediate", "fixed", or "exponential". Default: "immediate". */
  retryBackoffStrategy?: string
}

/** Server bind options for serial port. */
export interface SerialServerOptions {
  /** Serial port path (e.g., "/dev/ttyUSB0", "COM3"). */
  portPath: string
  /** Baud rate (e.g., 9600, 19200, 38400, 57600, 115200). */
  baudRate: number
  /** Data bits (5, 6, 7, or 8). */
  dataBits?: number
  /** Parity ("none", "even", "odd"). */
  parity?: string
  /** Stop bits (1 or 2). */
  stopBits?: number
  /** Modbus unit ID (1-247) for the server to respond to. */
  unitId: number
  /** Response timeout in milliseconds. */
  responseTimeoutMs?: number
}

/** Handler response for diagnostics. */
export interface ServerDiagnosticsResponse {
  /** The sub-function code from the request. */
  subFunction: number
  /** The data to be returned by the diagnostics function. */
  data: Array<number>
}

/** Response that may include an exception code. */
export interface ServerExceptionResponse {
  /**
   * The Modbus exception code (e.g., 1 for Illegal Function).
   *  Modbus exception code if this is an error response.
   */
  exception?: number
}

/** Server bind options. */
export interface TcpServerOptions {
  /** Bind host address (e.g., "0.0.0.0"). */
  host: string
  /** Bind port. */
  port: number
  /** Modbus unit ID to respond to. */
  unitId: number
}

/** Connection options for the TCP transport. */
export interface TcpTransportOptions {
  /** Target host address (IP or hostname). */
  host: string
  /** Target TCP port (typically 502). */
  port: number
  /** Per-request timeout in milliseconds. */
  requestTimeoutMs?: number
  /** Number of retry attempts on failure. Default: 0 (no retries). */
  retryAttempts?: number
  /** Delay between retry attempts in milliseconds. */
  retryDelayMs?: number
  /** Backoff strategy for retries: "immediate", "fixed", or "exponential". Default: "immediate". */
  retryBackoffStrategy?: string
}

/** Options for writing file records. */
export interface WriteFileRecordOptions {
  /** An array of file record write sub-requests. */
  requests: Array<FileRecordWriteRequest>
  /** An optional `AbortSignal` to cancel the asynchronous operation. */
  signal?: AbortSignal
}

/** Handler request for writing file records. */
export interface WriteFileRecordRequest {
  /** The unit ID of the device that sent the request. */
  unitId: number
  /** An array of file record write sub-requests. */
  requests: Array<FileRecordWriteSubRequest>
}

/** Options for writing multiple coils. */
export interface WriteMultipleCoilsOptions {
  /** Starting coil address. */
  address: number
  /** An array of boolean values to write. */
  values: Array<boolean>
  /** An optional `AbortSignal` to cancel the asynchronous operation. */
  signal?: AbortSignal
}

/** Handler request for writing multiple coils. */
export interface WriteMultipleCoilsRequest {
  /** The unit ID of the device that sent the request. */
  unitId: number
  /** The starting address of the coils to write to. */
  address: number
  /** The array of boolean values to write. */
  values: Array<boolean>
}

/** Options for writing multiple registers. */
export interface WriteMultipleRegistersOptions {
  /** Starting register address. */
  address: number
  /** An array of 16-bit values to write. */
  values: Array<number>
  /** An optional `AbortSignal` to cancel the asynchronous operation. */
  signal?: AbortSignal
}

/** Handler request for writing multiple registers. */
export interface WriteMultipleRegistersRequest {
  /** The unit ID of the device that sent the request. */
  unitId: number
  /** The starting address of the registers to write to. */
  address: number
  /** The array of 16-bit values to write. */
  values: Array<number>
}

/** Options for writing a single coil. */
export interface WriteSingleCoilOptions {
  /** Coil address. */
  address: number
  /** The boolean value to write (true for ON, false for OFF). */
  value: boolean
  /** An optional `AbortSignal` to cancel the asynchronous operation. */
  signal?: AbortSignal
}

/** Handler request for writing a single coil. */
export interface WriteSingleCoilRequest {
  /** The unit ID of the device that sent the request. */
  unitId: number
  /** The address of the coil to write to. */
  address: number
  /** The value to write (true for ON, false for OFF). */
  value: boolean
}

/** Options for writing a single register. */
export interface WriteSingleRegisterOptions {
  /** Register address. */
  address: number
  /** The 16-bit value to write to the register. */
  value: number
  /** An optional `AbortSignal` to cancel the asynchronous operation. */
  signal?: AbortSignal
}

/** Handler request for writing a single register. */
export interface WriteSingleRegisterRequest {
  /** The unit ID of the device that sent the request. */
  unitId: number
  /** The address of the register to write to. */
  address: number
  /** The 16-bit value to write. */
  value: number
}

export interface ModbusException {
  exception: number;
}

/**
 * Callback functions to handle Modbus server requests.
 * 
 * Each handler corresponds to a specific Modbus function code. If a handler is not provided,
 * the server will respond with an "Illegal Function" exception (0x01).
 * 
 * Handlers can return the expected data directly or return a Promise for async operations.
 * To return a Modbus exception, return an object matching the `ModbusException` interface.
 */
export interface ServerHandlers {
  /**
   * Handle Read Coils (FC 01).
   * @param req The request object.
   * @param req.address The starting coil address (0x0000 to 0xFFFF).
   * @param req.quantity The number of coils to read (1 to 2000).
   * @returns An array of booleans representing the coil states, or a ModbusException.
   */
  onReadCoils?: (req: ReadCoilsRequest) => boolean[] | ModbusException | Promise<boolean[] | ModbusException>;

  /**
   * Handle Read Discrete Inputs (FC 02).
   * @param req The request object.
   * @param req.address The starting discrete input address (0x0000 to 0xFFFF).
   * @param req.quantity The number of inputs to read (1 to 2000).
   * @returns An array of booleans representing the input states, or a ModbusException.
   */
  onReadDiscreteInputs?: (req: ReadDiscreteInputsRequest) => boolean[] | ModbusException | Promise<boolean[] | ModbusException>;

  /**
   * Handle Read Holding Registers (FC 03).
   * @param req The request object.
   * @param req.address The starting holding register address (0x0000 to 0xFFFF).
   * @param req.quantity The number of registers to read (1 to 125).
   * @returns An array of 16-bit numbers representing the registers, or a ModbusException.
   */
  onReadHoldingRegisters?: (req: ReadHoldingRegistersRequest) => number[] | ModbusException | Promise<number[] | ModbusException>;

  /**
   * Handle Read Input Registers (FC 04).
   * @param req The request object.
   * @param req.address The starting input register address (0x0000 to 0xFFFF).
   * @param req.quantity The number of registers to read (1 to 125).
   * @returns An array of 16-bit numbers representing the registers, or a ModbusException.
   */
  onReadInputRegisters?: (req: ReadInputRegistersRequest) => number[] | ModbusException | Promise<number[] | ModbusException>;

  /**
   * Handle Write Single Coil (FC 05).
   * @param req The request object.
   * @param req.address The address of the coil to write (0x0000 to 0xFFFF).
   * @param req.value The boolean value to write (true for ON, false for OFF).
   * @returns void on success, or a ModbusException.
   */
  onWriteSingleCoil?: (req: WriteSingleCoilRequest) => void | ModbusException | Promise<void | ModbusException>;

  /**
   * Handle Write Single Register (FC 06).
   * @param req The request object.
   * @param req.address The address of the register to write (0x0000 to 0xFFFF).
   * @param req.value The 16-bit value to write.
   * @returns void on success, or a ModbusException.
   */
  onWriteSingleRegister?: (req: WriteSingleRegisterRequest) => void | ModbusException | Promise<void | ModbusException>;

  /**
   * Handle Read Exception Status (FC 07).
   * @param req The read exception status request object (empty).
   * @returns An 8-bit exception status byte, or a ModbusException.
   */
  onReadExceptionStatus?: (req: ReadExceptionStatusRequest) => number | ModbusException | Promise<number | ModbusException>;

  /**
   * Handle Diagnostics (FC 08).
   * @param req The diagnostics request object.
   * @param req.subFunction The 16-bit sub-function code.
   * @param req.data The 16-bit data payload for the sub-function.
   * @returns A response containing the sub-function and data, or a ModbusException.
   */
  onDiagnostics?: (req: DiagnosticsRequest) => ServerDiagnosticsResponse | ModbusException | Promise<ServerDiagnosticsResponse | ModbusException>;

  /**
   * Handle Write Multiple Coils (FC 15).
   * @param req The request object.
   * @param req.address The starting address of the coils to write.
   * @param req.values An array of booleans to write.
   * @returns void on success, or a ModbusException.
   */
  onWriteMultipleCoils?: (req: WriteMultipleCoilsRequest) => void | ModbusException | Promise<void | ModbusException>;

  /**
   * Handle Write Multiple Registers (FC 16).
   * @param req The request object.
   * @param req.address The starting address of the registers to write.
   * @param req.values An array of 16-bit numbers to write.
   * @returns void on success, or a ModbusException.
   */
  onWriteMultipleRegisters?: (req: WriteMultipleRegistersRequest) => void | ModbusException | Promise<void | ModbusException>;

  /**
   * Handle Read File Record (FC 20).
   * @param req The request object.
   * @param req.subRequests An array of sub-requests, each with `fileNumber`, `recordNumber`, and `recordLength`.
   * @returns An array of register arrays for each sub-request, or a ModbusException.
   */
  onReadFileRecord?: (req: ReadFileRecordRequest) => number[][] | ModbusException | Promise<number[][] | ModbusException>;

  /**
   * Handle Write File Record (FC 21).
   * @param req The request object.
   * @param req.subRequests An array of sub-requests, each with `fileNumber`, `recordNumber`, and `recordData` (a number array).
   * @returns void on success, or a ModbusException.
   */
  onWriteFileRecord?: (req: WriteFileRecordRequest) => void | ModbusException | Promise<void | ModbusException>;

  /**
   * Handle Read/Write Multiple Registers (FC 23).
   * @param req The request containing addresses and values to read and write.
   * @param req.readAddress The starting address for the read operation.
   * @param req.readQuantity The number of registers to read.
   * @param req.writeAddress The starting address for the write operation.
   * @param req.values An array of 16-bit numbers to write.
   * @returns An array of 16-bit numbers read, or a ModbusException.
   */
  onReadWriteMultipleRegisters?: (req: ReadWriteMultipleRegistersRequest) => number[] | ModbusException | Promise<number[] | ModbusException>;

  /**
   * Handle Read FIFO Queue (FC 24).
   * @param req The request object containing the FIFO pointer `address`.
   * @returns An array of 16-bit numbers from the queue, or a ModbusException.
   */
  onReadFifoQueue?: (req: ReadFifoQueueRequest) => number[] | ModbusException | Promise<number[] | ModbusException>;
}

/**
 * Stable error codes for identifying Modbus-related errors.
 * These can be used with the `getModbusErrorCode` helper to check for specific error types.
 */
export declare const ModbusErrorCode: {
  /** A Modbus exception response was received from the server (e.g., illegal function). */
  readonly EXCEPTION: 'MODBUS_EXCEPTION';
  /** The request timed out waiting for a response. */
  readonly TIMEOUT: 'MODBUS_TIMEOUT';
  /** A transport-level error occurred (e.g., framing error, checksum mismatch). */
  readonly TRANSPORT: 'MODBUS_TRANSPORT';
  /** An invalid argument was provided to a client or server function. */
  readonly INVALID_ARGUMENT: 'MODBUS_INVALID_ARGUMENT';
  /** The underlying connection was closed. */
  readonly CONNECTION_CLOSED: 'MODBUS_CONNECTION_CLOSED';
  /** An unexpected internal error occurred within the library. */
  readonly INTERNAL: 'MODBUS_INTERNAL';
};

/**
 * Extracts a stable error code from a Modbus error object.
 * @param err The error object.
 * @returns The corresponding code from `ModbusErrorCode`, or undefined if not a Modbus error.
 */
export declare function getModbusErrorCode(err: Error): string | undefined;
