#ifndef MODBUS_RS_GO_H
#define MODBUS_RS_GO_H

#pragma once

/* Auto-generated by cbindgen — DO NOT EDIT.
   Regenerate with: cargo build -p mbus-ffi --features go,full */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
typedef struct MbusGoTcpClient MbusGoTcpClient;
typedef struct MbusGoSerialClient MbusGoSerialClient;
typedef struct MbusGoTcpServer MbusGoTcpServer;
typedef struct MbusGoTcpGateway MbusGoTcpGateway;
/* Forward declarations for sibling-binding types that cbindgen leaks
   into this header even though their cfgs are disabled.  They are not
   reachable from the Go ABI; the typedefs make the header
   self-consistent so cgo can compile it cleanly. */
typedef struct MbusCoils MbusCoils;
typedef struct MbusDiscreteInputs MbusDiscreteInputs;
typedef struct MbusFifoQueue MbusFifoQueue;
typedef struct MbusRegisters MbusRegisters;
typedef uint16_t MbusClientId;
typedef uint16_t MbusServerId;
typedef uint16_t MbusGatewayId;
/**
 * C-compatible status code returned by every `mbus_*` function.
 *
 * `MBUS_OK` (0) means the request was successfully queued. Actual response data
 * is delivered later via the callbacks in `MbusCallbacks`.
 */
typedef enum MbusStatusCode {
    /**
     * Success.
     */
    MbusOk = 0,
    /**
     * Frame parse error.
     */
    MbusErrParseError,
    /**
     * Basic parse error.
     */
    MbusErrBasicParseError,
    /**
     * Response timeout.
     */
    MbusErrTimeout,
    /**
     * Modbus exception response.
     */
    MbusErrModbusException,
    /**
     * I/O error.
     */
    MbusErrIoError,
    /**
     * Unexpected error.
     */
    MbusErrUnexpected,
    /**
     * Connection lost.
     */
    MbusErrConnectionLost,
    /**
     * Unsupported function.
     */
    MbusErrUnsupportedFunction,
    /**
     * Reserved sub-function.
     */
    MbusErrReservedSubFunction,
    /**
     * Invalid PDU length.
     */
    MbusErrInvalidPduLength,
    /**
     * Invalid ADU length.
     */
    MbusErrInvalidAduLength,
    /**
     * Connection failed.
     */
    MbusErrConnectionFailed,
    /**
     * Connection closed.
     */
    MbusErrConnectionClosed,
    /**
     * Buffer too small.
     */
    MbusErrBufferTooSmall,
    /**
     * Buffer length mismatch.
     */
    MbusErrBufferLenMismatch,
    /**
     * Send failed.
     */
    MbusErrSendFailed,
    /**
     * Invalid address.
     */
    MbusErrInvalidAddress,
    /**
     * Invalid offset.
     */
    MbusErrInvalidOffset,
    /**
     * Too many in-flight requests.
     */
    MbusErrTooManyRequests,
    /**
     * Invalid function code.
     */
    MbusErrInvalidFunctionCode,
    /**
     * No retries left.
     */
    MbusErrNoRetriesLeft,
    /**
     * Too many file read sub-requests.
     */
    MbusErrTooManyFileReadSubRequests,
    /**
     * File read PDU overflow.
     */
    MbusErrFileReadPduOverflow,
    /**
     * Unexpected response.
     */
    MbusErrUnexpectedResponse,
    /**
     * Invalid transport.
     */
    MbusErrInvalidTransport,
    /**
     * Invalid slave address.
     */
    MbusErrInvalidSlaveAddress,
    /**
     * Checksum error.
     */
    MbusErrChecksumError,
    /**
     * Invalid configuration.
     */
    MbusErrInvalidConfiguration,
    /**
     * Invalid number of expected responses.
     */
    MbusErrInvalidNumOfExpectedRsps,
    /**
     * Invalid data length.
     */
    MbusErrInvalidDataLen,
    /**
     * Invalid quantity.
     */
    MbusErrInvalidQuantity,
    /**
     * Invalid value.
     */
    MbusErrInvalidValue,
    /**
     * Invalid AND mask.
     */
    MbusErrInvalidAndMask,
    /**
     * Invalid OR mask.
     */
    MbusErrInvalidOrMask,
    /**
     * Invalid byte count.
     */
    MbusErrInvalidByteCount,
    /**
     * Invalid device identification.
     */
    MbusErrInvalidDeviceIdentification,
    /**
     * Invalid device ID code.
     */
    MbusErrInvalidDeviceIdCode,
    /**
     * Invalid MEI type.
     */
    MbusErrInvalidMeiType,
    /**
     * Invalid broadcast address.
     */
    MbusErrInvalidBroadcastAddress,
    /**
     * Broadcast not allowed.
     */
    MbusErrBroadcastNotAllowed,
    /**
     * Null pointer passed.
     */
    MbusErrNullPointer,
    /**
     * Invalid UTF-8 string.
     */
    MbusErrInvalidUtf8,
    /**
     * Invalid client ID (freed or never allocated).
     */
    MbusErrInvalidClientId,
    /**
     * Client pool is full — no free slots.
     */
    MbusErrPoolFull,
    /**
     * Client type mismatch (e.g. TCP call on serial ID).
     */
    MbusErrClientTypeMismatch,
    /**
     * Client is busy (indicates an illegal re-entrant call from a callback).
     */
    MbusErrBusy,
} MbusStatusCode;
/**
 * Serial framing mode.
 */
typedef enum MbusSerialMode {
    /**
     * Modbus RTU binary framing with CRC-16.
     */
    MbusSerialRtu = 0,
    /**
     * Modbus ASCII framing with LRC.
     */
    MbusSerialAscii,
} MbusSerialMode;
/**
 * Backoff strategy selector for retry logic.
 */
typedef enum MbusBackoffStrategy {
    /**
     * Retry immediately with no delay.
     */
    MbusBackoffImmediate = 0,
    /**
     * Retry after a fixed delay (`backoff_base_delay_ms`).
     */
    MbusBackoffFixed,
    /**
     * Retry with exponentially increasing delay, capped at `backoff_max_delay_ms`.
     */
    MbusBackoffExponential,
    /**
     * Retry with linearly increasing delay, capped at `backoff_max_delay_ms`.
     */
    MbusBackoffLinear,
} MbusBackoffStrategy;
/**
 * Exception code returned by every C server callback.
 *
 * Maps 1-to-1 with the Modbus standard exception codes:
 * - `0x01` IllegalFunction
 * - `0x02` IllegalDataAddress
 * - `0x03` IllegalDataValue
 * - `0x04` ServerDeviceFailure
 *
 * The value `Ok = 0` is a non-standard sentinel used by this API to signal
 * "request handled successfully; no exception".
 */
typedef enum MbusServerExceptionCode {
    /**
     * No exception — the callback handled the request successfully.
     */
    Ok = 0,
    /**
     * FC is not supported / not implemented by this server.
     */
    IllegalFunction = 1,
    /**
     * Address or offset is outside the server's valid range.
     */
    IllegalDataAddress = 2,
    /**
     * A data value in the request is not acceptable.
     */
    IllegalDataValue = 3,
    /**
     * The server could not complete the request due to an internal failure.
     */
    ServerDeviceFailure = 4,
} MbusServerExceptionCode;
/**
 * Opaque handle to an asynchronous Modbus serial client (RTU or ASCII).
 */
typedef struct MbusDnSerialClient MbusDnSerialClient;
/**
 * Configuration for a Modbus Serial (RTU or ASCII) client.
 *
 * `port_name` must remain valid for the duration of `mbus_serial_client_new`.
 */
typedef struct MbusSerialConfig {
    /**
     * Null-terminated serial port path (e.g. `"/dev/ttyUSB0"` or `"COM3"`).
     */
    const char *port_name;
    /**
     * Baud rate (e.g. 9600, 19200, 115200).
     */
    uint32_t baud_rate;
    /**
     * Framing mode: RTU or ASCII.
     */
    enum MbusSerialMode mode;
    /**
     * Timeout waiting for a Modbus response, in milliseconds.
     */
    uint32_t response_timeout_ms;
    /**
     * Number of retry attempts.
     */
    uint8_t retries;
    /**
     * Backoff strategy between retries.
     */
    enum MbusBackoffStrategy backoff_strategy;
    /**
     * Base delay (ms).
     */
    uint32_t backoff_base_delay_ms;
    /**
     * Maximum delay cap (ms).
     */
    uint32_t backoff_max_delay_ms;
    /**
     * Jitter percentage (0–100).
     */
    uint8_t jitter_percent;
} MbusSerialConfig;
/**
 * C-provided transport callbacks.
 *
 * All five callbacks must be non-`NULL` for a valid transport.
 * `userdata` is threaded through every callback invocation.
 */
typedef struct MbusTransportCallbacks {
    /**
     * Opaque user context threaded to every callback.
     */
    void *userdata;
    /**
     * Called to open/connect the transport.
     */
    enum MbusStatusCode (*on_connect)(void *userdata);
    /**
     * Called to close/disconnect the transport.
     */
    enum MbusStatusCode (*on_disconnect)(void *userdata);
    /**
     * Called to send a frame.
     */
    enum MbusStatusCode (*on_send)(const uint8_t *data, uint16_t len, void *userdata);
    /**
     * Called to receive a frame.
     */
    enum MbusStatusCode (*on_recv)(uint8_t *buffer,
                                   uint16_t buffer_cap,
                                   uint16_t *out_len,
                                   void *userdata);
    /**
     * Called to query connection state.
     */
    uint8_t (*on_is_connected)(void *userdata);
} MbusTransportCallbacks;
/**
 * Configuration for a Modbus TCP client.
 *
 * All pointer fields (`host`) must remain valid for the duration of the
 * `mbus_tcp_client_new` call. They are copied internally and do not need to
 * outlive the call.
 */
typedef struct MbusTcpConfig {
    /**
     * Null-terminated hostname or IPv4/IPv6 address string (max 63 bytes excl. NUL).
     */
    const char *host;
    /**
     * TCP port (default Modbus port is 502).
     */
    uint16_t port;
    /**
     * Timeout waiting for the TCP connection to be established, in milliseconds.
     */
    uint32_t connection_timeout_ms;
    /**
     * Timeout waiting for a Modbus response, in milliseconds.
     */
    uint32_t response_timeout_ms;
    /**
     * Number of retry attempts before reporting failure via the error callback.
     */
    uint8_t retries;
    /**
     * Backoff strategy between retries.
     */
    enum MbusBackoffStrategy backoff_strategy;
    /**
     * Base delay (ms) used by `MbusBackoffFixed`, `MbusBackoffExponential`, and
     * `MbusBackoffLinear`.
     */
    uint32_t backoff_base_delay_ms;
    /**
     * Maximum delay cap (ms) used by `MbusBackoffExponential` and `MbusBackoffLinear`.
     */
    uint32_t backoff_max_delay_ms;
    /**
     * Jitter percentage (0 = no jitter, 1–100 = ±N% random spread on top of backoff).
     */
    uint8_t jitter_percent;
} MbusTcpConfig;
/**
 * A single sub-request passed to [`mbus_tcp_read_file_record`] /
 * [`mbus_tcp_write_file_record`] (and their serial equivalents).
 *
 * For **read** operations: populate `file_number`, `record_number`, and
 * `data_len` (number of registers to read); set `data` to NULL.
 *
 * For **write** operations: populate all four fields; `data` must point to
 * at least `data_len` valid `u16` words.
 */
typedef struct MbusSubRequest {
    /**
     * File number (1–65535).
     */
    uint16_t file_number;
    /**
     * Starting record number within the file.
     */
    uint16_t record_number;
    /**
     * Number of 16-bit registers (length). For reads: how many to read.
     * For writes: must equal `data_len`.
     */
    uint16_t record_length;
    /**
     * Pointer to write data (NULL for reads). Valid only during the call.
     */
    const uint16_t *data;
    /**
     * Number of valid words pointed to by `data` (0 for reads).
     */
    uint16_t data_len;
} MbusSubRequest;
/**
 * Request context for FC 0x01 — Read Coils.
 *
 * C reads `address` and `quantity`; writes packed coil bits into `out_data` (at most
 * `out_data_len` bytes) and sets `out_byte_count` to the number of bytes written.
 */
typedef struct MbusServerReadCoilsReq {
    /**
     * Slave/unit address of the request.
     */
    uint8_t unit_id;
    /**
     * Transaction ID (MBAP) or 0 for serial.
     */
    uint16_t txn_id;
    /**
     * Starting coil address.
     */
    uint16_t address;
    /**
     * Number of coils to read.
     */
    uint16_t quantity;
    /**
     * Buffer to write packed coil bytes into (Rust-allocated, valid for callback duration).
     */
    uint8_t *out_data;
    /**
     * Capacity of `out_data` in bytes.
     */
    uintptr_t out_data_len;
    /**
     * C must set this to the number of bytes written into `out_data`.
     */
    uint8_t out_byte_count;
} MbusServerReadCoilsReq;
/**
 * C callback type for FC 0x01.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadCoilsFn)(struct MbusServerReadCoilsReq *req,
                                                              void *userdata);
/**
 * Request context for FC 0x05 — Write Single Coil.
 */
typedef struct MbusServerWriteSingleCoilReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t address;
    /**
     * `true` = force coil ON, `false` = force coil OFF.
     */
    bool value;
} MbusServerWriteSingleCoilReq;
/**
 * C callback type for FC 0x05.
 */
typedef enum MbusServerExceptionCode (*MbusServerWriteSingleCoilFn)(const struct MbusServerWriteSingleCoilReq *req,
                                                                    void *userdata);
/**
 * Request context for FC 0x0F — Write Multiple Coils.
 *
 * `values` is a packed bit array from the master (LSB of first byte = coil at
 * `starting_address`). Valid for the duration of the callback only.
 */
typedef struct MbusServerWriteMultipleCoilsReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t starting_address;
    uint16_t quantity;
    /**
     * Packed coil bits from the master (read-only, valid for callback duration).
     */
    const uint8_t *values;
    /**
     * Number of bytes in `values`.
     */
    uintptr_t values_len;
} MbusServerWriteMultipleCoilsReq;
/**
 * C callback type for FC 0x0F.
 */
typedef enum MbusServerExceptionCode (*MbusServerWriteMultipleCoilsFn)(const struct MbusServerWriteMultipleCoilsReq *req,
                                                                       void *userdata);
/**
 * Request context for FC 0x02 — Read Discrete Inputs.
 */
typedef struct MbusServerReadDiscreteInputsReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t address;
    uint16_t quantity;
    uint8_t *out_data;
    uintptr_t out_data_len;
    uint8_t out_byte_count;
} MbusServerReadDiscreteInputsReq;
/**
 * C callback type for FC 0x02.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadDiscreteInputsFn)(struct MbusServerReadDiscreteInputsReq *req,
                                                                       void *userdata);
/**
 * Request context for FC 0x03 — Read Holding Registers.
 *
 * `out_data` receives big-endian register bytes (2 bytes per register).
 * `out_byte_count` must be set to `quantity * 2` on success.
 */
typedef struct MbusServerReadHoldingRegistersReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t address;
    uint16_t quantity;
    uint8_t *out_data;
    uintptr_t out_data_len;
    uint8_t out_byte_count;
} MbusServerReadHoldingRegistersReq;
/**
 * C callback type for FC 0x03.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadHoldingRegistersFn)(struct MbusServerReadHoldingRegistersReq *req,
                                                                         void *userdata);
/**
 * Request context for FC 0x06 — Write Single Register.
 */
typedef struct MbusServerWriteSingleRegisterReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t address;
    uint16_t value;
} MbusServerWriteSingleRegisterReq;
/**
 * C callback type for FC 0x06.
 */
typedef enum MbusServerExceptionCode (*MbusServerWriteSingleRegisterFn)(const struct MbusServerWriteSingleRegisterReq *req,
                                                                        void *userdata);
/**
 * Request context for FC 0x10 — Write Multiple Registers.
 *
 * `values` contains the decoded `u16` register values (big-endian already parsed).
 * Valid for the duration of the callback only.
 */
typedef struct MbusServerWriteMultipleRegistersReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t starting_address;
    /**
     * Decoded register values from the master (read-only, valid for callback duration).
     */
    const uint16_t *values;
    /**
     * Number of elements in `values`.
     */
    uintptr_t values_len;
} MbusServerWriteMultipleRegistersReq;
/**
 * C callback type for FC 0x10.
 */
typedef enum MbusServerExceptionCode (*MbusServerWriteMultipleRegistersFn)(const struct MbusServerWriteMultipleRegistersReq *req,
                                                                           void *userdata);
/**
 * Request context for FC 0x16 — Mask Write Register.
 */
typedef struct MbusServerMaskWriteRegisterReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t address;
    uint16_t and_mask;
    uint16_t or_mask;
} MbusServerMaskWriteRegisterReq;
/**
 * C callback type for FC 0x16.
 */
typedef enum MbusServerExceptionCode (*MbusServerMaskWriteRegisterFn)(const struct MbusServerMaskWriteRegisterReq *req,
                                                                      void *userdata);
/**
 * Request context for FC 0x17 — Read/Write Multiple Registers.
 *
 * C writes the read result into `out_data` (big-endian register bytes) and sets
 * `out_byte_count`. `write_values` contains the decoded write values from the master.
 */
typedef struct MbusServerReadWriteMultipleRegistersReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t read_address;
    uint16_t read_quantity;
    uint16_t write_address;
    /**
     * Decoded write values from the master (read-only, valid for callback duration).
     */
    const uint16_t *write_values;
    uintptr_t write_values_len;
    uint8_t *out_data;
    uintptr_t out_data_len;
    /**
     * C must set to the number of bytes written into `out_data`.
     */
    uint8_t out_byte_count;
} MbusServerReadWriteMultipleRegistersReq;
/**
 * C callback type for FC 0x17.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadWriteMultipleRegistersFn)(struct MbusServerReadWriteMultipleRegistersReq *req,
                                                                               void *userdata);
/**
 * Request context for FC 0x04 — Read Input Registers.
 */
typedef struct MbusServerReadInputRegistersReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t address;
    uint16_t quantity;
    uint8_t *out_data;
    uintptr_t out_data_len;
    uint8_t out_byte_count;
} MbusServerReadInputRegistersReq;
/**
 * C callback type for FC 0x04.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadInputRegistersFn)(struct MbusServerReadInputRegistersReq *req,
                                                                       void *userdata);
/**
 * Request context for FC 0x18 — Read FIFO Queue.
 */
typedef struct MbusServerReadFifoQueueReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t pointer_address;
    uint8_t *out_data;
    uintptr_t out_data_len;
    /**
     * C must set to the number of bytes written.
     */
    uint8_t out_byte_count;
} MbusServerReadFifoQueueReq;
/**
 * C callback type for FC 0x18.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadFifoQueueFn)(struct MbusServerReadFifoQueueReq *req,
                                                                  void *userdata);
/**
 * Request context for FC 0x14 — Read File Record (one sub-request at a time).
 *
 * C writes record data bytes into `out_data` and sets `out_byte_count`.
 */
typedef struct MbusServerReadFileRecordReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t file_number;
    uint16_t record_number;
    uint16_t record_length;
    uint8_t *out_data;
    uintptr_t out_data_len;
    /**
     * C must set to the number of bytes written into `out_data`.
     */
    uint8_t out_byte_count;
} MbusServerReadFileRecordReq;
/**
 * C callback type for FC 0x14.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadFileRecordFn)(struct MbusServerReadFileRecordReq *req,
                                                                   void *userdata);
/**
 * Request context for FC 0x15 — Write File Record (one sub-request at a time).
 *
 * `record_data` contains decoded `u16` words. Valid for the callback duration only.
 */
typedef struct MbusServerWriteFileRecordReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t file_number;
    uint16_t record_number;
    uint16_t record_length;
    /**
     * Decoded record data words (read-only, valid for callback duration).
     */
    const uint16_t *record_data;
    uintptr_t record_data_len;
} MbusServerWriteFileRecordReq;
/**
 * C callback type for FC 0x15.
 */
typedef enum MbusServerExceptionCode (*MbusServerWriteFileRecordFn)(const struct MbusServerWriteFileRecordReq *req,
                                                                    void *userdata);
/**
 * Request context for FC 0x07 — Read Exception Status.
 *
 * C sets `out_status` to the 8-bit exception status byte.
 */
typedef struct MbusServerReadExceptionStatusReq {
    uint8_t unit_id;
    uint16_t txn_id;
    /**
     * C must set this to the 8-bit exception status byte.
     */
    uint8_t out_status;
} MbusServerReadExceptionStatusReq;
/**
 * C callback type for FC 0x07.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadExceptionStatusFn)(struct MbusServerReadExceptionStatusReq *req,
                                                                        void *userdata);
/**
 * Request context for FC 0x08 — Diagnostics.
 *
 * `sub_function` is the raw 16-bit sub-function code (see Modbus spec §6.8).
 * C sets `out_result` to the 16-bit data echo/result.
 */
typedef struct MbusServerDiagnosticsReq {
    uint8_t unit_id;
    uint16_t txn_id;
    /**
     * Raw sub-function code (e.g. 0x0000 = Return Query Data, 0x0002 = Return Diagnostic Register).
     */
    uint16_t sub_function;
    /**
     * Data word from the request.
     */
    uint16_t data;
    /**
     * C must set this to the 16-bit result/echo value.
     */
    uint16_t out_result;
} MbusServerDiagnosticsReq;
/**
 * C callback type for FC 0x08.
 */
typedef enum MbusServerExceptionCode (*MbusServerDiagnosticsFn)(struct MbusServerDiagnosticsReq *req,
                                                                void *userdata);
/**
 * Request context for FC 0x0B — Get Comm Event Counter.
 *
 * C sets `out_status` (status word) and `out_event_count`.
 */
typedef struct MbusServerGetCommEventCounterReq {
    uint8_t unit_id;
    uint16_t txn_id;
    /**
     * C must set this to the status word.
     */
    uint16_t out_status;
    /**
     * C must set this to the event counter value.
     */
    uint16_t out_event_count;
} MbusServerGetCommEventCounterReq;
/**
 * C callback type for FC 0x0B.
 */
typedef enum MbusServerExceptionCode (*MbusServerGetCommEventCounterFn)(struct MbusServerGetCommEventCounterReq *req,
                                                                        void *userdata);
/**
 * Request context for FC 0x0C — Get Comm Event Log.
 *
 * C writes event bytes into `out_events` (max `out_events_len` bytes) and
 * sets the four output scalar fields.
 */
typedef struct MbusServerGetCommEventLogReq {
    uint8_t unit_id;
    uint16_t txn_id;
    /**
     * Buffer for event log bytes (Rust-allocated, valid for callback duration).
     */
    uint8_t *out_events;
    /**
     * Capacity of `out_events`.
     */
    uintptr_t out_events_len;
    /**
     * C must set to the Status word.
     */
    uint16_t out_status;
    /**
     * C must set to the Event Count.
     */
    uint16_t out_event_count;
    /**
     * C must set to the Message Count.
     */
    uint16_t out_message_count;
    /**
     * C must set to the number of events written into `out_events`.
     */
    uint8_t out_num_events;
} MbusServerGetCommEventLogReq;
/**
 * C callback type for FC 0x0C.
 */
typedef enum MbusServerExceptionCode (*MbusServerGetCommEventLogFn)(struct MbusServerGetCommEventLogReq *req,
                                                                    void *userdata);
/**
 * Request context for FC 0x11 — Report Server ID.
 *
 * C writes vendor/device identification bytes into `out_server_id` and sets
 * `out_byte_count` and `out_run_indicator_status`.
 */
typedef struct MbusServerReportServerIdReq {
    uint8_t unit_id;
    uint16_t txn_id;
    /**
     * Buffer for server ID bytes (Rust-allocated).
     */
    uint8_t *out_server_id;
    /**
     * Capacity of `out_server_id`.
     */
    uintptr_t out_server_id_len;
    /**
     * C must set to the number of Server ID bytes written.
     */
    uint8_t out_byte_count;
    /**
     * C must set to the Run Indicator Status byte (0x00 = OFF, 0xFF = ON).
     */
    uint8_t out_run_indicator_status;
} MbusServerReportServerIdReq;
/**
 * C callback type for FC 0x11.
 */
typedef enum MbusServerExceptionCode (*MbusServerReportServerIdFn)(struct MbusServerReportServerIdReq *req,
                                                                   void *userdata);
/**
 * Request context for FC 0x2B / MEI 0x0E — Read Device Identification.
 *
 * C writes object data into `out_data` and sets all `out_*` fields.
 */
typedef struct MbusServerReadDeviceIdentificationReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint8_t read_device_id_code;
    uint8_t start_object_id;
    uint8_t *out_data;
    uintptr_t out_data_len;
    /**
     * C must set to the conformity level byte.
     */
    uint8_t out_conformity_level;
    /**
     * C must set to the "more follows" object ID (0x00 if none).
     */
    uint8_t out_more_follows_object_id;
    /**
     * C must set to `true` if more objects follow (segmentation).
     */
    bool out_has_more;
    /**
     * C must set to the next Object ID to request (only valid when `out_has_more` is true).
     */
    uint8_t out_next_object_id;
    /**
     * C must set to the number of bytes written into `out_data`.
     */
    uint8_t out_byte_count;
} MbusServerReadDeviceIdentificationReq;
/**
 * C callback type for FC 0x2B / MEI 0x0E.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadDeviceIdentificationFn)(struct MbusServerReadDeviceIdentificationReq *req,
                                                                             void *userdata);
/**
 * Master callback table for a C Modbus server application.
 *
 * Pass a populated instance of this struct to `mbus_tcp_server_new` or
 * `mbus_serial_server_new`. Any callback left as `NULL` will cause the server
 * to respond with `ExceptionCode::IllegalFunction` for that function code.
 *
 * The `userdata` pointer is passed as-is to every callback. It is the caller's
 * responsibility to ensure its lifetime exceeds the server's.
 *
 * # Example (C)
 *
 * ```c
 * static MbusServerHandlers g_handlers = {
 *     .userdata         = &my_app_state,
 *     .on_read_coils    = my_read_coils_handler,
 *     .on_write_single_coil = my_write_single_coil_handler,
 *     // leave other fields NULL to return IllegalFunction
 * };
 * ```
 */
typedef struct MbusServerHandlers {
    /**
     * Opaque pointer passed to every callback.
     */
    void *userdata;
    MbusServerReadCoilsFn on_read_coils;
    MbusServerWriteSingleCoilFn on_write_single_coil;
    MbusServerWriteMultipleCoilsFn on_write_multiple_coils;
    MbusServerReadDiscreteInputsFn on_read_discrete_inputs;
    MbusServerReadHoldingRegistersFn on_read_holding_registers;
    MbusServerWriteSingleRegisterFn on_write_single_register;
    MbusServerWriteMultipleRegistersFn on_write_multiple_registers;
    MbusServerMaskWriteRegisterFn on_mask_write_register;
    MbusServerReadWriteMultipleRegistersFn on_read_write_multiple_registers;
    MbusServerReadInputRegistersFn on_read_input_registers;
    MbusServerReadFifoQueueFn on_read_fifo_queue;
    MbusServerReadFileRecordFn on_read_file_record;
    MbusServerWriteFileRecordFn on_write_file_record;
    MbusServerReadExceptionStatusFn on_read_exception_status;
    MbusServerDiagnosticsFn on_diagnostics;
    MbusServerGetCommEventCounterFn on_get_comm_event_counter;
    MbusServerGetCommEventLogFn on_get_comm_event_log;
    MbusServerReportServerIdFn on_report_server_id;
    MbusServerReadDeviceIdentificationFn on_read_device_identification;
} MbusServerHandlers;
/**
 * Common server configuration shared by TCP and Serial server types.
 *
 * Only fields that influence the server runtime logic are included here;
 * transport-level details (host address, port, baud rate) are handled
 * separately in the `_new` constructor callbacks.
 */
typedef struct MbusServerConfig {
    /**
     * Slave/unit address this server will respond to.  Valid range: 1–247.
     * For TCP-only deployments the conventional value is 1 or 0xFF.
     */
    uint8_t slave_address;
    /**
     * Maximum time (ms) allocated to process and respond to a single request.
     * Passed to `ResilienceConfig::default()` for now; reserved for future
     * per-request timeout enforcement.
     */
    uint32_t response_timeout_ms;
} MbusServerConfig;
/**
 * A sub-request descriptor for serial file record operations.
 *
 * Identical layout to `MbusDnSubRequest` in `tcp.rs` — shared by both
 * transport variants so C# can use the same struct definition.
 */
typedef struct MbusDnSerialSubRequest {
    /**
     * File number (1–65535).
     */
    uint16_t file_number;
    /**
     * Starting record number within the file (0–9999).
     */
    uint16_t record_number;
    /**
     * Number of 16-bit registers. For reads: how many to read; for writes: must equal `data_len`.
     */
    uint16_t record_length;
    /**
     * Pointer to write data (`null` for reads).
     */
    const uint16_t *data;
    /**
     * Number of valid words pointed to by `data` (0 for reads).
     */
    uint16_t data_len;
} MbusDnSerialSubRequest;
/**
 * A sub-request descriptor used by [`mbus_dn_tcp_client_read_file_record`] and
 * [`mbus_dn_tcp_client_write_file_record`].
 *
 * **Read** sub-requests: set `data` to `null` and `data_len` to `0`; fill
 * `file_number`, `record_number`, and `record_length` with the target record.
 *
 * **Write** sub-requests: set `data` to a pointer to `data_len` `u16` words and
 * ensure `record_length == data_len`.
 */
typedef struct MbusDnSubRequest {
    /**
     * File number (1–65535).
     */
    uint16_t file_number;
    /**
     * Starting record number within the file (0–9999).
     */
    uint16_t record_number;
    /**
     * Number of 16-bit registers. For reads: how many to read; for writes: must equal `data_len`.
     */
    uint16_t record_length;
    /**
     * Pointer to write data (`null` for reads). Valid for at least `data_len` words.
     */
    const uint16_t *data;
    /**
     * Number of valid words pointed to by `data` (0 for reads).
     */
    uint16_t data_len;
} MbusDnSubRequest;
/**
 * Status code returned by every `mbus_go_*` function.
 *
 * Numerically identical to [`crate::c::error::MbusStatusCode`].
 */
typedef enum MbusStatusCode MbusGoStatus;
/**
 * A sub-request descriptor for serial file record operations.
 *
 * Identical layout to `MbusGoSubRequest` in `tcp.rs` — shared by both
 * transport variants so Go can use the same struct definition.
 */
typedef struct MbusGoSerialSubRequest {
    /**
     * File number (1–65535).
     */
    uint16_t file_number;
    /**
     * Starting record number within the file (0–9999).
     */
    uint16_t record_number;
    /**
     * Number of 16-bit registers. For reads: how many to read; for writes: must equal `data_len`.
     */
    uint16_t record_length;
    /**
     * Pointer to write data (`null` for reads).
     */
    const uint16_t *data;
    /**
     * Number of valid words pointed to by `data` (0 for reads).
     */
    uint16_t data_len;
} MbusGoSerialSubRequest;
/**
 * A sub-request descriptor used by [`mbus_go_tcp_client_read_file_record`] and
 * [`mbus_go_tcp_client_write_file_record`].
 *
 * **Read** sub-requests: set `data` to `null` and `data_len` to `0`; fill
 * `file_number`, `record_number`, and `record_length` with the target record.
 *
 * **Write** sub-requests: set `data` to a pointer to `data_len` `u16` words and
 * ensure `record_length == data_len`.
 */
typedef struct MbusGoSubRequest {
    /**
     * File number (1–65535).
     */
    uint16_t file_number;
    /**
     * Starting record number within the file (0–9999).
     */
    uint16_t record_number;
    /**
     * Number of 16-bit registers. For reads: how many to read; for writes: must equal `data_len`.
     */
    uint16_t record_length;
    /**
     * Pointer to write data (`null` for reads). Valid for at least `data_len` words.
     */
    const uint16_t *data;
    /**
     * Number of valid words pointed to by `data` (0 for reads).
     */
    uint16_t data_len;
} MbusGoSubRequest;
/**
 * C-compatible vtable of optional Modbus request handler callbacks.
 *
 * Set any slot to `None` (`null` from Go) to return an `IllegalFunction`
 * exception for that function code.  All function pointers receive `ctx` as
 * their first argument.
 *
 * # Repr
 *
 * The struct uses `#[repr(C)]` so that it has a stable, platform-defined
 * layout.  Pass it by pointer to `mbus_go_tcp_server_new`.
 */
typedef struct MbusGoServerVtable {
    /**
     * Caller-supplied opaque context forwarded unchanged to every callback.
     */
    void *ctx;
    /**
     * `fn(ctx, address, count, out_packed_bytes, out_byte_count) -> i32`
     */
    int32_t (*read_coils)(void*, uint16_t, uint16_t, uint8_t*, uint16_t*);
    /**
     * `fn(ctx, address, value_bool) -> i32`
     */
    int32_t (*write_single_coil)(void*, uint16_t, uint8_t);
    /**
     * `fn(ctx, address, packed_bytes, byte_count, coil_count) -> i32`
     */
    int32_t (*write_multiple_coils)(void*, uint16_t, const uint8_t*, uint16_t, uint16_t);
    /**
     * `fn(ctx, address, count, out_packed_bytes, out_byte_count) -> i32`
     */
    int32_t (*read_discrete_inputs)(void*, uint16_t, uint16_t, uint8_t*, uint16_t*);
    /**
     * `fn(ctx, address, count, out_u16_values, out_count) -> i32`
     */
    int32_t (*read_holding_registers)(void*, uint16_t, uint16_t, uint16_t*, uint16_t*);
    /**
     * `fn(ctx, address, count, out_u16_values, out_count) -> i32`
     */
    int32_t (*read_input_registers)(void*, uint16_t, uint16_t, uint16_t*, uint16_t*);
    /**
     * `fn(ctx, address, value) -> i32`
     */
    int32_t (*write_single_register)(void*, uint16_t, uint16_t);
    /**
     * `fn(ctx, address, values_be_bytes, count) -> i32`
     */
    int32_t (*write_multiple_registers)(void*, uint16_t, const uint8_t*, uint16_t);
    /**
     * `fn(ctx, address, and_mask, or_mask) -> i32`
     */
    int32_t (*mask_write_register)(void*, uint16_t, uint16_t, uint16_t);
    /**
     * `fn(ctx, read_addr, read_count, write_addr, write_values_be_bytes,
     *    write_count, out_u16_values, out_count) -> i32`
     */
    int32_t (*read_write_multiple_registers)(void*,
                                             uint16_t,
                                             uint16_t,
                                             uint16_t,
                                             const uint8_t*,
                                             uint16_t,
                                             uint16_t*,
                                             uint16_t*);
    /**
     * `fn(ctx, pointer_address, out_u16_values, out_count) -> i32`
     */
    int32_t (*read_fifo_queue)(void*, uint16_t, uint16_t*, uint16_t*);
    /**
     * `fn(ctx, out_status_byte) -> i32`
     */
    int32_t (*read_exception_status)(void*, uint8_t*);
    /**
     * `fn(ctx, sub_fn, data, out_sub_fn, out_data) -> i32`
     */
    int32_t (*diagnostics)(void*, uint16_t, uint16_t, uint16_t*, uint16_t*);
    /**
     * `fn(ctx, out_status_word, out_event_count) -> i32`
     */
    int32_t (*get_comm_event_counter)(void*, uint16_t*, uint16_t*);
    /**
     * `fn(ctx, out_payload_bytes, out_byte_count) -> i32`
     *
     * The payload must be formatted as:
     * `[status_hi, status_lo, event_count_hi, event_count_lo,
     *   msg_count_hi, msg_count_lo, event_bytes...]`
     */
    int32_t (*get_comm_event_log)(void*, uint8_t*, uint16_t*);
    /**
     * `fn(ctx, out_payload_bytes, out_byte_count) -> i32`
     */
    int32_t (*report_server_id)(void*, uint8_t*, uint16_t*);
} MbusGoServerVtable;
/**
 * Reads a single coil value by 0-based index into `out_value`.
 *
 * `index` must be less than [`mbus_coils_quantity`]; otherwise returns
/**
 * Reads a single discrete input value by 0-based index into `out_value`.
 *
 * `index` must be less than [`mbus_discrete_inputs_quantity`]; otherwise returns
/**
 * Reads a single register value by 0-based index into `out_value`.
 *
 * `index` must be less than [`mbus_registers_quantity`]; otherwise returns
/**
 * Close the serial port.
 *
 * Pending in-flight requests are failed immediately with `MBUS_ERR_CONNECTION_LOST`.
 * The client ID remains valid; call [`mbus_serial_connect`] to reopen the port.
/**
 * Close the TCP connection.
 *
 * Pending in-flight requests are failed immediately with `MBUS_ERR_CONNECTION_LOST`.
 * The client ID remains valid; call [`mbus_tcp_connect`] to reconnect.
/**
 * Sets a per-request timeout in milliseconds; `0` disables the timeout.
/**
 * Returns `1` when there are requests in flight awaiting a response, `0`
 * otherwise; returns `0` when `handle` is null.
/**
 * Writes a single holding register (FC06).
 *
 * On success, writes the echoed `(address, value)` to `out_address` and
 * `out_value` if those pointers are non-null.
 *
 * # Safety
 *
 * * `handle` must be a valid client pointer.
 * * `out_address` and `out_value` may be null; if non-null they must
/**
 * Reads `quantity` coils (FC01) starting at `address` from `unit_id`.
 *
 * Writes bit-packed coil bytes (Modbus wire format, LSB-first) into `out_buf`.
 * `out_buf_len` is the buffer length in bytes; must be ≥ `ceil(quantity / 8)`.
/**
 * Writes multiple coils (FC15) starting at `address`.
 *
 * `packed_coils` is Modbus bit-packed coil data (LSB-first). `byte_count` is
 * the number of bytes in `packed_coils`; `coil_count` is the number of coils.
/**
 * Starts the gateway on a new background OS thread.
 *
 * Connects all registered downstreams and begins forwarding requests.
 * Returns `MbusOk` immediately; the thread runs until
/**
 * Creates a new RTU serial client.
 *
 * `port` must be a NUL-terminated UTF-8 path string (e.g. `"/dev/ttyUSB0"` on
 * Linux or `"COM3"` on Windows).  `parity` is `0`=None, `1`=Even, `2`=Odd.
 * Returns `null` on any configuration or construction failure.
 *
 * # Safety
 *
 * `port` must point to a valid NUL-terminated string for the duration of the call.
 */
MbusGoSerialClient *mbus_go_serial_client_new_rtu(const char *port,
                                                  uint32_t baud_rate,
                                                  uint8_t data_bits,
                                                  uint8_t parity,
                                                  uint8_t stop_bits,
                                                  uint32_t response_timeout_ms);
/**
 * Creates a new ASCII serial client.
 *
 * See [`mbus_go_serial_client_new_rtu`] for parameter semantics.
 *
 * # Safety
 *
 * `port` must point to a valid NUL-terminated string for the duration of the call.
 */
MbusGoSerialClient *mbus_go_serial_client_new_ascii(const char *port,
                                                    uint32_t baud_rate,
                                                    uint8_t data_bits,
                                                    uint8_t parity,
                                                    uint8_t stop_bits,
                                                    uint32_t response_timeout_ms);
/**
 * Destroys the serial client and releases all associated resources.
 *
 * # Safety
 *
 * `handle` must be a valid pointer originally returned by one of the
 * `mbus_go_serial_client_new_*` constructors.  Calling this function more
 * than once with the same pointer is undefined behaviour.
 */
void mbus_go_serial_client_free(MbusGoSerialClient *handle);
/**
 * Opens the underlying serial port.
 *
 * # Safety
 *
 * `handle` must be a valid client pointer.
 */
MbusGoStatus mbus_go_serial_client_connect(MbusGoSerialClient *handle);
/**
 * Closes the underlying serial port.
 *
 * # Safety
 *
 * `handle` must be a valid client pointer.
 */
MbusGoStatus mbus_go_serial_client_disconnect(MbusGoSerialClient *handle);
/**
 * Sets the per-request timeout in milliseconds (`0` = no timeout).
 *
 * # Safety
 *
 * `handle` must be a valid client pointer.
 */
void mbus_go_serial_client_set_request_timeout_ms(MbusGoSerialClient *handle, uint64_t timeout_ms);
/**
 * Reads `quantity` holding registers (FC03).
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_read_holding_registers(MbusGoSerialClient *handle,
                                                          uint8_t unit_id,
                                                          uint16_t address,
                                                          uint16_t quantity,
                                                          uint16_t *out_buf,
                                                          uint16_t out_buf_len,
                                                          uint16_t *out_count);
/**
 * Writes a single holding register (FC06).
 *
 * # Safety
 *
 * `handle` must be a valid client pointer.
 */
MbusGoStatus mbus_go_serial_client_write_single_register(MbusGoSerialClient *handle,
                                                         uint8_t unit_id,
                                                         uint16_t address,
                                                         uint16_t value,
                                                         uint16_t *out_address,
                                                         uint16_t *out_value);
/**
 * Writes multiple holding registers (FC16).
 *
 * `values` is a slice of `quantity` big-endian register words.
 *
 * # Safety
 *
 * `handle` and `values` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_write_multiple_registers(MbusGoSerialClient *handle,
                                                            uint8_t unit_id,
                                                            uint16_t address,
                                                            const uint16_t *values,
                                                            uint16_t quantity,
                                                            uint16_t *out_address,
                                                            uint16_t *out_quantity);
/**
 * Reads `quantity` input registers (FC04).
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_read_input_registers(MbusGoSerialClient *handle,
                                                        uint8_t unit_id,
                                                        uint16_t address,
                                                        uint16_t quantity,
                                                        uint16_t *out_buf,
                                                        uint16_t out_buf_len,
                                                        uint16_t *out_count);
/**
 * Applies an AND/OR bitmask to a holding register (FC22).
 *
 * # Safety
 *
 * `handle` must be a valid client pointer.
 */
MbusGoStatus mbus_go_serial_client_mask_write_register(MbusGoSerialClient *handle,
                                                       uint8_t unit_id,
                                                       uint16_t address,
                                                       uint16_t and_mask,
                                                       uint16_t or_mask);
/**
 * Reads and simultaneously writes multiple holding registers (FC23).
 *
 * # Safety
 *
 * `handle`, `write_values`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_read_write_multiple_registers(MbusGoSerialClient *handle,
                                                                 uint8_t unit_id,
                                                                 uint16_t read_address,
                                                                 uint16_t read_quantity,
                                                                 uint16_t write_address,
                                                                 const uint16_t *write_values,
                                                                 uint16_t write_quantity,
                                                                 uint16_t *out_buf,
                                                                 uint16_t out_buf_len,
                                                                 uint16_t *out_count);
/**
 * Reads `quantity` coils (FC01).
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_read_coils(MbusGoSerialClient *handle,
                                              uint8_t unit_id,
                                              uint16_t address,
                                              uint16_t quantity,
                                              uint8_t *out_buf,
                                              uint16_t out_buf_len,
                                              uint16_t *out_count);
/**
 * Writes a single coil (FC05).
 *
 * # Safety
 *
 * `handle` must be a valid client pointer.
 */
MbusGoStatus mbus_go_serial_client_write_single_coil(MbusGoSerialClient *handle,
                                                     uint8_t unit_id,
                                                     uint16_t address,
                                                     uint8_t value,
                                                     uint16_t *out_address,
                                                     uint8_t *out_value);
/**
 * Writes multiple coils (FC15).
 *
 * # Safety
 *
 * `handle` and `packed_coils` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_write_multiple_coils(MbusGoSerialClient *handle,
                                                        uint8_t unit_id,
                                                        uint16_t address,
                                                        const uint8_t *packed_coils,
                                                        uint16_t byte_count,
                                                        uint16_t coil_count,
                                                        uint16_t *out_address,
                                                        uint16_t *out_quantity);
/**
 * Reads `quantity` discrete inputs (FC02).
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_read_discrete_inputs(MbusGoSerialClient *handle,
                                                        uint8_t unit_id,
                                                        uint16_t address,
                                                        uint16_t quantity,
                                                        uint8_t *out_buf,
                                                        uint16_t out_buf_len,
                                                        uint16_t *out_count);
/**
 * Reads the FIFO queue (FC24).
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_read_fifo_queue(MbusGoSerialClient *handle,
                                                   uint8_t unit_id,
                                                   uint16_t address,
                                                   uint16_t *out_buf,
                                                   uint16_t out_buf_len,
                                                   uint16_t *out_count);
/**
 * Reads the device exception status (FC07).
 *
 * # Safety
 *
 * `handle` and `out_status` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_read_exception_status(MbusGoSerialClient *handle,
                                                         uint8_t unit_id,
                                                         uint8_t *out_status);
/**
 * Reads the communication event counter (FC11).
 *
 * # Safety
 *
 * `handle`, `out_status`, and `out_event_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_get_comm_event_counter(MbusGoSerialClient *handle,
                                                          uint8_t unit_id,
                                                          uint16_t *out_status,
                                                          uint16_t *out_event_count);
/**
 * Reads the communication event log (FC12).
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_get_comm_event_log(MbusGoSerialClient *handle,
                                                      uint8_t unit_id,
                                                      uint8_t *out_buf,
                                                      uint16_t out_buf_len,
                                                      uint16_t *out_count);
/**
 * Reports the server identifier (FC17).
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_report_server_id(MbusGoSerialClient *handle,
                                                    uint8_t unit_id,
                                                    uint8_t *out_buf,
                                                    uint16_t out_buf_len,
                                                    uint16_t *out_count);
/**
 * Sends a Diagnostics (FC08) request.
 *
 * # Safety
 *
 * `handle`, `out_sub_function`, `out_buf`, and `out_count` must be valid non-null
 * pointers. If `data_in_count > 0`, `data_in` must point to at least `data_in_count`
 * valid `u16` words.
 */
MbusGoStatus mbus_go_serial_client_diagnostics(MbusGoSerialClient *handle,
                                               uint8_t unit_id,
                                               uint16_t sub_function,
                                               const uint16_t *data_in,
                                               uint16_t data_in_count,
                                               uint16_t *out_sub_function,
                                               uint16_t *out_buf,
                                               uint16_t out_buf_len,
                                               uint16_t *out_count);
/**
 * Reads one or more file records (FC14) over a serial connection.
 *
 * # Safety
 *
 * `handle`, `sub_reqs`, `out_buf`, and `out_count` must be valid non-null pointers.
 * `sub_reqs` must be valid for `sub_req_count` items.
 */
MbusGoStatus mbus_go_serial_client_read_file_record(MbusGoSerialClient *handle,
                                                    uint8_t unit_id,
                                                    const struct MbusGoSerialSubRequest *sub_reqs,
                                                    uint16_t sub_req_count,
                                                    uint16_t *out_buf,
                                                    uint16_t out_buf_len,
                                                    uint16_t *out_count);
/**
 * Writes one or more file records (FC15) over a serial connection.
 *
 * # Safety
 *
 * `handle` and `sub_reqs` must be valid non-null pointers. `sub_reqs` must be valid
 * for `sub_req_count` items. For each item, `data` must be valid for `data_len` words.
 */
MbusGoStatus mbus_go_serial_client_write_file_record(MbusGoSerialClient *handle,
                                                     uint8_t unit_id,
                                                     const struct MbusGoSerialSubRequest *sub_reqs,
                                                     uint16_t sub_req_count);
/**
 * Creates a new async TCP client targeting `host:port`.
 *
 * `host` must be a NUL-terminated UTF-8 string.  The returned pointer
 * must eventually be released with [`mbus_go_tcp_client_free`].  Returns
 * `null` if `host` is null, not valid UTF-8, or the underlying constructor
 * fails (for example because no Tokio runtime could be started).
 *
 * # Safety
 *
 * `host` must point to a valid NUL-terminated string for the duration of
 * this call.
 */
MbusGoTcpClient *mbus_go_tcp_client_new(const char *host, uint16_t port);
/**
 * Releases an `MbusGoTcpClient` previously returned from
 * [`mbus_go_tcp_client_new`].
 *
 * Drops the underlying `AsyncTcpClient`, which signals its background
 * Tokio task to exit.  No-op if `handle` is null.  Safe to call exactly
 * once per handle.
 *
 * # Safety
 *
 * `handle` must be either null or a pointer previously returned from
 * [`mbus_go_tcp_client_new`] that has not already been freed.
 */
void mbus_go_tcp_client_free(MbusGoTcpClient *handle);
/**
 * Establishes the TCP transport connection.
 *
 * Blocks the calling thread until the connection completes or fails.
 *
 * # Safety
 *
 * `handle` must be a non-null pointer previously returned from
 * [`mbus_go_tcp_client_new`] and still alive.
 */
MbusGoStatus mbus_go_tcp_client_connect(MbusGoTcpClient *handle);
/**
 * Closes the TCP transport gracefully.
 *
 * Drains any in-flight or queued requests with `ConnectionClosed`.  After
 * this call the client can be reconnected with
 * [`mbus_go_tcp_client_connect`].
 *
 * # Safety
 *
 * See [`mbus_go_tcp_client_connect`].
 */
MbusGoStatus mbus_go_tcp_client_disconnect(MbusGoTcpClient *handle);
/**
 * Sets a per-request timeout in milliseconds; `0` disables the timeout.
 *
 * # Safety
 *
 * See [`mbus_go_tcp_client_connect`].
 */
MbusGoStatus mbus_go_tcp_client_set_request_timeout_ms(MbusGoTcpClient *handle,
                                                       uint64_t timeout_ms);
/**
 * Returns `1` when there are requests in flight awaiting a response, `0`
 * otherwise; returns `0` when `handle` is null.
 *
 * # Safety
 *
 * See [`mbus_go_tcp_client_connect`].
 */
uint8_t mbus_go_tcp_client_has_pending_requests(MbusGoTcpClient *handle);
/**
 * Reads `quantity` holding registers (FC03) starting at `address` from
 * the given `unit_id` and copies them, in declaration order, into the
 * caller-supplied `out_buf` of length `out_buf_len` (in `u16` elements).
 *
 * On success writes the number of registers actually read into
 * `out_count` (which equals `quantity`) and returns `MbusOk`.
 *
 * Returns `MbusErrBufferTooSmall` if `out_buf_len < quantity`.
 *
 * # Safety
 *
 * * `handle` must be a valid client pointer.
 * * `out_buf` must point to writable storage for at least `out_buf_len`
 *   `u16` values.
 * * `out_count` must point to a writable `u16`.
 */
MbusGoStatus mbus_go_tcp_client_read_holding_registers(MbusGoTcpClient *handle,
                                                       uint8_t unit_id,
                                                       uint16_t address,
                                                       uint16_t quantity,
                                                       uint16_t *out_buf,
                                                       uint16_t out_buf_len,
                                                       uint16_t *out_count);
/**
 * Writes a single holding register (FC06).
 *
 * On success, writes the echoed `(address, value)` to `out_address` and
 * `out_value` if those pointers are non-null.
 *
 * # Safety
 *
 * * `handle` must be a valid client pointer.
 * * `out_address` and `out_value` may be null; if non-null they must
 *   point to writable `u16` storage.
 */
MbusGoStatus mbus_go_tcp_client_write_single_register(MbusGoTcpClient *handle,
                                                      uint8_t unit_id,
                                                      uint16_t address,
                                                      uint16_t value,
                                                      uint16_t *out_address,
                                                      uint16_t *out_value);
/**
 * Writes `quantity` holding registers (FC16) starting at `address`.
 *
 * `values` must point to `quantity` `u16` values in declaration order.
 *
 * On success, writes the echoed `(starting_address, quantity)` to
 * `out_address` and `out_quantity` if non-null.
 *
 * # Safety
 *
 * * `handle` must be a valid client pointer.
 * * `values` must point to at least `quantity` readable `u16` values.
 * * `out_address` and `out_quantity` may be null.
 */
MbusGoStatus mbus_go_tcp_client_write_multiple_registers(MbusGoTcpClient *handle,
                                                         uint8_t unit_id,
                                                         uint16_t address,
                                                         const uint16_t *values,
                                                         uint16_t quantity,
                                                         uint16_t *out_address,
                                                         uint16_t *out_quantity);
/**
 * Reads `quantity` coils (FC01) starting at `address` from `unit_id`.
 *
 * Writes bit-packed coil bytes (Modbus wire format, LSB-first) into `out_buf`.
 * `out_buf_len` is the buffer length in bytes; must be ≥ `ceil(quantity / 8)`.
 * On success writes the byte count to `out_count`.
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_read_coils(MbusGoTcpClient *handle,
                                           uint8_t unit_id,
                                           uint16_t address,
                                           uint16_t quantity,
                                           uint8_t *out_buf,
                                           uint16_t out_buf_len,
                                           uint16_t *out_count);
/**
 * Writes a single coil (FC05). `value != 0` means ON.
 *
 * On success, writes echoed address to `out_address` and value (`1`=ON, `0`=OFF)
 * to `out_value` if those pointers are non-null.
 *
 * # Safety
 *
 * `handle` must be a valid client pointer.
 */
MbusGoStatus mbus_go_tcp_client_write_single_coil(MbusGoTcpClient *handle,
                                                  uint8_t unit_id,
                                                  uint16_t address,
                                                  uint8_t value,
                                                  uint16_t *out_address,
                                                  uint8_t *out_value);
/**
 * Writes multiple coils (FC15) starting at `address`.
 *
 * `packed_coils` is Modbus bit-packed coil data (LSB-first). `byte_count` is
 * the number of bytes in `packed_coils`; `coil_count` is the number of coils.
 *
 * # Safety
 *
 * `handle` and `packed_coils` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_write_multiple_coils(MbusGoTcpClient *handle,
                                                     uint8_t unit_id,
                                                     uint16_t address,
                                                     const uint8_t *packed_coils,
                                                     uint16_t byte_count,
                                                     uint16_t coil_count,
                                                     uint16_t *out_address,
                                                     uint16_t *out_quantity);
/**
 * Reads `quantity` discrete inputs (FC02) starting at `address` from `unit_id`.
 *
 * Writes bit-packed bytes into `out_buf`. On success writes byte count to `out_count`.
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_read_discrete_inputs(MbusGoTcpClient *handle,
                                                     uint8_t unit_id,
                                                     uint16_t address,
                                                     uint16_t quantity,
                                                     uint8_t *out_buf,
                                                     uint16_t out_buf_len,
                                                     uint16_t *out_count);
/**
 * Reads `quantity` input registers (FC04) starting at `address` from `unit_id`.
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_read_input_registers(MbusGoTcpClient *handle,
                                                     uint8_t unit_id,
                                                     uint16_t address,
                                                     uint16_t quantity,
                                                     uint16_t *out_buf,
                                                     uint16_t out_buf_len,
                                                     uint16_t *out_count);
/**
 * Applies an AND/OR bitmask to a holding register (FC22).
 *
 * # Safety
 *
 * `handle` must be a valid client pointer.
 */
MbusGoStatus mbus_go_tcp_client_mask_write_register(MbusGoTcpClient *handle,
                                                    uint8_t unit_id,
                                                    uint16_t address,
                                                    uint16_t and_mask,
                                                    uint16_t or_mask);
/**
 * Reads and simultaneously writes multiple holding registers (FC23).
 *
 * # Safety
 *
 * `handle`, `write_values`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_read_write_multiple_registers(MbusGoTcpClient *handle,
                                                              uint8_t unit_id,
                                                              uint16_t read_address,
                                                              uint16_t read_quantity,
                                                              uint16_t write_address,
                                                              const uint16_t *write_values,
                                                              uint16_t write_quantity,
                                                              uint16_t *out_buf,
                                                              uint16_t out_buf_len,
                                                              uint16_t *out_count);
/**
 * Reads the FIFO queue (FC24) at `address` from `unit_id`.
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_read_fifo_queue(MbusGoTcpClient *handle,
                                                uint8_t unit_id,
                                                uint16_t address,
                                                uint16_t *out_buf,
                                                uint16_t out_buf_len,
                                                uint16_t *out_count);
/**
 * Reads the device exception status (FC07).
 *
 * # Safety
 *
 * `handle` and `out_status` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_read_exception_status(MbusGoTcpClient *handle,
                                                      uint8_t unit_id,
                                                      uint8_t *out_status);
/**
 * Reads the communication event counter (FC11).
 *
 * On success writes `status_word` and `event_count` to the respective out pointers.
 *
 * # Safety
 *
 * `handle`, `out_status`, and `out_event_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_get_comm_event_counter(MbusGoTcpClient *handle,
                                                       uint8_t unit_id,
                                                       uint16_t *out_status,
                                                       uint16_t *out_event_count);
/**
 * Reads the communication event log (FC12).
 *
 * Writes the raw event bytes into `out_buf`. On success writes byte count to `out_count`.
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_get_comm_event_log(MbusGoTcpClient *handle,
                                                   uint8_t unit_id,
                                                   uint8_t *out_buf,
                                                   uint16_t out_buf_len,
                                                   uint16_t *out_count);
/**
 * Reports the server identifier (FC17).
 *
 * Writes the raw server ID bytes into `out_buf`. On success writes byte count to `out_count`.
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_report_server_id(MbusGoTcpClient *handle,
                                                 uint8_t unit_id,
                                                 uint8_t *out_buf,
                                                 uint16_t out_buf_len,
                                                 uint16_t *out_count);
/**
 * Sends a Diagnostics (FC08) request.
 *
 * `sub_function` is the 16-bit sub-function code (see Modbus spec table).
 * `data_in` / `data_in_count` form the optional request data words (`null` / `0` for
 * sub-functions that carry no data such as *Return Query Data* with zero words).
 *
 * On success writes the echoed sub-function code to `out_sub_function` and the
 * echoed data words into `out_buf`, then sets `out_count` to the number of words written.
 *
 * # Safety
 *
 * `handle`, `out_sub_function`, `out_buf`, and `out_count` must be valid non-null pointers.
 * If `data_in_count > 0`, `data_in` must point to at least `data_in_count` valid `u16` words.
 */
MbusGoStatus mbus_go_tcp_client_diagnostics(MbusGoTcpClient *handle,
                                            uint8_t unit_id,
                                            uint16_t sub_function,
                                            const uint16_t *data_in,
                                            uint16_t data_in_count,
                                            uint16_t *out_sub_function,
                                            uint16_t *out_buf,
                                            uint16_t out_buf_len,
                                            uint16_t *out_count);
/**
 * Reads one or more file records (FC14).
 *
 * `sub_reqs` must point to `sub_req_count` [`MbusGoSubRequest`] descriptors in read mode
 * (i.e. each `data` field is `null` and `data_len` is `0`).
 *
 * On success the register words for all sub-requests are written contiguously into
 * `out_buf` (in the order of the sub-requests), and `out_count` is set to the total
 * number of words written.  The caller is expected to know the `record_length` of each
 * sub-request so it can split the flat buffer into per-record slices.
 *
 * # Safety
 *
 * `handle`, `sub_reqs`, `out_buf`, and `out_count` must be valid non-null pointers.
 * `sub_reqs` must be valid for `sub_req_count` items.
 */
MbusGoStatus mbus_go_tcp_client_read_file_record(MbusGoTcpClient *handle,
                                                 uint8_t unit_id,
                                                 const struct MbusGoSubRequest *sub_reqs,
                                                 uint16_t sub_req_count,
                                                 uint16_t *out_buf,
                                                 uint16_t out_buf_len,
                                                 uint16_t *out_count);
/**
 * Writes one or more file records (FC15).
 *
 * `sub_reqs` must point to `sub_req_count` [`MbusGoSubRequest`] descriptors in write mode
 * (i.e. each `data` field points to `data_len` valid `u16` words, and `record_length == data_len`).
 *
 * Returns `MbusOk` when all records have been written successfully.
 *
 * # Safety
 *
 * `handle` and `sub_reqs` must be valid non-null pointers.  `sub_reqs` must be valid for
 * `sub_req_count` items.  For each item, `data` must be valid for `data_len` words.
 */
MbusGoStatus mbus_go_tcp_client_write_file_record(MbusGoTcpClient *handle,
                                                  uint8_t unit_id,
                                                  const struct MbusGoSubRequest *sub_reqs,
                                                  uint16_t sub_req_count);
uintptr_t mbus_go_tcp_client_handle_size(void);
/**
 * Creates a new gateway handle.
 *
 * `host` is the NUL-terminated upstream bind address (e.g. `"0.0.0.0"`).
 * Returns `null` if `host` is null or not valid UTF-8.
 *
 * # Safety
 *
 * `host` must point to a valid NUL-terminated string.
 */
MbusGoTcpGateway *mbus_go_tcp_gateway_new(const char *host, uint16_t port);
/**
 * Destroys the gateway handle.
 *
 * Call [`mbus_go_tcp_gateway_stop`] first if the gateway is running.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`mbus_go_tcp_gateway_new`].
 */
void mbus_go_tcp_gateway_free(MbusGoTcpGateway *handle);
/**
 * Adds a TCP downstream and returns its zero-based channel index.
 *
 * Returns `u32::MAX` if `host` is null.
 *
 * # Safety
 *
 * `handle` and `host` must be valid non-null pointers.
 */
uint32_t mbus_go_tcp_gateway_add_downstream(MbusGoTcpGateway *handle,
                                            const char *host,
                                            uint16_t port);
/**
 * Routes a single unit ID to a downstream channel.
 *
 * Returns `MbusOk` on success, `MbusErrInvalidAddress` if `unit_id == 0` or
 * `channel >= registered_downstream_count`.
 *
 * # Safety
 *
 * `handle` must be a valid gateway pointer.
 */
MbusGoStatus mbus_go_tcp_gateway_add_unit_route(MbusGoTcpGateway *handle,
                                                uint8_t unit_id,
                                                uint32_t channel);
/**
 * Routes an inclusive unit-ID range `[min, max]` to a downstream channel.
 *
 * Returns `MbusErrInvalidAddress` if `min == 0`, `min > max`, or
 * `channel >= registered_downstream_count`.
 *
 * # Safety
 *
 * `handle` must be a valid gateway pointer.
 */
MbusGoStatus mbus_go_tcp_gateway_add_range_route(MbusGoTcpGateway *handle,
                                                 uint8_t unit_min,
                                                 uint8_t unit_max,
                                                 uint32_t channel);
/**
 * Starts the gateway on a new background OS thread.
 *
 * Connects all registered downstreams and begins forwarding requests.
 * Returns `MbusOk` immediately; the thread runs until
 * [`mbus_go_tcp_gateway_stop`] is called.
 *
 * Returns `MbusErrInvalidAddress` if no downstreams or no routes have been
 * registered.
 *
 * # Safety
 *
 * `handle` must be a valid gateway pointer.
 */
MbusGoStatus mbus_go_tcp_gateway_start(MbusGoTcpGateway *handle);
/**
 * Signals the running gateway to stop.
 *
 * # Safety
 *
 * `handle` must be a valid gateway pointer.
 */
void mbus_go_tcp_gateway_stop(MbusGoTcpGateway *handle);
/**
 * Creates a new TCP server handle.
 *
 * `host` is a NUL-terminated bind address (e.g. `"0.0.0.0"`).
 * `unit_id` is the Modbus unit ID to respond to.
 * `vtable` must remain valid for the lifetime of the server handle.
 *
 * Returns `null` if `host` or `vtable` is null, or if `unit_id` is invalid.
 *
 * # Safety
 *
 * * `host` must point to a valid NUL-terminated UTF-8 string.
 * * `vtable` must be non-null and the struct it points to must remain valid
 *   until [`mbus_go_tcp_server_free`] is called.
 */
MbusGoTcpServer *mbus_go_tcp_server_new(const char *host,
                                        uint16_t port,
                                        uint8_t unit_id,
                                        const struct MbusGoServerVtable *vtable);
/**
 * Destroys the server handle.
 *
 * Does **not** stop a running server — call [`mbus_go_tcp_server_stop`]
 * first, wait for the background thread to exit, then call this.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`mbus_go_tcp_server_new`].
 * Calling this more than once is undefined behaviour.
 */
void mbus_go_tcp_server_free(MbusGoTcpServer *handle);
/**
 * Starts the server on a new background OS thread.
 *
 * The thread blocks on `serve_with_shutdown` until [`mbus_go_tcp_server_stop`]
 * is called or a fatal error occurs.  Returns immediately to the caller.
 *
 * # Safety
 *
 * `handle` must be a valid server pointer.
 */
MbusGoStatus mbus_go_tcp_server_start(MbusGoTcpServer *handle);
/**
 * Signals the running server to stop.
 *
 * The background thread will finish in-flight sessions and then exit.
 *
 * # Safety
 *
 * `handle` must be a valid server pointer.
 */
void mbus_go_tcp_server_stop(MbusGoTcpServer *handle);
/**
 * Returns a static C string describing `status`.
 *
 * Equivalent to [`crate::c::error::mbus_status_str`] but exported with a
 * `mbus_go_` prefix so that it appears in the Go-only header.
 *
 * The returned pointer is always valid (points to a static string literal).
 * The caller must NOT free it.
 */
const char *mbus_go_status_str(MbusGoStatus status);
#endif  /* MODBUS_RS_GO_H */
