#ifndef MODBUS_RS_GO_H
#define MODBUS_RS_GO_H

#pragma once

/* Auto-generated by cbindgen — DO NOT EDIT.
   Regenerate with: cargo build -p mbus-ffi --features go,full */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
typedef struct MbusGoTcpClient MbusGoTcpClient;
typedef struct MbusGoSerialClient MbusGoSerialClient;
typedef struct MbusGoTcpServer MbusGoTcpServer;
typedef struct MbusGoTcpGateway MbusGoTcpGateway;

/* Forward declarations for sibling-binding types that cbindgen leaks
   into this header even though their cfgs are disabled.  They are not
   reachable from the Go ABI; the typedefs make the header
   self-consistent so cgo can compile it cleanly. */
typedef struct MbusCoils MbusCoils;
typedef struct MbusDiscreteInputs MbusDiscreteInputs;
typedef struct MbusFifoQueue MbusFifoQueue;
typedef struct MbusRegisters MbusRegisters;
typedef uint16_t MbusClientId;
typedef uint16_t MbusServerId;
typedef uint16_t MbusGatewayId;

/* Go server vtable - manually defined because cbindgen doesn't handle conditional fields correctly */
typedef struct MbusGoServerVtable {
    void *ctx;
    int32_t (*read_coils)(void*, uint16_t, uint16_t, uint8_t*, uint16_t*);
    int32_t (*write_single_coil)(void*, uint16_t, uint8_t);
    int32_t (*write_multiple_coils)(void*, uint16_t, const uint8_t*, uint16_t, uint16_t);
    int32_t (*read_discrete_inputs)(void*, uint16_t, uint16_t, uint8_t*, uint16_t*);
    int32_t (*read_holding_registers)(void*, uint16_t, uint16_t, uint16_t*, uint16_t*);
    int32_t (*read_input_registers)(void*, uint16_t, uint16_t, uint16_t*, uint16_t*);
    int32_t (*write_single_register)(void*, uint16_t, uint16_t);
    int32_t (*write_multiple_registers)(void*, uint16_t, const uint8_t*, uint16_t);
    int32_t (*mask_write_register)(void*, uint16_t, uint16_t, uint16_t);
    int32_t (*read_write_multiple_registers)(void*, uint16_t, uint16_t, uint16_t, const uint16_t*, uint16_t*);
    int32_t (*read_fifo_queue)(void*, uint16_t, uint16_t*, uint16_t*);
    int32_t (*read_file_record)(void*, uint16_t, uint16_t, uint16_t, uint16_t*, uint16_t*);
    int32_t (*write_file_record)(void*, uint16_t, uint16_t, uint16_t, const uint16_t*);
    int32_t (*read_exception_status)(void*, uint8_t*);
    int32_t (*diagnostics)(void*, uint16_t, uint16_t, uint16_t*, uint16_t*);
    int32_t (*get_comm_event_counter)(void*, uint16_t*, uint16_t*);
    int32_t (*get_comm_event_log)(void*, uint8_t*, uint16_t*);
    int32_t (*report_server_id)(void*, uint8_t*, uint16_t*);
} MbusGoServerVtable;


/**
 * C-compatible status code returned by every `mbus_*` function.
 *
 * `MBUS_OK` (0) means the request was successfully queued. Actual response data
 * is delivered later via the callbacks in `MbusCallbacks`.
 */
typedef enum MbusStatusCode {
    /**
     * Success.
     */
    MbusOk = 0,
    /**
     * Frame parse error.
     */
    MbusErrParseError,
    /**
     * Basic parse error.
     */
    MbusErrBasicParseError,
    /**
     * Response timeout.
     */
    MbusErrTimeout,
    /**
     * Modbus exception response.
     */
    MbusErrModbusException,
    /**
     * I/O error.
     */
    MbusErrIoError,
    /**
     * Unexpected error.
     */
    MbusErrUnexpected,
    /**
     * Connection lost.
     */
    MbusErrConnectionLost,
    /**
     * Unsupported function.
     */
    MbusErrUnsupportedFunction,
    /**
     * Reserved sub-function.
     */
    MbusErrReservedSubFunction,
    /**
     * Invalid PDU length.
     */
    MbusErrInvalidPduLength,
    /**
     * Invalid ADU length.
     */
    MbusErrInvalidAduLength,
    /**
     * Connection failed.
     */
    MbusErrConnectionFailed,
    /**
     * Connection closed.
     */
    MbusErrConnectionClosed,
    /**
     * Buffer too small.
     */
    MbusErrBufferTooSmall,
    /**
     * Buffer length mismatch.
     */
    MbusErrBufferLenMismatch,
    /**
     * Send failed.
     */
    MbusErrSendFailed,
    /**
     * Invalid address.
     */
    MbusErrInvalidAddress,
    /**
     * Invalid offset.
     */
    MbusErrInvalidOffset,
    /**
     * Too many in-flight requests.
     */
    MbusErrTooManyRequests,
    /**
     * Invalid function code.
     */
    MbusErrInvalidFunctionCode,
    /**
     * No retries left.
     */
    MbusErrNoRetriesLeft,
    /**
     * Too many file read sub-requests.
     */
    MbusErrTooManyFileReadSubRequests,
    /**
     * File read PDU overflow.
     */
    MbusErrFileReadPduOverflow,
    /**
     * Unexpected response.
     */
    MbusErrUnexpectedResponse,
    /**
     * Invalid transport.
     */
    MbusErrInvalidTransport,
    /**
     * Invalid slave address.
     */
    MbusErrInvalidSlaveAddress,
    /**
     * Checksum error.
     */
    MbusErrChecksumError,
    /**
     * Invalid configuration.
     */
    MbusErrInvalidConfiguration,
    /**
     * Invalid number of expected responses.
     */
    MbusErrInvalidNumOfExpectedRsps,
    /**
     * Invalid data length.
     */
    MbusErrInvalidDataLen,
    /**
     * Invalid quantity.
     */
    MbusErrInvalidQuantity,
    /**
     * Invalid value.
     */
    MbusErrInvalidValue,
    /**
     * Invalid AND mask.
     */
    MbusErrInvalidAndMask,
    /**
     * Invalid OR mask.
     */
    MbusErrInvalidOrMask,
    /**
     * Invalid byte count.
     */
    MbusErrInvalidByteCount,
    /**
     * Invalid device identification.
     */
    MbusErrInvalidDeviceIdentification,
    /**
     * Invalid device ID code.
     */
    MbusErrInvalidDeviceIdCode,
    /**
     * Invalid MEI type.
     */
    MbusErrInvalidMeiType,
    /**
     * Invalid broadcast address.
     */
    MbusErrInvalidBroadcastAddress,
    /**
     * Broadcast not allowed.
     */
    MbusErrBroadcastNotAllowed,
    /**
     * Framing error (protocol timing violation).
     */
    MbusErrFramingError,
    /**
     * Null pointer passed.
     */
    MbusErrNullPointer,
    /**
     * Invalid UTF-8 string.
     */
    MbusErrInvalidUtf8,
    /**
     * Invalid client ID (freed or never allocated).
     */
    MbusErrInvalidClientId,
    /**
     * Client pool is full — no free slots.
     */
    MbusErrPoolFull,
    /**
     * Client type mismatch (e.g. TCP call on serial ID).
     */
    MbusErrClientTypeMismatch,
    /**
     * Client is busy (indicates an illegal re-entrant call from a callback).
     */
    MbusErrBusy,
} MbusStatusCode;

/**
 * Serial framing mode.
 */
typedef enum MbusSerialMode {
    /**
     * Modbus RTU binary framing with CRC-16.
     */
    MbusSerialRtu = 0,
    /**
     * Modbus ASCII framing with LRC.
     */
    MbusSerialAscii,
} MbusSerialMode;

/**
 * Backoff strategy selector for retry logic.
 */
typedef enum MbusBackoffStrategy {
    /**
     * Retry immediately with no delay.
     */
    MbusBackoffImmediate = 0,
    /**
     * Retry after a fixed delay (`backoff_base_delay_ms`).
     */
    MbusBackoffFixed,
    /**
     * Retry with exponentially increasing delay, capped at `backoff_max_delay_ms`.
     */
    MbusBackoffExponential,
    /**
     * Retry with linearly increasing delay, capped at `backoff_max_delay_ms`.
     */
    MbusBackoffLinear,
} MbusBackoffStrategy;

/**
 * Exception code returned by every C server callback.
 *
 * Maps 1-to-1 with the Modbus standard exception codes:
 *
 * | Value | Name | When to return |
 * |-------|------|----------------|
 * | `0` | `Ok` | Request handled successfully. The server sends a normal response. |
 * | `1` | `IllegalFunction` | This function code is not supported by your server implementation. |
 * | `2` | `IllegalDataAddress` | The requested `address` or `quantity` is outside the server's valid range. |
 * | `3` | `IllegalDataValue` | A value in the request data field is not acceptable (e.g. out-of-range register value). |
 * | `4` | `ServerDeviceFailure` | An unrecoverable error occurred while processing the request (hardware fault, internal error). |
 *
 * # Notes
 * - `Ok = 0` is a **non-standard sentinel** used only by this C API.  It is
 *   never sent on the wire; the server translates it to a normal success response.
 * - For **write** function codes (FC05, FC06, FC0F, FC10, FC15, FC16, FC17),
 *   `Ok` means the write was accepted and committed.  The server echoes the
 *   request back to the master as specified by the Modbus protocol.
 * - For **read** function codes (FC01–FC04, FC07, FC0B, FC0C, FC11, FC14, FC17,
 *   FC18, FC2B), `Ok` means the `out_*` fields have been populated with valid
 *   response data.
 * - If you detect a timing violation in application logic (e.g. a sensor timed
 *   out), return `ServerDeviceFailure`; do **not** return `FramingError` — that
 *   is a transport-level status only returned by the `recv` callback.
 */
typedef enum MbusServerExceptionCode {
    /**
     * No exception — the callback handled the request successfully.
     */
    Ok = 0,
    /**
     * FC is not supported / not implemented by this server.
     */
    IllegalFunction = 1,
    /**
     * Address or offset is outside the server's valid range.
     */
    IllegalDataAddress = 2,
    /**
     * A data value in the request is not acceptable.
     */
    IllegalDataValue = 3,
    /**
     * The server could not complete the request due to an internal failure.
     */
    ServerDeviceFailure = 4,
} MbusServerExceptionCode;

/**
 * Configuration for a Modbus Serial (RTU or ASCII) client.
 *
 * `port_name` must remain valid for the duration of `mbus_serial_client_new`.
 */
typedef struct MbusSerialConfig {
    /**
     * Null-terminated serial port path (e.g. `"/dev/ttyUSB0"` or `"COM3"`).
     */
    const char *port_name;
    /**
     * Framing mode: RTU or ASCII.
     */
    enum MbusSerialMode mode;
    /**
     * Backoff strategy between retries.
     */
    enum MbusBackoffStrategy backoff_strategy;
} MbusSerialConfig;

/**
 * C-provided transport callbacks — the only interface between C code and the Rust Modbus stack.
 *
 * Fill in this struct and pass it to a `mbus_*_new` constructor.  The Rust stack
 * calls these function pointers whenever it needs to open, close, send data, or
 * receive data over the underlying physical medium (TCP socket, UART, etc.).
 *
 * # Requirements
 *
 * - **All five callbacks must be non-`NULL`.**  `validate_transport_callbacks` checks
 *   this; constructors reject a struct with any `NULL` slot.
 * - Every callback receives the same `userdata` pointer that is stored in this struct.
 *   Use it to pass your driver state (file descriptor, hardware register base, etc.).
 * - Callbacks may be called from any context that calls `mbus_*_poll`, `mbus_*_connect`,
 *   or `mbus_*_send`.  If you use locking in your driver, acquire and release the lock
 *   inside the callback — do **not** hold an external lock while polling.
 * - Callbacks must **never** call back into the Modbus stack (no `mbus_*` functions
 *   from inside a callback) — doing so causes re-entrant undefined behaviour.
 *
 * # Lifetime
 *
 * The struct (and everything `userdata` points to) must remain valid until
 * `mbus_*_free` is called on every server or client that uses it.
 *
 * # Minimal example (C, TCP)
 *
 * ```c
 * static MbusStatusCode my_connect(void *ud) {
 *     MyCtx *ctx = (MyCtx *)ud;
 *     ctx->fd = socket_open(ctx->host, ctx->port);
 *     return ctx->fd >= 0 ? MBUS_OK : MBUS_ERR_CONNECTION_FAILED;
 * }
 * static MbusStatusCode my_disconnect(void *ud) {
 *     socket_close(((MyCtx *)ud)->fd);
 *     return MBUS_OK;
 * }
 * static MbusStatusCode my_send(const uint8_t *data, uint16_t len, void *ud) {
 *     return socket_write(((MyCtx *)ud)->fd, data, len) == len
 *         ? MBUS_OK : MBUS_ERR_SEND_FAILED;
 * }
 * static MbusStatusCode my_recv(uint8_t *buf, uint16_t cap,
 *                               uint16_t *out_len, void *ud) {
 *     int n = socket_read_nonblocking(((MyCtx *)ud)->fd, buf, cap);
 *     if (n > 0) { *out_len = (uint16_t)n; return MBUS_OK; }
 *     return n == 0 ? MBUS_ERR_TIMEOUT : MBUS_ERR_IO_ERROR;
 * }
 * static uint8_t my_is_connected(void *ud) {
 *     return ((MyCtx *)ud)->fd >= 0 ? 1 : 0;
 * }
 *
 * static MbusTransportCallbacks g_transport = {
 *     .userdata       = &g_ctx,
 *     .on_connect     = my_connect,
 *     .on_disconnect  = my_disconnect,
 *     .on_send        = my_send,
 *     .on_recv        = my_recv,
 *     .on_is_connected = my_is_connected,
 * };
 * ```
 */
typedef struct MbusTransportCallbacks {
    /**
     * Opaque pointer passed unchanged to every callback invocation.
     *
     * Typically points to your driver context struct (file descriptor, register
     * base address, mutex handle, etc.).  May be `NULL` if your callbacks do not
     * need per-instance state (e.g. a singleton UART driver).
     */
    void *userdata;
    /**
     * Open the physical connection.
     *
     * Called once by `mbus_*_connect`.  The stack does not call `on_send` or
     * `on_recv` until this returns `MBUS_OK`.
     *
     * # What to do
     * - Open the socket / serial port / SPI bus.
     * - Perform any hardware initialisation (baud rate, parity, stop bits).
     * - For serial servers: configure the UART but do **not** start receiving
     *   until you return — the stack will call `on_recv` on the first poll.
     *
     * # Return values
     * | Code | Meaning |
     * |------|---------|
     * | `MBUS_OK` | Connection established; stack proceeds normally. |
     * | `MBUS_ERR_CONNECTION_FAILED` | Could not open the port/socket (e.g. ENOENT, EACCES). |
     * | `MBUS_ERR_IO_ERROR` | Low-level I/O failure during hardware setup. |
     * | `MBUS_ERR_INVALID_CONFIGURATION` | Supplied config is not supported by this hardware. |
     *
     * Any other non-`MBUS_OK` code is mapped to `MbusError::Unexpected` internally.
     */
    enum MbusStatusCode (*on_connect)(void *userdata);
    /**
     * Close the physical connection.
     *
     * Called by `mbus_*_disconnect` and during server teardown.  After this
     * returns, the stack will not call `on_send` or `on_recv` until
     * `on_connect` is called again.
     *
     * # What to do
     * - Release the socket / serial port file descriptor.
     * - For RS-485: de-assert the transmit-enable line if your driver holds it.
     * - This function should be idempotent — calling it on an already-closed
     *   transport must not crash or return an error.
     *
     * # Return values
     * | Code | Meaning |
     * |------|---------|
     * | `MBUS_OK` | Disconnected successfully (or was already disconnected). |
     * | `MBUS_ERR_IO_ERROR` | An error occurred while flushing or closing the port. |
     *
     * The return value is checked but not acted upon by the stack beyond logging.
     */
    enum MbusStatusCode (*on_disconnect)(void *userdata);
    /**
     * Write a complete Modbus ADU frame to the medium.
     *
     * The stack calls this once per outgoing frame with a fully-formed byte
     * slice (`data[0..len]`).  The function must write **all** `len` bytes
     * atomically from the stack's perspective — partial writes are not retried
     * at the byte level.
     *
     * # Parameters
     * - `data`     — Pointer to the frame bytes.  Valid only for the duration
     *   of this call; do not retain it.
     * - `len`      — Number of bytes to send (always ≤ `MAX_ADU_FRAME_LEN` = 256).
     * - `userdata` — The value stored in `MbusTransportCallbacks::userdata`.
     *
     * # RS-485 / half-duplex requirement
     * Assert the TX-enable line **before** writing the first byte and
     * de-assert it **after** the last byte has been shifted out of the UART
     * FIFO (not just after the write syscall returns).  Failing to do this
     * corrupts the frame from the perspective of other nodes on the bus.
     *
     * # Return values
     * | Code | Meaning |
     * |------|---------|
     * | `MBUS_OK` | All bytes written successfully. |
     * | `MBUS_ERR_SEND_FAILED` | Write failed partway through (broken pipe, UART overflow). |
     * | `MBUS_ERR_IO_ERROR` | Hardware-level I/O error (DMA fault, framing error on TX). |
     * | `MBUS_ERR_CONNECTION_CLOSED` | The remote end closed the connection (TCP only). |
     *
     * On failure the stack queues the frame for retry (up to `max_send_retries`).
     */
    enum MbusStatusCode (*on_send)(const uint8_t *data, uint16_t len, void *userdata);
    /**
     * Read the next available Modbus ADU frame from the medium.
     *
     * The stack calls this once per `mbus_*_poll` invocation.  The function
     * must be **non-blocking** (or use a very short read timeout) so that the
     * poll loop remains responsive.
     *
     * # Parameters
     * - `buffer`     — Rust-allocated scratch buffer; write received bytes here.
     *   Valid only for the duration of this call.
     * - `buffer_cap` — Capacity of `buffer` in bytes (always `MAX_ADU_FRAME_LEN` = 256).
     *   Never write more than `buffer_cap` bytes.
     * - `out_len`    — Write the number of bytes placed in `buffer` here.
     *   Must be set to `0` when returning anything other than `MBUS_OK`.
     * - `userdata`   — The value stored in `MbusTransportCallbacks::userdata`.
     *
     * # TCP / stream transports
     * Read as many bytes as are available right now (non-blocking).  The Rust
     * layer uses a sliding window to assemble complete frames from partial reads;
     * you do not need to wait for a full frame.
     *
     * # Serial RTU transports — timing requirements
     * The `on_recv` callback is the correct place to enforce Modbus
     * inter-character timing (§2.5 of the Modbus Serial Line Specification):
     *
     * - **t3.5 (end-of-frame):** Wait until the line has been silent for at
     *   least 3.5 character times after the last received byte.  Only then
     *   return the accumulated bytes with `MBUS_OK`.  This ensures each
     *   `on_recv` call delivers exactly one complete frame.
     *
     * - **t1.5 (framing violation):** If silence of ≥ 1.5 character times is
     *   detected *between* bytes of the same frame, the frame is corrupt.
     *   Return **`MBUS_ERR_FRAMING_ERROR`** immediately.  The stack will:
     *     1. Discard all bytes buffered so far.
     *     2. Keep the transport connected.
     *     3. Resume waiting for a clean frame on the next poll.
     *
     * # Return values
     * | Code | Meaning |
     * |------|---------|
     * | `MBUS_OK` | Frame bytes written into `buffer`; `*out_len > 0`. |
     * | `MBUS_ERR_TIMEOUT` | No data available this poll (bus idle / no client request yet). The stack skips processing and polls again. |
     * | `MBUS_ERR_FRAMING_ERROR` | **Serial only.** t1.5 inter-character gap detected mid-frame. Stack discards the partial frame and continues. |
     * | `MBUS_ERR_IO_ERROR` | Hardware read error (UART overrun, DMA fault). Stack marks the transport as disconnected. |
     * | `MBUS_ERR_CONNECTION_CLOSED` | Remote closed the connection (TCP) or the port was unexpectedly closed. Stack disconnects and stops polling. |
     * | `MBUS_ERR_CONNECTION_LOST` | Connection dropped unexpectedly (e.g. TCP RST). Same effect as `CONNECTION_CLOSED`. |
     * | `MBUS_ERR_BUFFER_TOO_SMALL` | Frame exceeded `buffer_cap`. Stack discards data (should not happen under normal conditions). |
     *
     * **Do not** set `*out_len` to a non-zero value when returning an error code —
     * the stack ignores `buffer` contents on any non-`MBUS_OK` return.
     */
    enum MbusStatusCode (*on_recv)(uint8_t *buffer,
                                   uint16_t buffer_cap,
                                   uint16_t *out_len,
                                   void *userdata);
} MbusTransportCallbacks;

/**
 * Configuration for a Modbus TCP client.
 *
 * All pointer fields (`host`) must remain valid for the duration of the
 * `mbus_tcp_client_new` call. They are copied internally and do not need to
 * outlive the call.
 */
typedef struct MbusTcpConfig {
    /**
     * Null-terminated hostname or IPv4/IPv6 address string (max 63 bytes excl. NUL).
     */
    const char *host;
    /**
     * Backoff strategy between retries.
     */
    enum MbusBackoffStrategy backoff_strategy;
} MbusTcpConfig;

/**
 * A single sub-request passed to [`mbus_tcp_read_file_record`] /
 * [`mbus_tcp_write_file_record`] (and their serial equivalents).
 *
 * For **read** operations: populate `file_number`, `record_number`, and
 * `data_len` (number of registers to read); set `data` to NULL.
 *
 * For **write** operations: populate all four fields; `data` must point to
 * at least `data_len` valid `u16` words.
 */
typedef struct MbusSubRequest {
    /**
     * File number (1–65535).
     */
    uint16_t file_number;
} MbusSubRequest;

/**
 * Request context for FC 0x01 — Read Coils.
 *
 * C reads `address` and `quantity`; writes packed coil bits into `out_data` (at most
 * `out_data_len` bytes) and sets `out_byte_count` to the number of bytes written.
 */
typedef struct MbusServerReadCoilsReq {
    /**
     * Slave/unit address of the request.
     */
    uint8_t unit_id;
} MbusServerReadCoilsReq;

/**
 * C callback type for FC 0x01.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadCoilsFn)(struct MbusServerReadCoilsReq *req,
                                                              void *userdata);

/**
 * Request context for FC 0x05 — Write Single Coil.
 */
typedef struct MbusServerWriteSingleCoilReq {
    uint8_t unit_id;
    /**
     * `true` = force coil ON, `false` = force coil OFF.
     */
    bool value;
} MbusServerWriteSingleCoilReq;

/**
 * C callback type for FC 0x05.
 */
typedef enum MbusServerExceptionCode (*MbusServerWriteSingleCoilFn)(const struct MbusServerWriteSingleCoilReq *req,
                                                                    void *userdata);

/**
 * Request context for FC 0x0F — Write Multiple Coils.
 *
 * `values` is a packed bit array from the master (LSB of first byte = coil at
 * `starting_address`). Valid for the duration of the callback only.
 */
typedef struct MbusServerWriteMultipleCoilsReq {
    uint8_t unit_id;
} MbusServerWriteMultipleCoilsReq;

/**
 * C callback type for FC 0x0F.
 */
typedef enum MbusServerExceptionCode (*MbusServerWriteMultipleCoilsFn)(const struct MbusServerWriteMultipleCoilsReq *req,
                                                                       void *userdata);

/**
 * Request context for FC 0x02 — Read Discrete Inputs.
 */
typedef struct MbusServerReadDiscreteInputsReq {
    uint8_t unit_id;
} MbusServerReadDiscreteInputsReq;

/**
 * C callback type for FC 0x02.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadDiscreteInputsFn)(struct MbusServerReadDiscreteInputsReq *req,
                                                                       void *userdata);

/**
 * Request context for FC 0x03 — Read Holding Registers.
 *
 * `out_data` receives big-endian register bytes (2 bytes per register).
 * `out_byte_count` must be set to `quantity * 2` on success.
 */
typedef struct MbusServerReadHoldingRegistersReq {
    uint8_t unit_id;
} MbusServerReadHoldingRegistersReq;

/**
 * C callback type for FC 0x03.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadHoldingRegistersFn)(struct MbusServerReadHoldingRegistersReq *req,
                                                                         void *userdata);

/**
 * Request context for FC 0x06 — Write Single Register.
 */
typedef struct MbusServerWriteSingleRegisterReq {
    uint8_t unit_id;
} MbusServerWriteSingleRegisterReq;

/**
 * C callback type for FC 0x06.
 */
typedef enum MbusServerExceptionCode (*MbusServerWriteSingleRegisterFn)(const struct MbusServerWriteSingleRegisterReq *req,
                                                                        void *userdata);

/**
 * Request context for FC 0x10 — Write Multiple Registers.
 *
 * `values` contains the decoded `u16` register values (big-endian already parsed).
 * Valid for the duration of the callback only.
 */
typedef struct MbusServerWriteMultipleRegistersReq {
    uint8_t unit_id;
} MbusServerWriteMultipleRegistersReq;

/**
 * C callback type for FC 0x10.
 */
typedef enum MbusServerExceptionCode (*MbusServerWriteMultipleRegistersFn)(const struct MbusServerWriteMultipleRegistersReq *req,
                                                                           void *userdata);

/**
 * Request context for FC 0x16 — Mask Write Register.
 */
typedef struct MbusServerMaskWriteRegisterReq {
    uint8_t unit_id;
} MbusServerMaskWriteRegisterReq;

/**
 * C callback type for FC 0x16.
 */
typedef enum MbusServerExceptionCode (*MbusServerMaskWriteRegisterFn)(const struct MbusServerMaskWriteRegisterReq *req,
                                                                      void *userdata);

/**
 * Request context for FC 0x17 — Read/Write Multiple Registers.
 *
 * C writes the read result into `out_data` (big-endian register bytes) and sets
 * `out_byte_count`. `write_values` contains the decoded write values from the master.
 */
typedef struct MbusServerReadWriteMultipleRegistersReq {
    uint8_t unit_id;
} MbusServerReadWriteMultipleRegistersReq;

/**
 * C callback type for FC 0x17.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadWriteMultipleRegistersFn)(struct MbusServerReadWriteMultipleRegistersReq *req,
                                                                               void *userdata);

/**
 * Request context for FC 0x04 — Read Input Registers.
 */
typedef struct MbusServerReadInputRegistersReq {
    uint8_t unit_id;
} MbusServerReadInputRegistersReq;

/**
 * C callback type for FC 0x04.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadInputRegistersFn)(struct MbusServerReadInputRegistersReq *req,
                                                                       void *userdata);

/**
 * Request context for FC 0x18 — Read FIFO Queue.
 */
typedef struct MbusServerReadFifoQueueReq {
    uint8_t unit_id;
} MbusServerReadFifoQueueReq;

/**
 * C callback type for FC 0x18.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadFifoQueueFn)(struct MbusServerReadFifoQueueReq *req,
                                                                  void *userdata);

/**
 * Request context for FC 0x14 — Read File Record (one sub-request at a time).
 *
 * C writes record data bytes into `out_data` and sets `out_byte_count`.
 */
typedef struct MbusServerReadFileRecordReq {
    uint8_t unit_id;
} MbusServerReadFileRecordReq;

/**
 * C callback type for FC 0x14.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadFileRecordFn)(struct MbusServerReadFileRecordReq *req,
                                                                   void *userdata);

/**
 * Request context for FC 0x15 — Write File Record (one sub-request at a time).
 *
 * `record_data` contains decoded `u16` words. Valid for the callback duration only.
 */
typedef struct MbusServerWriteFileRecordReq {
    uint8_t unit_id;
} MbusServerWriteFileRecordReq;

/**
 * C callback type for FC 0x15.
 */
typedef enum MbusServerExceptionCode (*MbusServerWriteFileRecordFn)(const struct MbusServerWriteFileRecordReq *req,
                                                                    void *userdata);

/**
 * Request context for FC 0x07 — Read Exception Status.
 *
 * C sets `out_status` to the 8-bit exception status byte.
 */
typedef struct MbusServerReadExceptionStatusReq {
    uint8_t unit_id;
} MbusServerReadExceptionStatusReq;

/**
 * C callback type for FC 0x07.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadExceptionStatusFn)(struct MbusServerReadExceptionStatusReq *req,
                                                                        void *userdata);

/**
 * Request context for FC 0x08 — Diagnostics.
 *
 * `sub_function` is the raw 16-bit sub-function code (see Modbus spec §6.8).
 * C sets `out_result` to the 16-bit data echo/result.
 */
typedef struct MbusServerDiagnosticsReq {
    uint8_t unit_id;
} MbusServerDiagnosticsReq;

/**
 * C callback type for FC 0x08.
 */
typedef enum MbusServerExceptionCode (*MbusServerDiagnosticsFn)(struct MbusServerDiagnosticsReq *req,
                                                                void *userdata);

/**
 * Request context for FC 0x0B — Get Comm Event Counter.
 *
 * C sets `out_status` (status word) and `out_event_count`.
 */
typedef struct MbusServerGetCommEventCounterReq {
    uint8_t unit_id;
} MbusServerGetCommEventCounterReq;

/**
 * C callback type for FC 0x0B.
 */
typedef enum MbusServerExceptionCode (*MbusServerGetCommEventCounterFn)(struct MbusServerGetCommEventCounterReq *req,
                                                                        void *userdata);

/**
 * Request context for FC 0x0C — Get Comm Event Log.
 *
 * C writes event bytes into `out_events` (max `out_events_len` bytes) and
 * sets the four output scalar fields.
 */
typedef struct MbusServerGetCommEventLogReq {
    uint8_t unit_id;
} MbusServerGetCommEventLogReq;

/**
 * C callback type for FC 0x0C.
 */
typedef enum MbusServerExceptionCode (*MbusServerGetCommEventLogFn)(struct MbusServerGetCommEventLogReq *req,
                                                                    void *userdata);

/**
 * Request context for FC 0x11 — Report Server ID.
 *
 * C writes vendor/device identification bytes into `out_server_id` and sets
 * `out_byte_count` and `out_run_indicator_status`.
 */
typedef struct MbusServerReportServerIdReq {
    uint8_t unit_id;
} MbusServerReportServerIdReq;

/**
 * C callback type for FC 0x11.
 */
typedef enum MbusServerExceptionCode (*MbusServerReportServerIdFn)(struct MbusServerReportServerIdReq *req,
                                                                   void *userdata);

/**
 * Request context for FC 0x2B / MEI 0x0E — Read Device Identification.
 *
 * C writes object data into `out_data` and sets all `out_*` fields.
 */
typedef struct MbusServerReadDeviceIdentificationReq {
    uint8_t unit_id;
    /**
     * C must set to `true` if more objects follow (segmentation).
     */
    bool out_has_more;
} MbusServerReadDeviceIdentificationReq;

/**
 * C callback type for FC 0x2B / MEI 0x0E.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadDeviceIdentificationFn)(struct MbusServerReadDeviceIdentificationReq *req,
                                                                             void *userdata);

/**
 * Master callback table for a C Modbus server application.
 *
 * Pass a populated instance to `mbus_tcp_server_new`,
 * `mbus_serial_rtu_server_new`, or `mbus_serial_ascii_server_new`.
 *
 * ## NULL slots
 * Any callback slot left as `NULL` causes the server to respond with
 * `ExceptionCode::IllegalFunction` (0x01) for that function code.
 * You do not need to implement callbacks for function codes your device
 * does not support.
 *
 * ## Return value contract
 * Every callback returns `MbusServerExceptionCode`.  The server uses this to
 * decide what to send on the wire:
 *
 * | Return value | Wire response |
 * |---|---|
 * | `Ok` | Normal success response (echo or `out_*` data). |
 * | `IllegalFunction` | Exception response 0x01. |
 * | `IllegalDataAddress` | Exception response 0x02. |
 * | `IllegalDataValue` | Exception response 0x03. |
 * | `ServerDeviceFailure` | Exception response 0x04. |
 *
 * ## Timing — serial servers
 * Callbacks are invoked from within `mbus_serial_server_poll`.  The stack
 * does **not** call the `recv` callback while a callback is running, so you
 * cannot observe a t1.5/t3.5 violation from inside a handler.  Timing
 * violations are detected and reported exclusively through the `recv`
 * transport callback before dispatch (see the `serial_server` module docs).
 *
 * ## Lifetime of pointer fields
 * All `*mut` and `*const` pointer fields in the `*Req` structs are valid only
 * for the duration of the callback invocation.  Do **not** retain them.
 *
 * ## Example (C)
 *
 * ```c
 * static MbusServerHandlers g_handlers = {
 *     .userdata             = &my_app_state,
 *     .on_read_holding_registers = my_read_hr_handler,
 *     .on_write_single_register  = my_write_sr_handler,
 *     // All other slots are NULL → server returns IllegalFunction.
 * };
 * ```
 */
typedef struct MbusServerHandlers {
    /**
     * Opaque pointer passed to every callback.
     */
    void *userdata;
    MbusServerReadCoilsFn on_read_coils;
    MbusServerWriteSingleCoilFn on_write_single_coil;
    MbusServerWriteMultipleCoilsFn on_write_multiple_coils;
    MbusServerReadDiscreteInputsFn on_read_discrete_inputs;
    MbusServerReadHoldingRegistersFn on_read_holding_registers;
    MbusServerWriteSingleRegisterFn on_write_single_register;
    MbusServerWriteMultipleRegistersFn on_write_multiple_registers;
    MbusServerMaskWriteRegisterFn on_mask_write_register;
    MbusServerReadWriteMultipleRegistersFn on_read_write_multiple_registers;
    MbusServerReadInputRegistersFn on_read_input_registers;
    MbusServerReadFifoQueueFn on_read_fifo_queue;
    MbusServerReadFileRecordFn on_read_file_record;
    MbusServerWriteFileRecordFn on_write_file_record;
    MbusServerReadExceptionStatusFn on_read_exception_status;
    MbusServerDiagnosticsFn on_diagnostics;
    MbusServerGetCommEventCounterFn on_get_comm_event_counter;
    MbusServerGetCommEventLogFn on_get_comm_event_log;
    MbusServerReportServerIdFn on_report_server_id;
    MbusServerReadDeviceIdentificationFn on_read_device_identification;
} MbusServerHandlers;

/**
 * Common server configuration shared by TCP and Serial server types.
 *
 * Only fields that influence the server runtime logic are included here;
 * transport-level details (host address, port, baud rate) are handled
 * separately in the `_new` constructor callbacks.
 */
typedef struct MbusServerConfig {
    /**
     * Slave/unit address this server will respond to.  Valid range: 1–247.
     * For TCP-only deployments the conventional value is 1 or 0xFF.
     */
    uint8_t slave_address;
} MbusServerConfig;

/**
 * Status code returned by every `mbus_go_*` function.
 *
 * Numerically identical to [`crate::c::error::MbusStatusCode`].
 */
typedef enum MbusStatusCode MbusGoStatus;

/**
 * A sub-request descriptor for serial file record operations.
 *
 * Identical layout to `MbusGoSubRequest` in `tcp.rs` — shared by both
 * transport variants so Go can use the same struct definition.
 */
typedef struct MbusGoSerialSubRequest {
    /**
     * File number (1–65535).
     */
    uint16_t file_number;
} MbusGoSerialSubRequest;

/**
 * A sub-request descriptor used by [`mbus_go_tcp_client_read_file_record`] and
 * [`mbus_go_tcp_client_write_file_record`].
 *
 * **Read** sub-requests: set `data` to `null` and `data_len` to `0`; fill
 * `file_number`, `record_number`, and `record_length` with the target record.
 *
 * **Write** sub-requests: set `data` to a pointer to `data_len` `u16` words and
 * ensure `record_length == data_len`.
 */
typedef struct MbusGoSubRequest {
    /**
     * File number (1–65535).
     */
    uint16_t file_number;
} MbusGoSubRequest;

/**
 * C-compatible vtable of optional Modbus request handler callbacks.
 *
 * Set any slot to `None` (`null` from Go) to return an `IllegalFunction`
 * exception for that function code.  All function pointers receive `ctx` as
 * their first argument.
 *
 * # Repr
 *
 * The struct uses `#[repr(C)]` so that it has a stable, platform-defined
 * layout.  Pass it by pointer to `mbus_go_tcp_server_new`.
 */


/**
 * Returns a static null-terminated C string describing the status code.
 *
 * The returned pointer is always valid (points to a static string literal).
 * The caller must NOT free it.
 */
const char *mbus_status_str(enum MbusStatusCode code);

/**
 * No-op stub for pool lock (used when no external C caller provides it).
 */
void mbus_pool_lock(void);

/**
 * No-op stub for pool unlock.
 */
void mbus_pool_unlock(void);

/**
 * Returns the starting address of the coils range.
 *
 * # Safety
 * `coils` must either be null (returns 0) or point to a valid `MbusCoils`.
 */
uint16_t mbus_coils_from_address(const MbusCoils *coils);

/**
 * Returns the number of coils.
 *
 * # Safety
 * `coils` must either be null (returns 0) or point to a valid `MbusCoils`.
 */
uint16_t mbus_coils_quantity(const MbusCoils *coils);

/**
 * Reads a single coil value by address into `out_value`.
 *
 * # Safety
 * `coils` and `out_value` must be non-null and point to valid memory, or null
 * (returns `MBUS_ERR_NULL_POINTER` for null).
 */
enum MbusStatusCode mbus_coils_value(const MbusCoils *coils, uint16_t address, bool *out_value);

/**
 * Reads a single coil value by 0-based index into `out_value`.
 *
 * `index` must be less than [`mbus_coils_quantity`]; otherwise returns
 * `MBUS_ERR_INVALID_ADDRESS`. Unlike [`mbus_coils_value`], no knowledge of
 * the Modbus starting address is required.
 *
 * # Safety
 * `coils` and `out_value` must be non-null and point to valid memory, or null
 * (returns `MBUS_ERR_NULL_POINTER` for null).
 */
enum MbusStatusCode mbus_coils_value_at_index(const MbusCoils *coils,
                                              uint16_t index,
                                              bool *out_value);

/**
 * Returns a raw pointer to the packed coil bit-values. Valid during callback only.
 *
 * # Safety
 * `coils` must either be null (returns a null pointer) or point to a valid `MbusCoils`.
 */
const uint8_t *mbus_coils_values_ptr(const MbusCoils *coils);

/**
 * Returns the starting address of the discrete inputs range.
 *
 * # Safety
 * `discrete_inputs` must either be null (returns 0) or point to a valid `MbusDiscreteInputs`.
 */
uint16_t mbus_discrete_inputs_from_address(const MbusDiscreteInputs *discrete_inputs);

/**
 * Returns the number of discrete inputs.
 *
 * # Safety
 * `discrete_inputs` must either be null (returns 0) or point to a valid `MbusDiscreteInputs`.
 */
uint16_t mbus_discrete_inputs_quantity(const MbusDiscreteInputs *discrete_inputs);

/**
 * Reads a single discrete input value by address into `out_value`.
 *
 * # Safety
 * `discrete_inputs` and `out_value` must be non-null and point to valid memory, or null
 * (returns `MBUS_ERR_NULL_POINTER` for null).
 */
enum MbusStatusCode mbus_discrete_inputs_value(const MbusDiscreteInputs *discrete_inputs,
                                               uint16_t address,
                                               bool *out_value);

/**
 * Reads a single discrete input value by 0-based index into `out_value`.
 *
 * `index` must be less than [`mbus_discrete_inputs_quantity`]; otherwise returns
 * `MBUS_ERR_INVALID_ADDRESS`. Unlike [`mbus_discrete_inputs_value`], no knowledge
 * of the Modbus starting address is required.
 *
 * # Safety
 * `discrete_inputs` and `out_value` must be non-null and point to valid memory, or null
 * (returns `MBUS_ERR_NULL_POINTER` for null).
 */
enum MbusStatusCode mbus_discrete_inputs_value_at_index(const MbusDiscreteInputs *discrete_inputs,
                                                        uint16_t index,
                                                        bool *out_value);

/**
 * Returns a raw pointer to the discrete input bit-values. Valid during callback only.
 *
 * # Safety
 * `discrete_inputs` must either be null (returns a null pointer) or point to a valid
 * `MbusDiscreteInputs`.
 */
const uint8_t *mbus_discrete_inputs_values_ptr(const MbusDiscreteInputs *discrete_inputs);

/**
 * Returns the FIFO pointer address.
 *
 * # Safety
 * `fifo_queue` must either be null (returns 0) or point to a valid `MbusFifoQueue`.
 */
uint16_t mbus_fifo_queue_ptr_address(const MbusFifoQueue *fifo_queue);

/**
 * Returns the number of values in the FIFO queue.
 *
 * # Safety
 * `fifo_queue` must either be null (returns 0) or point to a valid `MbusFifoQueue`.
 */
uint16_t mbus_fifo_queue_count(const MbusFifoQueue *fifo_queue);

/**
 * Reads a FIFO value by index.
 *
 * # Safety
 * `fifo_queue` and `out_value` must be non-null and point to valid memory, or null
 * (returns `MBUS_ERR_NULL_POINTER` for null).
 */
enum MbusStatusCode mbus_fifo_queue_value(const MbusFifoQueue *fifo_queue,
                                          uint16_t index,
                                          uint16_t *out_value);

/**
 * Returns a raw pointer to the FIFO values. Valid during callback only.
 *
 * # Safety
 * `fifo_queue` must either be null (returns a null pointer) or point to a valid `MbusFifoQueue`.
 */
const uint16_t *mbus_fifo_queue_values_ptr(const MbusFifoQueue *fifo_queue);

/**
 * Returns the starting address of the registers range.
 *
 * # Safety
 * `registers` must either be null (returns 0) or point to a valid `MbusRegisters`.
 */
uint16_t mbus_registers_from_address(const MbusRegisters *registers);

/**
 * Returns the number of registers.
 *
 * # Safety
 * `registers` must either be null (returns 0) or point to a valid `MbusRegisters`.
 */
uint16_t mbus_registers_quantity(const MbusRegisters *registers);

/**
 * Reads a single register value by address into `out_value`.
 *
 * # Safety
 * `registers` and `out_value` must be non-null and point to valid memory, or null
 * (returns `MBUS_ERR_NULL_POINTER` for null).
 */
enum MbusStatusCode mbus_registers_value(const MbusRegisters *registers,
                                         uint16_t address,
                                         uint16_t *out_value);

/**
 * Reads a single register value by 0-based index into `out_value`.
 *
 * `index` must be less than [`mbus_registers_quantity`]; otherwise returns
 * `MBUS_ERR_INVALID_ADDRESS`. Unlike [`mbus_registers_value`], no knowledge of
 * the Modbus starting address is required.
 *
 * # Safety
 * `registers` and `out_value` must be non-null and point to valid memory, or null
 * (returns `MBUS_ERR_NULL_POINTER` for null).
 */
enum MbusStatusCode mbus_registers_value_at_index(const MbusRegisters *registers,
                                                  uint16_t index,
                                                  uint16_t *out_value);

/**
 * Returns a raw pointer to the register values. Valid during callback only.
 *
 * # Safety
 * `registers` must either be null (returns a null pointer) or point to a valid `MbusRegisters`.
 */
const uint16_t *mbus_registers_values_ptr(const MbusRegisters *registers);

/**
 * Lock the global pool (used only during client creation/destruction).
 */
extern void mbus_pool_lock(void);

/**
 * Unlock the global pool.
 */
extern void mbus_pool_unlock(void);

/**
 * Open the serial port with the configured parameters.
 */
enum MbusStatusCode mbus_serial_connect(MbusClientId id);

/**
 * Close the serial port.
 *
 * Pending in-flight requests are failed immediately with `MBUS_ERR_CONNECTION_LOST`.
 * The client ID remains valid; call [`mbus_serial_connect`] to reopen the port.
 */
enum MbusStatusCode mbus_serial_disconnect(MbusClientId id);

/**
 * Returns `1` if the serial port is currently open, `0` otherwise.
 */
uint8_t mbus_serial_is_connected(MbusClientId id);

/**
 * Drive the serial Modbus state machine once.
 *
 * Call periodically from your application loop. All registered callbacks are
 * invoked synchronously from within this call.
 */
void mbus_serial_poll(MbusClientId id);

/**
 * Returns `1` if the client has in-flight requests awaiting response/timeout,
 * `0` otherwise.
 */
uint8_t mbus_serial_has_pending_requests(MbusClientId id);

/**
 * Disconnect then reconnect the serial port.
 */
enum MbusStatusCode mbus_serial_reconnect(MbusClientId id);

/**
 * Open the TCP connection to the configured host:port.
 *
 * Returns `MBUS_OK` on success or a specific error code on failure.
 */
enum MbusStatusCode mbus_tcp_connect(MbusClientId id);

/**
 * Close the TCP connection.
 *
 * Pending in-flight requests are failed immediately with `MBUS_ERR_CONNECTION_LOST`.
 * The client ID remains valid; call [`mbus_tcp_connect`] to reconnect.
 */
enum MbusStatusCode mbus_tcp_disconnect(MbusClientId id);

/**
 * Returns `1` if the TCP connection is currently open, `0` otherwise.
 */
uint8_t mbus_tcp_is_connected(MbusClientId id);

/**
 * Drive the Modbus state machine: receive pending frames, match responses to
 * outstanding requests, fire any ready callbacks, and handle timeouts / retries.
 *
 * Call this function periodically (e.g. every 5–20 ms) from your application
 * loop. All registered callbacks are invoked synchronously from within this call.
 */
void mbus_tcp_poll(MbusClientId id);

/**
 * Returns `1` if the client has in-flight requests awaiting response/timeout,
 * `0` otherwise.
 */
uint8_t mbus_tcp_has_pending_requests(MbusClientId id);

/**
 * Disconnect then reconnect. Useful after a `MBUS_ERR_CONNECTION_LOST` callback.
 */
enum MbusStatusCode mbus_tcp_reconnect(MbusClientId id);

/**
 * Queue a Read Coils (FC 0x01) request.
 *
 * The response is delivered via `MbusCallbacks::on_read_coils`.
 */
enum MbusStatusCode mbus_tcp_read_coils(MbusClientId id,
                                        uint16_t txn_id,
                                        uint8_t unit_id,
                                        uint16_t address,
                                        uint16_t quantity);

/**
 * Queue a Read Coils (FC 0x01) request on a serial client.
 */
enum MbusStatusCode mbus_serial_read_coils(MbusClientId id,
                                           uint16_t txn_id,
                                           uint8_t unit_id,
                                           uint16_t address,
                                           uint16_t quantity);

/**
 * Queue a Read Single Coil request (reads FC 0x01 with quantity=1).
 */
enum MbusStatusCode mbus_tcp_read_single_coil(MbusClientId id,
                                              uint16_t txn_id,
                                              uint8_t unit_id,
                                              uint16_t address);

/**
 * Queue a Read Single Coil request on a serial client.
 */
enum MbusStatusCode mbus_serial_read_single_coil(MbusClientId id,
                                                 uint16_t txn_id,
                                                 uint8_t unit_id,
                                                 uint16_t address);

/**
 * Queue a Write Single Coil (FC 0x05) request. `value`: 1 = ON, 0 = OFF.
 */
enum MbusStatusCode mbus_tcp_write_single_coil(MbusClientId id,
                                               uint16_t txn_id,
                                               uint8_t unit_id,
                                               uint16_t address,
                                               uint8_t value);

/**
 * Queue a Write Single Coil (FC 0x05) request on a serial client.
 */
enum MbusStatusCode mbus_serial_write_single_coil(MbusClientId id,
                                                  uint16_t txn_id,
                                                  uint8_t unit_id,
                                                  uint16_t address,
                                                  uint8_t value);

/**
 * Queue a Write Multiple Coils (FC 0x0F) request.
 *
 * `values` must point to at least `ceil(quantity / 8)` bytes of bit-packed coil
 * data (LSB-first). Valid for the duration of this call only.
 *
 * # Safety
 * `values` must be a valid non-null pointer.
 */
enum MbusStatusCode mbus_tcp_write_multiple_coils(MbusClientId id,
                                                  uint16_t txn_id,
                                                  uint8_t unit_id,
                                                  uint16_t address,
                                                  const uint8_t *values,
                                                  uint16_t quantity);

/**
 * Queue a Write Multiple Coils (FC 0x0F) request on a serial client.
 *
 * # Safety
 * `values` must be a valid non-null pointer.
 */
enum MbusStatusCode mbus_serial_write_multiple_coils(MbusClientId id,
                                                     uint16_t txn_id,
                                                     uint8_t unit_id,
                                                     uint16_t address,
                                                     const uint8_t *values,
                                                     uint16_t quantity);

/**
 * Queue a Diagnostics (FC 0x08) request.
 *
 * # Safety
 * If `data_len > 0`, `data` must be valid for that many `u16` words.
 */
enum MbusStatusCode mbus_tcp_diagnostics(MbusClientId id,
                                         uint16_t txn_id,
                                         uint8_t unit_id,
                                         uint16_t sub_fn,
                                         const uint16_t *data,
                                         uint16_t data_len);

/**
 * Queue a Diagnostics (FC 0x08) request on a serial client.
 *
 * # Safety
 * If `data_len > 0`, `data` must be valid for that many `u16` words.
 */
enum MbusStatusCode mbus_serial_diagnostics(MbusClientId id,
                                            uint16_t txn_id,
                                            uint8_t unit_id,
                                            uint16_t sub_fn,
                                            const uint16_t *data,
                                            uint16_t data_len);

/**
 * Queue a Read Device Identification (FC 0x2B/0x0E) request.
 *
 * `dev_id_code`: 1=Basic, 2=Regular, 3=Extended, 4=Specific.
 * `object_id`: starting object ID (0x00–0xFF).
 */
enum MbusStatusCode mbus_tcp_read_device_identification(MbusClientId id,
                                                        uint16_t txn_id,
                                                        uint8_t unit_id,
                                                        uint8_t dev_id_code,
                                                        uint8_t object_id);

/**
 * Queue a Read Device Identification request on a serial client.
 */
enum MbusStatusCode mbus_serial_read_device_identification(MbusClientId id,
                                                           uint16_t txn_id,
                                                           uint8_t unit_id,
                                                           uint8_t dev_id_code,
                                                           uint8_t object_id);

/**
 * Queue a Read Discrete Inputs (FC 0x02) request.
 *
 * The response is delivered via `MbusCallbacks::on_read_discrete_inputs`.
 */
enum MbusStatusCode mbus_tcp_read_discrete_inputs(MbusClientId id,
                                                  uint16_t txn_id,
                                                  uint8_t unit_id,
                                                  uint16_t address,
                                                  uint16_t quantity);

/**
 * Queue a Read Discrete Inputs (FC 0x02) request on a serial client.
 */
enum MbusStatusCode mbus_serial_read_discrete_inputs(MbusClientId id,
                                                     uint16_t txn_id,
                                                     uint8_t unit_id,
                                                     uint16_t address,
                                                     uint16_t quantity);

/**
 * Queue a Read Single Discrete Input request (FC 0x02 with quantity=1).
 */
enum MbusStatusCode mbus_tcp_read_single_discrete_input(MbusClientId id,
                                                        uint16_t txn_id,
                                                        uint8_t unit_id,
                                                        uint16_t address);

/**
 * Queue a Read Single Discrete Input request on a serial client.
 */
enum MbusStatusCode mbus_serial_read_single_discrete_input(MbusClientId id,
                                                           uint16_t txn_id,
                                                           uint8_t unit_id,
                                                           uint16_t address);

/**
 * Queue a Read FIFO Queue (FC 0x18) request.
 *
 * The response is delivered via `MbusCallbacks::on_read_fifo_queue`.
 */
enum MbusStatusCode mbus_tcp_read_fifo_queue(MbusClientId id,
                                             uint16_t txn_id,
                                             uint8_t unit_id,
                                             uint16_t address);

/**
 * Queue a Read FIFO Queue (FC 0x18) request on a serial client.
 */
enum MbusStatusCode mbus_serial_read_fifo_queue(MbusClientId id,
                                                uint16_t txn_id,
                                                uint8_t unit_id,
                                                uint16_t address);

/**
 * Queue a Read File Record (FC 0x14) request.
 *
 * # Safety
 * `sub_reqs` must be a valid non-null pointer to `count` items.
 */
enum MbusStatusCode mbus_tcp_read_file_record(MbusClientId id,
                                              uint16_t txn_id,
                                              uint8_t unit_id,
                                              const struct MbusSubRequest *sub_reqs,
                                              uint16_t count);

/**
 * Queue a Read File Record (FC 0x14) request on a serial client.
 *
 * # Safety
 * `sub_reqs` must be a valid non-null pointer to `count` items.
 */
enum MbusStatusCode mbus_serial_read_file_record(MbusClientId id,
                                                 uint16_t txn_id,
                                                 uint8_t unit_id,
                                                 const struct MbusSubRequest *sub_reqs,
                                                 uint16_t count);

/**
 * Queue a Write File Record (FC 0x15) request.
 *
 * # Safety
 * `sub_reqs` must be valid. Each `sub_reqs[i].data` must be valid for
 * `sub_reqs[i].data_len` words.
 */
enum MbusStatusCode mbus_tcp_write_file_record(MbusClientId id,
                                               uint16_t txn_id,
                                               uint8_t unit_id,
                                               const struct MbusSubRequest *sub_reqs,
                                               uint16_t count);

/**
 * Queue a Write File Record (FC 0x15) request on a serial client.
 *
 * # Safety
 * `sub_reqs` must be valid. Each `sub_reqs[i].data` must be valid for
 * `sub_reqs[i].data_len` words.
 */
enum MbusStatusCode mbus_serial_write_file_record(MbusClientId id,
                                                  uint16_t txn_id,
                                                  uint8_t unit_id,
                                                  const struct MbusSubRequest *sub_reqs,
                                                  uint16_t count);

/**
 * Queue a Write Multiple Registers (FC 0x10) request.
 *
 * `values` must point to at least `quantity` `u16` words, valid for this call only.
 *
 * # Safety
 * `values` must be a valid non-null pointer.
 */
enum MbusStatusCode mbus_tcp_write_multiple_registers(MbusClientId id,
                                                      uint16_t txn_id,
                                                      uint8_t unit_id,
                                                      uint16_t address,
                                                      const uint16_t *values,
                                                      uint16_t quantity);

/**
 * Queue a Write Multiple Registers (FC 0x10) request on a serial client.
 *
 * # Safety
 * `values` must be a valid non-null pointer.
 */
enum MbusStatusCode mbus_serial_write_multiple_registers(MbusClientId id,
                                                         uint16_t txn_id,
                                                         uint8_t unit_id,
                                                         uint16_t address,
                                                         const uint16_t *values,
                                                         uint16_t quantity);

/**
 * Queue a Read/Write Multiple Registers (FC 0x17) request.
 *
 * `write_values` must point to at least `write_qty` valid `u16` words.
 *
 * # Safety
 * `write_values` must be a valid non-null pointer.
 */
enum MbusStatusCode mbus_tcp_read_write_multiple_registers(MbusClientId id,
                                                           uint16_t txn_id,
                                                           uint8_t unit_id,
                                                           uint16_t read_address,
                                                           uint16_t read_qty,
                                                           uint16_t write_address,
                                                           const uint16_t *write_values,
                                                           uint16_t write_qty);

/**
 * Queue a Read/Write Multiple Registers (FC 0x17) request on a serial client.
 *
 * # Safety
 * `write_values` must be a valid non-null pointer.
 */
enum MbusStatusCode mbus_serial_read_write_multiple_registers(MbusClientId id,
                                                              uint16_t txn_id,
                                                              uint8_t unit_id,
                                                              uint16_t read_address,
                                                              uint16_t read_qty,
                                                              uint16_t write_address,
                                                              const uint16_t *write_values,
                                                              uint16_t write_qty);

/**
 * Lock the global server pool (used only during server creation/destruction).
 */
extern void mbus_pool_lock(void);

/**
 * Unlock the global server pool.
 */
extern void mbus_pool_unlock(void);

/**
 * Creates a new Modbus Serial RTU server and returns an opaque server ID.
 *
 * # Parameters
 * - `transport` — Transport callbacks providing connect/disconnect/send/recv.
 *   The `recv` callback is responsible for t1.5/t3.5 silence detection (see
 *   the module-level timing section).
 * - `handlers`  — Application callback table. `NULL` slots automatically
 *   respond with `IllegalFunction` for that function code.
 * - `config`    — Server configuration (slave address, timeout).
 *
 * # Returns
 * A valid `MbusServerId` on success, or `MBUS_INVALID_SERVER_ID` on failure.
 *
 * `MBUS_INVALID_SERVER_ID` is returned when:
 * - Any pointer argument is `NULL`.
 * - Any required function pointer inside `transport` is `NULL`.
 * - `config.slave_address` is outside the valid range 1–247.
 * - The internal serial server pool is exhausted.
 *
 * # Safety
 * - `transport`, `handlers`, and `config` must remain valid for the entire
 *   lifetime of the server (until `mbus_serial_server_free` is called).
 * - All function pointers inside `transport` must be valid C functions.
 * - `handlers.userdata` must outlive the server.
 */
MbusServerId mbus_serial_rtu_server_new(const struct MbusTransportCallbacks *transport,
                                        const struct MbusServerHandlers *handlers,
                                        const struct MbusServerConfig *config);

/**
 * Creates a new Modbus Serial ASCII server and returns an opaque server ID.
 *
 * ASCII mode uses LRC checksums and `:` / CR-LF delimiters instead of CRC and
 * silence-based framing, so t1.5/t3.5 inter-character timing is relaxed.
 * The `recv` callback may still return `MbusErrFramingError` if the ASCII frame
 * is malformed (e.g. an unexpected character between `:` and CR-LF).
 *
 * # Parameters
 * - `transport` — Transport callbacks for the underlying serial port.
 * - `handlers`  — Application callback table.
 * - `config`    — Server configuration (slave address, timeout).
 *
 * # Returns
 * A valid `MbusServerId` on success, or `MBUS_INVALID_SERVER_ID` on failure.
 *
 * `MBUS_INVALID_SERVER_ID` is returned under the same conditions as
 * `mbus_serial_rtu_server_new` (null pointers, invalid slave address, pool full).
 *
 * # Safety
 * Same requirements as `mbus_serial_rtu_server_new`.
 */
MbusServerId mbus_serial_ascii_server_new(const struct MbusTransportCallbacks *transport,
                                          const struct MbusServerHandlers *handlers,
                                          const struct MbusServerConfig *config);

/**
 * Global pool lock — held only during create/destroy operations. Reuses
 * the same symbol exported by the client pool.
 */
extern void mbus_pool_lock(void);

/**
 * Release the global pool lock.
 */
extern void mbus_pool_unlock(void);

/**
 * Creates a new RTU serial client.
 *
 * `port` must be a NUL-terminated UTF-8 path string (e.g. `"/dev/ttyUSB0"` on
 * Linux or `"COM3"` on Windows).  `parity` is `0`=None, `1`=Even, `2`=Odd.
 * Returns `null` on any configuration or construction failure.
 *
 * # Safety
 *
 * `port` must point to a valid NUL-terminated string for the duration of the call.
 */
MbusGoSerialClient *mbus_go_serial_client_new_rtu(const char *port,
                                                  uint32_t baud_rate,
                                                  uint8_t data_bits,
                                                  uint8_t parity,
                                                  uint8_t stop_bits,
                                                  uint32_t response_timeout_ms);

/**
 * Creates a new ASCII serial client.
 *
 * See [`mbus_go_serial_client_new_rtu`] for parameter semantics.
 *
 * # Safety
 *
 * `port` must point to a valid NUL-terminated string for the duration of the call.
 */
MbusGoSerialClient *mbus_go_serial_client_new_ascii(const char *port,
                                                    uint32_t baud_rate,
                                                    uint8_t data_bits,
                                                    uint8_t parity,
                                                    uint8_t stop_bits,
                                                    uint32_t response_timeout_ms);

/**
 * Destroys the serial client and releases all associated resources.
 *
 * # Safety
 *
 * `handle` must be a valid pointer originally returned by one of the
 * `mbus_go_serial_client_new_*` constructors.  Calling this function more
 * than once with the same pointer is undefined behaviour.
 */
void mbus_go_serial_client_free(MbusGoSerialClient *handle);

/**
 * Opens the underlying serial port.
 *
 * # Safety
 *
 * `handle` must be a valid client pointer.
 */
MbusGoStatus mbus_go_serial_client_connect(MbusGoSerialClient *handle);

/**
 * Closes the underlying serial port.
 *
 * # Safety
 *
 * `handle` must be a valid client pointer.
 */
MbusGoStatus mbus_go_serial_client_disconnect(MbusGoSerialClient *handle);

/**
 * Sets the per-request timeout in milliseconds (`0` = no timeout).
 *
 * # Safety
 *
 * `handle` must be a valid client pointer.
 */
void mbus_go_serial_client_set_request_timeout_ms(MbusGoSerialClient *handle, uint64_t timeout_ms);

/**
 * Reads `quantity` holding registers (FC03).
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_read_holding_registers(MbusGoSerialClient *handle,
                                                          uint8_t unit_id,
                                                          uint16_t address,
                                                          uint16_t quantity,
                                                          uint16_t *out_buf,
                                                          uint16_t out_buf_len,
                                                          uint16_t *out_count);

/**
 * Writes a single holding register (FC06).
 *
 * # Safety
 *
 * `handle` must be a valid client pointer.
 */
MbusGoStatus mbus_go_serial_client_write_single_register(MbusGoSerialClient *handle,
                                                         uint8_t unit_id,
                                                         uint16_t address,
                                                         uint16_t value,
                                                         uint16_t *out_address,
                                                         uint16_t *out_value);

/**
 * Writes multiple holding registers (FC16).
 *
 * `values` is a slice of `quantity` big-endian register words.
 *
 * # Safety
 *
 * `handle` and `values` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_write_multiple_registers(MbusGoSerialClient *handle,
                                                            uint8_t unit_id,
                                                            uint16_t address,
                                                            const uint16_t *values,
                                                            uint16_t quantity,
                                                            uint16_t *out_address,
                                                            uint16_t *out_quantity);

/**
 * Reads `quantity` input registers (FC04).
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_read_input_registers(MbusGoSerialClient *handle,
                                                        uint8_t unit_id,
                                                        uint16_t address,
                                                        uint16_t quantity,
                                                        uint16_t *out_buf,
                                                        uint16_t out_buf_len,
                                                        uint16_t *out_count);

/**
 * Applies an AND/OR bitmask to a holding register (FC22).
 *
 * # Safety
 *
 * `handle` must be a valid client pointer.
 */
MbusGoStatus mbus_go_serial_client_mask_write_register(MbusGoSerialClient *handle,
                                                       uint8_t unit_id,
                                                       uint16_t address,
                                                       uint16_t and_mask,
                                                       uint16_t or_mask);

/**
 * Reads and simultaneously writes multiple holding registers (FC23).
 *
 * # Safety
 *
 * `handle`, `write_values`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_read_write_multiple_registers(MbusGoSerialClient *handle,
                                                                 uint8_t unit_id,
                                                                 uint16_t read_address,
                                                                 uint16_t read_quantity,
                                                                 uint16_t write_address,
                                                                 const uint16_t *write_values,
                                                                 uint16_t write_quantity,
                                                                 uint16_t *out_buf,
                                                                 uint16_t out_buf_len,
                                                                 uint16_t *out_count);

/**
 * Reads `quantity` coils (FC01).
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_read_coils(MbusGoSerialClient *handle,
                                              uint8_t unit_id,
                                              uint16_t address,
                                              uint16_t quantity,
                                              uint8_t *out_buf,
                                              uint16_t out_buf_len,
                                              uint16_t *out_count);

/**
 * Writes a single coil (FC05).
 *
 * # Safety
 *
 * `handle` must be a valid client pointer.
 */
MbusGoStatus mbus_go_serial_client_write_single_coil(MbusGoSerialClient *handle,
                                                     uint8_t unit_id,
                                                     uint16_t address,
                                                     uint8_t value,
                                                     uint16_t *out_address,
                                                     uint8_t *out_value);

/**
 * Writes multiple coils (FC15).
 *
 * # Safety
 *
 * `handle` and `packed_coils` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_write_multiple_coils(MbusGoSerialClient *handle,
                                                        uint8_t unit_id,
                                                        uint16_t address,
                                                        const uint8_t *packed_coils,
                                                        uint16_t byte_count,
                                                        uint16_t coil_count,
                                                        uint16_t *out_address,
                                                        uint16_t *out_quantity);

/**
 * Reads `quantity` discrete inputs (FC02).
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_read_discrete_inputs(MbusGoSerialClient *handle,
                                                        uint8_t unit_id,
                                                        uint16_t address,
                                                        uint16_t quantity,
                                                        uint8_t *out_buf,
                                                        uint16_t out_buf_len,
                                                        uint16_t *out_count);

/**
 * Reads the FIFO queue (FC24).
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_read_fifo_queue(MbusGoSerialClient *handle,
                                                   uint8_t unit_id,
                                                   uint16_t address,
                                                   uint16_t *out_buf,
                                                   uint16_t out_buf_len,
                                                   uint16_t *out_count);

/**
 * Reads the device exception status (FC07).
 *
 * # Safety
 *
 * `handle` and `out_status` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_read_exception_status(MbusGoSerialClient *handle,
                                                         uint8_t unit_id,
                                                         uint8_t *out_status);

/**
 * Reads the communication event counter (FC11).
 *
 * # Safety
 *
 * `handle`, `out_status`, and `out_event_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_get_comm_event_counter(MbusGoSerialClient *handle,
                                                          uint8_t unit_id,
                                                          uint16_t *out_status,
                                                          uint16_t *out_event_count);

/**
 * Reads the communication event log (FC12).
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_get_comm_event_log(MbusGoSerialClient *handle,
                                                      uint8_t unit_id,
                                                      uint8_t *out_buf,
                                                      uint16_t out_buf_len,
                                                      uint16_t *out_count);

/**
 * Reports the server identifier (FC17).
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_serial_client_report_server_id(MbusGoSerialClient *handle,
                                                    uint8_t unit_id,
                                                    uint8_t *out_buf,
                                                    uint16_t out_buf_len,
                                                    uint16_t *out_count);

/**
 * Sends a Diagnostics (FC08) request.
 *
 * # Safety
 *
 * `handle`, `out_sub_function`, `out_buf`, and `out_count` must be valid non-null
 * pointers. If `data_in_count > 0`, `data_in` must point to at least `data_in_count`
 * valid `u16` words.
 */
MbusGoStatus mbus_go_serial_client_diagnostics(MbusGoSerialClient *handle,
                                               uint8_t unit_id,
                                               uint16_t sub_function,
                                               const uint16_t *data_in,
                                               uint16_t data_in_count,
                                               uint16_t *out_sub_function,
                                               uint16_t *out_buf,
                                               uint16_t out_buf_len,
                                               uint16_t *out_count);

/**
 * Reads one or more file records (FC14) over a serial connection.
 *
 * # Safety
 *
 * `handle`, `sub_reqs`, `out_buf`, and `out_count` must be valid non-null pointers.
 * `sub_reqs` must be valid for `sub_req_count` items.
 */
MbusGoStatus mbus_go_serial_client_read_file_record(MbusGoSerialClient *handle,
                                                    uint8_t unit_id,
                                                    const struct MbusGoSerialSubRequest *sub_reqs,
                                                    uint16_t sub_req_count,
                                                    uint16_t *out_buf,
                                                    uint16_t out_buf_len,
                                                    uint16_t *out_count);

/**
 * Writes one or more file records (FC15) over a serial connection.
 *
 * # Safety
 *
 * `handle` and `sub_reqs` must be valid non-null pointers. `sub_reqs` must be valid
 * for `sub_req_count` items. For each item, `data` must be valid for `data_len` words.
 */
MbusGoStatus mbus_go_serial_client_write_file_record(MbusGoSerialClient *handle,
                                                     uint8_t unit_id,
                                                     const struct MbusGoSerialSubRequest *sub_reqs,
                                                     uint16_t sub_req_count);

/**
 * Creates a new async TCP client targeting `host:port`.
 *
 * `host` must be a NUL-terminated UTF-8 string.  The returned pointer
 * must eventually be released with [`mbus_go_tcp_client_free`].  Returns
 * `null` if `host` is null, not valid UTF-8, or the underlying constructor
 * fails (for example because no Tokio runtime could be started).
 *
 * # Safety
 *
 * `host` must point to a valid NUL-terminated string for the duration of
 * this call.
 */
MbusGoTcpClient *mbus_go_tcp_client_new(const char *host, uint16_t port);

/**
 * Releases an `MbusGoTcpClient` previously returned from
 * [`mbus_go_tcp_client_new`].
 *
 * Drops the underlying `AsyncTcpClient`, which signals its background
 * Tokio task to exit.  No-op if `handle` is null.  Safe to call exactly
 * once per handle.
 *
 * # Safety
 *
 * `handle` must be either null or a pointer previously returned from
 * [`mbus_go_tcp_client_new`] that has not already been freed.
 */
void mbus_go_tcp_client_free(MbusGoTcpClient *handle);

/**
 * Establishes the TCP transport connection.
 *
 * Blocks the calling thread until the connection completes or fails.
 *
 * # Safety
 *
 * `handle` must be a non-null pointer previously returned from
 * [`mbus_go_tcp_client_new`] and still alive.
 */
MbusGoStatus mbus_go_tcp_client_connect(MbusGoTcpClient *handle);

/**
 * Closes the TCP transport gracefully.
 *
 * Drains any in-flight or queued requests with `ConnectionClosed`.  After
 * this call the client can be reconnected with
 * [`mbus_go_tcp_client_connect`].
 *
 * # Safety
 *
 * See [`mbus_go_tcp_client_connect`].
 */
MbusGoStatus mbus_go_tcp_client_disconnect(MbusGoTcpClient *handle);

/**
 * Sets a per-request timeout in milliseconds; `0` disables the timeout.
 *
 * # Safety
 *
 * See [`mbus_go_tcp_client_connect`].
 */
MbusGoStatus mbus_go_tcp_client_set_request_timeout_ms(MbusGoTcpClient *handle,
                                                       uint64_t timeout_ms);

/**
 * Returns `1` when there are requests in flight awaiting a response, `0`
 * otherwise; returns `0` when `handle` is null.
 *
 * # Safety
 *
 * See [`mbus_go_tcp_client_connect`].
 */
uint8_t mbus_go_tcp_client_has_pending_requests(MbusGoTcpClient *handle);

/**
 * Reads `quantity` holding registers (FC03) starting at `address` from
 * the given `unit_id` and copies them, in declaration order, into the
 * caller-supplied `out_buf` of length `out_buf_len` (in `u16` elements).
 *
 * On success writes the number of registers actually read into
 * `out_count` (which equals `quantity`) and returns `MbusOk`.
 *
 * Returns `MbusErrBufferTooSmall` if `out_buf_len < quantity`.
 *
 * # Safety
 *
 * * `handle` must be a valid client pointer.
 * * `out_buf` must point to writable storage for at least `out_buf_len`
 *   `u16` values.
 * * `out_count` must point to a writable `u16`.
 */
MbusGoStatus mbus_go_tcp_client_read_holding_registers(MbusGoTcpClient *handle,
                                                       uint8_t unit_id,
                                                       uint16_t address,
                                                       uint16_t quantity,
                                                       uint16_t *out_buf,
                                                       uint16_t out_buf_len,
                                                       uint16_t *out_count);

/**
 * Writes a single holding register (FC06).
 *
 * On success, writes the echoed `(address, value)` to `out_address` and
 * `out_value` if those pointers are non-null.
 *
 * # Safety
 *
 * * `handle` must be a valid client pointer.
 * * `out_address` and `out_value` may be null; if non-null they must
 *   point to writable `u16` storage.
 */
MbusGoStatus mbus_go_tcp_client_write_single_register(MbusGoTcpClient *handle,
                                                      uint8_t unit_id,
                                                      uint16_t address,
                                                      uint16_t value,
                                                      uint16_t *out_address,
                                                      uint16_t *out_value);

/**
 * Writes `quantity` holding registers (FC16) starting at `address`.
 *
 * `values` must point to `quantity` `u16` values in declaration order.
 *
 * On success, writes the echoed `(starting_address, quantity)` to
 * `out_address` and `out_quantity` if non-null.
 *
 * # Safety
 *
 * * `handle` must be a valid client pointer.
 * * `values` must point to at least `quantity` readable `u16` values.
 * * `out_address` and `out_quantity` may be null.
 */
MbusGoStatus mbus_go_tcp_client_write_multiple_registers(MbusGoTcpClient *handle,
                                                         uint8_t unit_id,
                                                         uint16_t address,
                                                         const uint16_t *values,
                                                         uint16_t quantity,
                                                         uint16_t *out_address,
                                                         uint16_t *out_quantity);

/**
 * Reads `quantity` coils (FC01) starting at `address` from `unit_id`.
 *
 * Writes bit-packed coil bytes (Modbus wire format, LSB-first) into `out_buf`.
 * `out_buf_len` is the buffer length in bytes; must be ≥ `ceil(quantity / 8)`.
 * On success writes the byte count to `out_count`.
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_read_coils(MbusGoTcpClient *handle,
                                           uint8_t unit_id,
                                           uint16_t address,
                                           uint16_t quantity,
                                           uint8_t *out_buf,
                                           uint16_t out_buf_len,
                                           uint16_t *out_count);

/**
 * Writes a single coil (FC05). `value != 0` means ON.
 *
 * On success, writes echoed address to `out_address` and value (`1`=ON, `0`=OFF)
 * to `out_value` if those pointers are non-null.
 *
 * # Safety
 *
 * `handle` must be a valid client pointer.
 */
MbusGoStatus mbus_go_tcp_client_write_single_coil(MbusGoTcpClient *handle,
                                                  uint8_t unit_id,
                                                  uint16_t address,
                                                  uint8_t value,
                                                  uint16_t *out_address,
                                                  uint8_t *out_value);

/**
 * Writes multiple coils (FC15) starting at `address`.
 *
 * `packed_coils` is Modbus bit-packed coil data (LSB-first). `byte_count` is
 * the number of bytes in `packed_coils`; `coil_count` is the number of coils.
 *
 * # Safety
 *
 * `handle` and `packed_coils` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_write_multiple_coils(MbusGoTcpClient *handle,
                                                     uint8_t unit_id,
                                                     uint16_t address,
                                                     const uint8_t *packed_coils,
                                                     uint16_t byte_count,
                                                     uint16_t coil_count,
                                                     uint16_t *out_address,
                                                     uint16_t *out_quantity);

/**
 * Reads `quantity` discrete inputs (FC02) starting at `address` from `unit_id`.
 *
 * Writes bit-packed bytes into `out_buf`. On success writes byte count to `out_count`.
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_read_discrete_inputs(MbusGoTcpClient *handle,
                                                     uint8_t unit_id,
                                                     uint16_t address,
                                                     uint16_t quantity,
                                                     uint8_t *out_buf,
                                                     uint16_t out_buf_len,
                                                     uint16_t *out_count);

/**
 * Reads `quantity` input registers (FC04) starting at `address` from `unit_id`.
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_read_input_registers(MbusGoTcpClient *handle,
                                                     uint8_t unit_id,
                                                     uint16_t address,
                                                     uint16_t quantity,
                                                     uint16_t *out_buf,
                                                     uint16_t out_buf_len,
                                                     uint16_t *out_count);

/**
 * Applies an AND/OR bitmask to a holding register (FC22).
 *
 * # Safety
 *
 * `handle` must be a valid client pointer.
 */
MbusGoStatus mbus_go_tcp_client_mask_write_register(MbusGoTcpClient *handle,
                                                    uint8_t unit_id,
                                                    uint16_t address,
                                                    uint16_t and_mask,
                                                    uint16_t or_mask);

/**
 * Reads and simultaneously writes multiple holding registers (FC23).
 *
 * # Safety
 *
 * `handle`, `write_values`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_read_write_multiple_registers(MbusGoTcpClient *handle,
                                                              uint8_t unit_id,
                                                              uint16_t read_address,
                                                              uint16_t read_quantity,
                                                              uint16_t write_address,
                                                              const uint16_t *write_values,
                                                              uint16_t write_quantity,
                                                              uint16_t *out_buf,
                                                              uint16_t out_buf_len,
                                                              uint16_t *out_count);

/**
 * Reads the FIFO queue (FC24) at `address` from `unit_id`.
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_read_fifo_queue(MbusGoTcpClient *handle,
                                                uint8_t unit_id,
                                                uint16_t address,
                                                uint16_t *out_buf,
                                                uint16_t out_buf_len,
                                                uint16_t *out_count);

/**
 * Reads the device exception status (FC07).
 *
 * # Safety
 *
 * `handle` and `out_status` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_read_exception_status(MbusGoTcpClient *handle,
                                                      uint8_t unit_id,
                                                      uint8_t *out_status);

/**
 * Reads the communication event counter (FC11).
 *
 * On success writes `status_word` and `event_count` to the respective out pointers.
 *
 * # Safety
 *
 * `handle`, `out_status`, and `out_event_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_get_comm_event_counter(MbusGoTcpClient *handle,
                                                       uint8_t unit_id,
                                                       uint16_t *out_status,
                                                       uint16_t *out_event_count);

/**
 * Reads the communication event log (FC12).
 *
 * Writes the raw event bytes into `out_buf`. On success writes byte count to `out_count`.
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_get_comm_event_log(MbusGoTcpClient *handle,
                                                   uint8_t unit_id,
                                                   uint8_t *out_buf,
                                                   uint16_t out_buf_len,
                                                   uint16_t *out_count);

/**
 * Reports the server identifier (FC17).
 *
 * Writes the raw server ID bytes into `out_buf`. On success writes byte count to `out_count`.
 *
 * # Safety
 *
 * `handle`, `out_buf`, and `out_count` must be valid non-null pointers.
 */
MbusGoStatus mbus_go_tcp_client_report_server_id(MbusGoTcpClient *handle,
                                                 uint8_t unit_id,
                                                 uint8_t *out_buf,
                                                 uint16_t out_buf_len,
                                                 uint16_t *out_count);

/**
 * Sends a Diagnostics (FC08) request.
 *
 * `sub_function` is the 16-bit sub-function code (see Modbus spec table).
 * `data_in` / `data_in_count` form the optional request data words (`null` / `0` for
 * sub-functions that carry no data such as *Return Query Data* with zero words).
 *
 * On success writes the echoed sub-function code to `out_sub_function` and the
 * echoed data words into `out_buf`, then sets `out_count` to the number of words written.
 *
 * # Safety
 *
 * `handle`, `out_sub_function`, `out_buf`, and `out_count` must be valid non-null pointers.
 * If `data_in_count > 0`, `data_in` must point to at least `data_in_count` valid `u16` words.
 */
MbusGoStatus mbus_go_tcp_client_diagnostics(MbusGoTcpClient *handle,
                                            uint8_t unit_id,
                                            uint16_t sub_function,
                                            const uint16_t *data_in,
                                            uint16_t data_in_count,
                                            uint16_t *out_sub_function,
                                            uint16_t *out_buf,
                                            uint16_t out_buf_len,
                                            uint16_t *out_count);

/**
 * Reads one or more file records (FC14).
 *
 * `sub_reqs` must point to `sub_req_count` [`MbusGoSubRequest`] descriptors in read mode
 * (i.e. each `data` field is `null` and `data_len` is `0`).
 *
 * On success the register words for all sub-requests are written contiguously into
 * `out_buf` (in the order of the sub-requests), and `out_count` is set to the total
 * number of words written.  The caller is expected to know the `record_length` of each
 * sub-request so it can split the flat buffer into per-record slices.
 *
 * # Safety
 *
 * `handle`, `sub_reqs`, `out_buf`, and `out_count` must be valid non-null pointers.
 * `sub_reqs` must be valid for `sub_req_count` items.
 */
MbusGoStatus mbus_go_tcp_client_read_file_record(MbusGoTcpClient *handle,
                                                 uint8_t unit_id,
                                                 const struct MbusGoSubRequest *sub_reqs,
                                                 uint16_t sub_req_count,
                                                 uint16_t *out_buf,
                                                 uint16_t out_buf_len,
                                                 uint16_t *out_count);

/**
 * Writes one or more file records (FC15).
 *
 * `sub_reqs` must point to `sub_req_count` [`MbusGoSubRequest`] descriptors in write mode
 * (i.e. each `data` field points to `data_len` valid `u16` words, and `record_length == data_len`).
 *
 * Returns `MbusOk` when all records have been written successfully.
 *
 * # Safety
 *
 * `handle` and `sub_reqs` must be valid non-null pointers.  `sub_reqs` must be valid for
 * `sub_req_count` items.  For each item, `data` must be valid for `data_len` words.
 */
MbusGoStatus mbus_go_tcp_client_write_file_record(MbusGoTcpClient *handle,
                                                  uint8_t unit_id,
                                                  const struct MbusGoSubRequest *sub_reqs,
                                                  uint16_t sub_req_count);

uintptr_t mbus_go_tcp_client_handle_size(void);

/**
 * Creates a new gateway handle.
 *
 * `host` is the NUL-terminated upstream bind address (e.g. `"0.0.0.0"`).
 * Returns `null` if `host` is null or not valid UTF-8.
 *
 * # Safety
 *
 * `host` must point to a valid NUL-terminated string.
 */
MbusGoTcpGateway *mbus_go_tcp_gateway_new(const char *host, uint16_t port);

/**
 * Destroys the gateway handle.
 *
 * Call [`mbus_go_tcp_gateway_stop`] first if the gateway is running.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`mbus_go_tcp_gateway_new`].
 */
void mbus_go_tcp_gateway_free(MbusGoTcpGateway *handle);

/**
 * Adds a TCP downstream and returns its zero-based channel index.
 *
 * Returns `u32::MAX` if `host` is null.
 *
 * # Safety
 *
 * `handle` and `host` must be valid non-null pointers.
 */
uint32_t mbus_go_tcp_gateway_add_downstream(MbusGoTcpGateway *handle,
                                            const char *host,
                                            uint16_t port);

/**
 * Routes a single unit ID to a downstream channel.
 *
 * Returns `MbusOk` on success, `MbusErrInvalidAddress` if `unit_id == 0` or
 * `channel >= registered_downstream_count`.
 *
 * # Safety
 *
 * `handle` must be a valid gateway pointer.
 */
MbusGoStatus mbus_go_tcp_gateway_add_unit_route(MbusGoTcpGateway *handle,
                                                uint8_t unit_id,
                                                uint32_t channel);

/**
 * Routes an inclusive unit-ID range `[min, max]` to a downstream channel.
 *
 * Returns `MbusErrInvalidAddress` if `min == 0`, `min > max`, or
 * `channel >= registered_downstream_count`.
 *
 * # Safety
 *
 * `handle` must be a valid gateway pointer.
 */
MbusGoStatus mbus_go_tcp_gateway_add_range_route(MbusGoTcpGateway *handle,
                                                 uint8_t unit_min,
                                                 uint8_t unit_max,
                                                 uint32_t channel);

/**
 * Starts the gateway on a new background OS thread.
 *
 * Connects all registered downstreams and begins forwarding requests.
 * Returns `MbusOk` immediately; the thread runs until
 * [`mbus_go_tcp_gateway_stop`] is called.
 *
 * Returns `MbusErrInvalidAddress` if no downstreams or no routes have been
 * registered.
 *
 * # Safety
 *
 * `handle` must be a valid gateway pointer.
 */
MbusGoStatus mbus_go_tcp_gateway_start(MbusGoTcpGateway *handle);

/**
 * Signals the running gateway to stop.
 *
 * # Safety
 *
 * `handle` must be a valid gateway pointer.
 */
void mbus_go_tcp_gateway_stop(MbusGoTcpGateway *handle);

/**
 * Creates a new TCP server handle.
 *
 * `host` is a NUL-terminated bind address (e.g. `"0.0.0.0"`).
 * `unit_id` is the Modbus unit ID to respond to.
 * `vtable` must remain valid for the lifetime of the server handle.
 *
 * Returns `null` if `host` or `vtable` is null, or if `unit_id` is invalid.
 *
 * # Safety
 *
 * * `host` must point to a valid NUL-terminated UTF-8 string.
 * * `vtable` must be non-null and the struct it points to must remain valid
 *   until [`mbus_go_tcp_server_free`] is called.
 */
MbusGoTcpServer *mbus_go_tcp_server_new(const char *host,
                                        uint16_t port,
                                        uint8_t unit_id,
                                        const struct MbusGoServerVtable *vtable);

/**
 * Destroys the server handle.
 *
 * Does **not** stop a running server — call [`mbus_go_tcp_server_stop`]
 * first, wait for the background thread to exit, then call this.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`mbus_go_tcp_server_new`].
 * Calling this more than once is undefined behaviour.
 */
void mbus_go_tcp_server_free(MbusGoTcpServer *handle);

/**
 * Starts the server on a new background OS thread.
 *
 * The thread blocks on `serve_with_shutdown` until [`mbus_go_tcp_server_stop`]
 * is called or a fatal error occurs.  Returns immediately to the caller.
 *
 * # Safety
 *
 * `handle` must be a valid server pointer.
 */
MbusGoStatus mbus_go_tcp_server_start(MbusGoTcpServer *handle);

/**
 * Signals the running server to stop.
 *
 * The background thread will finish in-flight sessions and then exit.
 *
 * # Safety
 *
 * `handle` must be a valid server pointer.
 */
void mbus_go_tcp_server_stop(MbusGoTcpServer *handle);

/**
 * Returns a static C string describing `status`.
 *
 * Equivalent to [`crate::c::error::mbus_status_str`] but exported with a
 * `mbus_go_` prefix so that it appears in the Go-only header.
 *
 * The returned pointer is always valid (points to a static string literal).
 * The caller must NOT free it.
 */
const char *mbus_go_status_str(MbusGoStatus status);

#endif  /* MODBUS_RS_GO_H */
