/* @generated by xtask gen-server-app. Do not edit manually. */
#ifndef MBUS_SERVER_APP_H
#define MBUS_SERVER_APP_H

#include <stdbool.h>
#include <stdint.h>
#include "modbus_rs_server.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum MbusHookStatus {
    MBUS_HOOK_OK = 0,
    MBUS_HOOK_ILLEGAL_DATA_ADDRESS = 1,
    MBUS_HOOK_ILLEGAL_DATA_VALUE = 2,
    MBUS_HOOK_DEVICE_FAILURE = 3
} MbusHookStatus;

/*
 * mbus_app_lock() / mbus_app_unlock()
 *
 * Protect concurrent access to the Modbus register state owned by Rust.
 * Called around every state mutation (Modbus writes and named push APIs).
 *
 * Implementation guidance:
 *   RTOS / multi-threaded : acquire/release a mutex or binary semaphore.
 *   Single-threaded bare-metal : leave both functions empty.
 *   Bare-metal with interrupts : enter/exit a critical section (disable/enable IRQ).
 *
 * Constraints:
 *   - NOT called before write-notification hooks (hooks run outside the lock).
 *     Do NOT call mbus_server_get_* or mbus_server_set_* from inside a hook.
 *   - Must not be called recursively (not reentrant).
 */
void mbus_app_lock(void);
void mbus_app_unlock(void);

/*
 * Write-notification hooks
 *
 * Called BEFORE the value is stored in Rust state.
 * Return MBUS_HOOK_OK to allow the write; any other value rejects it
 * and leaves the Rust state unchanged.
 * Called WITHOUT the lock — do not call mbus_server_get_* / set_* from here.
 */
MbusHookStatus app_on_write_alarm_ack(void* ctx, uint16_t address, uint8_t value);
MbusHookStatus app_on_write_pressure_limit(void* ctx, uint16_t address, uint16_t value);
MbusHookStatus app_on_write_pump_run(void* ctx, uint16_t address, uint8_t value);
MbusHookStatus app_on_write_speed_setpoint(void* ctx, uint16_t address, uint16_t value);

/*
 * Address-based register/coil access.
 * Useful for direct reads/writes outside the normal server flow.
 * Set functions call the write-notification hook before storing.
 */
MbusHookStatus mbus_server_get_coil(void* ctx, uint16_t address, uint8_t* out_value);
MbusHookStatus mbus_server_set_coil(void* ctx, uint16_t address, uint8_t value);
MbusHookStatus mbus_server_get_discrete_input(void* ctx, uint16_t address, uint8_t* out_value);
MbusHookStatus mbus_server_get_holding_register(void* ctx, uint16_t address, uint16_t* out_value);
MbusHookStatus mbus_server_set_holding_register(void* ctx, uint16_t address, uint16_t value);
MbusHookStatus mbus_server_get_input_register(void* ctx, uint16_t address, uint16_t* out_value);

/*
 * Server lifecycle — uses the standard mbus-ffi server infrastructure
 * (MbusTransportCallbacks, MbusServerHandlers, MbusServerConfig).
 *
 * 1. mbus_server_model_init()           — init Rust-owned register model
 * 2. mbus_server_default_handlers(ud)   — get populated MbusServerHandlers struct
 * 3. mbus_tcp_server_new(&t, &h, &cfg)  — create server via standard pool API
 * 4. mbus_tcp_server_connect(id)         — open transport
 * 5. mbus_tcp_server_poll(id)            — drive server state machine
 * 6. mbus_tcp_server_disconnect(id)      — close transport
 * 7. mbus_tcp_server_free(id)            — release pool slot
 */
void mbus_server_model_init(void);
struct MbusServerHandlers mbus_server_default_handlers(void *userdata);

/*
 * Generated handler callbacks.
 * These are automatically wired by mbus_server_default_handlers().
 * Declared here for users who want to build MbusServerHandlers manually.
 */
enum MbusServerExceptionCode mbus_gen_on_read_coils(
    struct MbusServerReadCoilsReq *req, void *userdata);
enum MbusServerExceptionCode mbus_gen_on_write_single_coil(
    const struct MbusServerWriteSingleCoilReq *req, void *userdata);
enum MbusServerExceptionCode mbus_gen_on_write_multiple_coils(
    const struct MbusServerWriteMultipleCoilsReq *req, void *userdata);
enum MbusServerExceptionCode mbus_gen_on_read_discrete_inputs(
    struct MbusServerReadDiscreteInputsReq *req, void *userdata);
enum MbusServerExceptionCode mbus_gen_on_read_holding_registers(
    struct MbusServerReadHoldingRegistersReq *req, void *userdata);
enum MbusServerExceptionCode mbus_gen_on_write_single_register(
    const struct MbusServerWriteSingleRegisterReq *req, void *userdata);
enum MbusServerExceptionCode mbus_gen_on_write_multiple_registers(
    const struct MbusServerWriteMultipleRegistersReq *req, void *userdata);
enum MbusServerExceptionCode mbus_gen_on_read_input_registers(
    struct MbusServerReadInputRegistersReq *req, void *userdata);

/*
 * Named field accessors — push/pull values from your application code.
 * Bypass write-notification hooks (app-side push, not a Modbus write).
 * Use to seed initial sensor values or read coil state from application code.
 */
void mbus_server_set_pump_run(uint8_t value);
MbusHookStatus mbus_server_get_pump_run(uint8_t* out_value);
void mbus_server_set_alarm_ack(uint8_t value);
MbusHookStatus mbus_server_get_alarm_ack(uint8_t* out_value);
void mbus_server_set_fault_active(uint8_t value);
MbusHookStatus mbus_server_get_fault_active(uint8_t* out_value);
void mbus_server_set_speed_setpoint(uint16_t value);
MbusHookStatus mbus_server_get_speed_setpoint(uint16_t* out_value);
void mbus_server_set_pressure_limit(uint16_t value);
MbusHookStatus mbus_server_get_pressure_limit(uint16_t* out_value);
void mbus_server_set_pressure_actual(uint16_t value);
MbusHookStatus mbus_server_get_pressure_actual(uint16_t* out_value);
void mbus_server_set_temperature_actual(uint16_t value);
MbusHookStatus mbus_server_get_temperature_actual(uint16_t* out_value);

/* Device: PumpController | Unit ID: 1 */

#ifdef __cplusplus
}
#endif

#endif /* MBUS_SERVER_APP_H */
