use mbus_core::transport::UnitIdOrSlaveAddr;
use mbus_server::{CoilsModel, HoldingRegistersModel, async_modbus_app};
use mbus_server_async::AsyncTcpServer;

#[derive(Debug, Default, Clone, CoilsModel)]
struct DemoCoils {
    #[coil(addr = 0)]
    relay_0: bool,
    #[coil(addr = 1)]
    relay_1: bool,
}

#[derive(Debug, Default, Clone, HoldingRegistersModel)]
struct DemoHolding {
    #[reg(addr = 0)]
    control: u16,
    #[reg(addr = 1)]
    setpoint: u16,
}

#[derive(Debug, Default, Clone)]
#[async_modbus_app(coils(coils), holding_registers(holding))]
struct DemoApp {
    coils: DemoCoils,
    holding: DemoHolding,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Macro-based quick-start: async handler impl is generated by #[async_modbus_app].
    let unit = UnitIdOrSlaveAddr::try_from(1u8)?;
    let _never = AsyncTcpServer::serve("0.0.0.0:1503", DemoApp::default(), unit).await?;
    Ok(())
}
