fn main() {
    println!("cargo::rustc-check-cfg=cfg(cbindgen)");
    println!("cargo::rustc-check-cfg=cfg(has_unwind)");

    // napi-build setup for Node.js bindings — generates the native addon registration glue.
    // Only called when the `nodejs` feature is active.
    if std::env::var("CARGO_FEATURE_NODEJS").is_ok() {
        napi_build::setup();
    }

    let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();

    // Link the C standard library for intrinsics (memcpy, memset, strlen, etc.)
    // These are generated by the compiler for no_std code and need libc implementations.
    // Windows MSVC has no "c" library; the CRT is linked automatically by rustc.
    let target_env = std::env::var("CARGO_CFG_TARGET_ENV").unwrap_or_default();
    if target_arch != "wasm32" && target_env != "msvc" {
        println!("cargo::rustc-link-lib=c");
    }

    // For macOS, suppress the undefined symbol error for _rust_eh_personality
    // by allowing undefined symbols in the dylib. The C side won't use unwinding anyway.
    #[cfg(target_os = "macos")]
    if target_arch != "wasm32" {
        println!("cargo::rustc-link-arg=-undefined");
        println!("cargo::rustc-link-arg=dynamic_lookup");
    }

    // Read CARGO_CFG_PANIC to detect if we are building with unwinding (e.g. during cargo test)
    if let Ok(panic_strat) = std::env::var("CARGO_CFG_PANIC")
        && panic_strat == "unwind"
    {
        println!("cargo::rustc-cfg=has_unwind");
    }

    // ── MBUS_MAX_TCP_CLIENTS ──────────────────────────────────────────────────
    //
    // Controls how many TCP client slots are pre-allocated in the static pool.
    // Default: 1. Valid range: [1, 255].
    // IDs 0x00xx index the TCP pool (high byte = 0x00).
    println!("cargo::rerun-if-env-changed=MBUS_MAX_TCP_CLIENTS");

    let max_tcp: usize = match std::env::var("MBUS_MAX_TCP_CLIENTS") {
        Ok(val) => {
            let n: usize = val.parse().unwrap_or_else(|_| {
                panic!("MBUS_MAX_TCP_CLIENTS must be a valid integer, got: \"{val}\"")
            });
            if n == 0 {
                panic!("MBUS_MAX_TCP_CLIENTS must be >= 1, got: 0");
            }
            if n > 255 {
                panic!("MBUS_MAX_TCP_CLIENTS must be <= 255, got: {n}");
            }
            n
        }
        Err(_) => 1, // default
    };

    // ── MBUS_MAX_SERIAL_CLIENTS ───────────────────────────────────────────────
    //
    // Controls how many Serial client slots are pre-allocated in each of the
    // RTU and ASCII sub-pools. Default: 1. Valid range: [1, 255].
    // IDs 0x01xx index the RTU pool, 0x02xx the ASCII pool.
    println!("cargo::rerun-if-env-changed=MBUS_MAX_SERIAL_CLIENTS");

    let max_serial: usize = match std::env::var("MBUS_MAX_SERIAL_CLIENTS") {
        Ok(val) => {
            let n: usize = val.parse().unwrap_or_else(|_| {
                panic!("MBUS_MAX_SERIAL_CLIENTS must be a valid integer, got: \"{val}\"")
            });
            if n == 0 {
                panic!("MBUS_MAX_SERIAL_CLIENTS must be >= 1, got: 0");
            }
            if n > 255 {
                panic!("MBUS_MAX_SERIAL_CLIENTS must be <= 255, got: {n}");
            }
            n
        }
        Err(_) => 1, // default
    };

    // ── MBUS_MAX_TCP_SERVERS ──────────────────────────────────────────────────
    //
    // Controls how many TCP server slots are pre-allocated in the static server pool.
    // Default: 1. Valid range: [1, 255].
    // IDs 0x10xx index the TCP server pool.
    println!("cargo::rerun-if-env-changed=MBUS_MAX_TCP_SERVERS");

    let max_tcp_servers: usize = match std::env::var("MBUS_MAX_TCP_SERVERS") {
        Ok(val) => {
            let n: usize = val.parse().unwrap_or_else(|_| {
                panic!("MBUS_MAX_TCP_SERVERS must be a valid integer, got: \"{val}\"")
            });
            if n == 0 {
                panic!("MBUS_MAX_TCP_SERVERS must be >= 1, got: 0");
            }
            if n > 255 {
                panic!("MBUS_MAX_TCP_SERVERS must be <= 255, got: {n}");
            }
            n
        }
        Err(_) => 1, // default
    };

    // ── MBUS_MAX_SERIAL_SERVERS ───────────────────────────────────────────────
    //
    // Controls how many Serial server slots are pre-allocated in the static server pool.
    // Default: 1. Valid range: [1, 255].
    // IDs 0x11xx index the Serial server pool.
    println!("cargo::rerun-if-env-changed=MBUS_MAX_SERIAL_SERVERS");

    let max_serial_servers: usize = match std::env::var("MBUS_MAX_SERIAL_SERVERS") {
        Ok(val) => {
            let n: usize = val.parse().unwrap_or_else(|_| {
                panic!("MBUS_MAX_SERIAL_SERVERS must be a valid integer, got: \"{val}\"")
            });
            if n == 0 {
                panic!("MBUS_MAX_SERIAL_SERVERS must be >= 1, got: 0");
            }
            if n > 255 {
                panic!("MBUS_MAX_SERIAL_SERVERS must be <= 255, got: {n}");
            }
            n
        }
        Err(_) => 1, // default
    };

    // ── MBUS_MAX_GATEWAYS ─────────────────────────────────────────────────────
    //
    // Controls how many gateway slots are pre-allocated in the static gateway pool.
    // Default: 1. Valid range: [1, 255].
    println!("cargo::rerun-if-env-changed=MBUS_MAX_GATEWAYS");

    let max_gateways: usize = match std::env::var("MBUS_MAX_GATEWAYS") {
        Ok(val) => {
            let n: usize = val.parse().unwrap_or_else(|_| {
                panic!("MBUS_MAX_GATEWAYS must be a valid integer, got: \"{val}\"")
            });
            if n == 0 {
                panic!("MBUS_MAX_GATEWAYS must be >= 1, got: 0");
            }
            if n > 255 {
                panic!("MBUS_MAX_GATEWAYS must be <= 255, got: {n}");
            }
            n
        }
        Err(_) => 1, // default
    };

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let config_path = format!("{out_dir}/pool_config.rs");
    std::fs::write(
        &config_path,
        format!(
            "/// Maximum number of TCP client slots (set via `MBUS_MAX_TCP_CLIENTS` env var, default 1).\n\
             #[allow(dead_code)]\n\
             pub(crate) const MAX_TCP_CLIENTS: usize = {max_tcp};\n\
             /// Maximum number of Serial client slots (set via `MBUS_MAX_SERIAL_CLIENTS` env var, default 1).\n\
             #[allow(dead_code)]\n\
             pub(crate) const MAX_SERIAL_CLIENTS: usize = {max_serial};\n\
             /// Maximum number of TCP server slots (set via `MBUS_MAX_TCP_SERVERS` env var, default 1).\n\
             #[allow(dead_code)]\n\
             pub(crate) const MAX_TCP_SERVERS: usize = {max_tcp_servers};\n\
             /// Maximum number of Serial server slots (set via `MBUS_MAX_SERIAL_SERVERS` env var, default 1).\n\
             #[allow(dead_code)]\n\
             pub(crate) const MAX_SERIAL_SERVERS: usize = {max_serial_servers};\n\
             /// Maximum number of gateway slots (set via `MBUS_MAX_GATEWAYS` env var, default 1).\n\
             #[allow(dead_code)]\n\
             pub(crate) const MAX_GATEWAYS: usize = {max_gateways};\n"
        ),
    )
    .expect("failed to write pool_config.rs");

    // ── cbindgen ──────────────────────────────────────────────────────────────

    // Only run cbindgen when the `c`, `c-server`, `c-gateway`, `dotnet`, or `go` feature is enabled.
    if std::env::var("CARGO_FEATURE_C").is_err()
        && std::env::var("CARGO_FEATURE_C_SERVER").is_err()
        && std::env::var("CARGO_FEATURE_C_GATEWAY").is_err()
        && std::env::var("CARGO_FEATURE_DOTNET").is_err()
        && std::env::var("CARGO_FEATURE_GO").is_err()
    {
        return;
    }

    let has_tcp = std::env::var("CARGO_FEATURE_NETWORK_TCP").is_ok();
    let has_serial_rtu = std::env::var("CARGO_FEATURE_SERIAL_RTU").is_ok();
    let has_serial_ascii = std::env::var("CARGO_FEATURE_SERIAL_ASCII").is_ok();
    let has_serial = has_serial_rtu || has_serial_ascii;

    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let workspace_root = std::path::Path::new(&crate_dir)
        .parent()
        .expect("CARGO_MANIFEST_DIR has no parent")
        .to_path_buf();
    let target_dir = std::env::var("CARGO_TARGET_DIR")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|_| workspace_root.join("target"));
    let include_dir = target_dir.join("mbus-ffi/include");

    // Rerun cbindgen if the configs or any source file changes.
    println!("cargo::rerun-if-changed=cbindgen_client.toml");
    println!("cargo::rerun-if-changed=cbindgen_server.toml");
    println!("cargo::rerun-if-changed=cbindgen_gateway.toml");
    println!("cargo::rerun-if-changed=cbindgen_dotnet.toml");
    println!("cargo::rerun-if-changed=cbindgen_go.toml");
    println!("cargo::rerun-if-changed=src");
    std::fs::create_dir_all(&include_dir).expect("failed to create target include directory");

    if std::env::var("CARGO_FEATURE_C").is_ok() {
        let output_file = include_dir.join("modbus_rs_client.h");
        let config_path = format!("{crate_dir}/cbindgen_client.toml");
        let config = cbindgen::Config::from_file(&config_path)
            .unwrap_or_else(|err| panic!("failed to parse {config_path}: {err}"));

        cbindgen::Builder::new()
            .with_crate(&crate_dir)
            .with_language(cbindgen::Language::C)
            .with_define("feature", "c", "MBUS_FEATURE_C")
            .with_define("feature", "coils", "MBUS_FEATURE_COILS")
            .with_define("feature", "registers", "MBUS_FEATURE_REGISTERS")
            .with_define("feature", "discrete-inputs", "MBUS_FEATURE_DISCRETE_INPUTS")
            .with_define("feature", "fifo", "MBUS_FEATURE_FIFO")
            .with_define("feature", "file-record", "MBUS_FEATURE_FILE_RECORD")
            .with_define("feature", "diagnostics", "MBUS_FEATURE_DIAGNOSTICS")
            .with_config(config)
            .generate()
            .expect("cbindgen failed to generate C header")
            .write_to_file(&output_file);

        prune_header(&output_file, |decl| {
            let code = strip_comments(decl);
            let trimmed = code.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                return true;
            }
            let mut mbus_seen = false;
            let mut mbus_kept = true;
            for tok in code.split(|c: char| !(c.is_alphanumeric() || c == '_')) {
                // Catch both function names (`mbus_...`) and struct/enum names (`Mbus...`)
                if tok.starts_with("mbus_") || tok.starts_with("Mbus") {
                    mbus_seen = true;
                    // Reject sibling API surface tokens.
                    if tok.starts_with("mbus_server_")
                        || tok.starts_with("mbus_tcp_server_")
                        || tok.starts_with("mbus_serial_server_")
                        || tok.starts_with("mbus_gateway_")
                        || tok.starts_with("mbus_tcp_gateway_")
                        || tok.starts_with("mbus_serial_gateway_")
                        || tok.starts_with("mbus_go_")
                        || tok.starts_with("MbusGo")
                        || tok.starts_with("mbus_dn_")
                        || tok.starts_with("MbusDn")
                    {
                        mbus_kept = false;
                    }
                    // Dynamically reject TCP/Serial tokens if the feature is disabled.
                    if !has_tcp && (tok.starts_with("mbus_tcp_") || tok.starts_with("MbusTcp")) {
                        mbus_kept = false;
                    }
                    if !has_serial
                        && (tok.starts_with("mbus_serial_") || tok.starts_with("MbusSerial"))
                    {
                        mbus_kept = false;
                    }
                    // Dynamically reject RTU/ASCII specific tokens if the corresponding feature is disabled.
                    if !has_serial_rtu && (tok.contains("_rtu") || tok.contains("Rtu")) {
                        mbus_kept = false;
                    }
                    if !has_serial_ascii && (tok.contains("_ascii") || tok.contains("Ascii")) {
                        mbus_kept = false;
                    }
                }
            }
            if mbus_seen {
                return mbus_kept;
            }
            true
        });
    }

    if std::env::var("CARGO_FEATURE_C_SERVER").is_ok() {
        let output_file = include_dir.join("modbus_rs_server.h");
        let config_path = format!("{crate_dir}/cbindgen_server.toml");
        let config = cbindgen::Config::from_file(&config_path)
            .unwrap_or_else(|err| panic!("failed to parse {config_path}: {err}"));

        cbindgen::Builder::new()
            .with_crate(&crate_dir)
            .with_language(cbindgen::Language::C)
            .with_define("feature", "c-server", "MBUS_FEATURE_C_SERVER")
            .with_define("feature", "network-tcp", "MBUS_FEATURE_NETWORK_TCP")
            .with_define("feature", "serial-rtu", "MBUS_FEATURE_SERIAL_RTU")
            .with_define("feature", "serial-ascii", "MBUS_FEATURE_SERIAL_ASCII")
            .with_config(config)
            .generate()
            .expect("cbindgen failed to generate server C header")
            .write_to_file(&output_file);

        prune_header(&output_file, |decl| {
            let code = strip_comments(decl);
            let trimmed = code.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                return true;
            }
            let mut mbus_seen = false;
            let mut mbus_kept = true;
            for tok in code.split(|c: char| !(c.is_alphanumeric() || c == '_')) {
                // Catch both function names (`mbus_...`) and struct/enum names (`Mbus...`)
                if tok.starts_with("mbus_") || tok.starts_with("Mbus") {
                    mbus_seen = true;
                    // Reject sibling API surface tokens.
                    if tok.starts_with("mbus_client_")
                        || tok.starts_with("mbus_tcp_client_")
                        || tok.starts_with("mbus_serial_client_")
                        || tok.starts_with("mbus_gateway_")
                        || tok.starts_with("mbus_tcp_gateway_")
                        || tok.starts_with("mbus_serial_gateway_")
                        || tok.starts_with("mbus_go_")
                        || tok.starts_with("MbusGo")
                        || tok.starts_with("mbus_dn_")
                        || tok.starts_with("MbusDn")
                    {
                        mbus_kept = false;
                    }
                    // Dynamically reject TCP/Serial tokens if the feature is disabled.
                    if !has_tcp && (tok.starts_with("mbus_tcp_") || tok.starts_with("MbusTcp")) {
                        mbus_kept = false;
                    }
                    if !has_serial
                        && (tok.starts_with("mbus_serial_") || tok.starts_with("MbusSerial"))
                    {
                        mbus_kept = false;
                    }
                    // Dynamically reject RTU/ASCII specific tokens if the corresponding feature is disabled.
                    if !has_serial_rtu && (tok.contains("_rtu") || tok.contains("Rtu")) {
                        mbus_kept = false;
                    }
                    if !has_serial_ascii && (tok.contains("_ascii") || tok.contains("Ascii")) {
                        mbus_kept = false;
                    }
                }
            }
            if mbus_seen {
                return mbus_kept;
            }
            true
        });

        // ── Server app code generation ────────────────────────────────────────
        //
        // Reads a user-supplied YAML config and generates the Rust dispatcher
        // (model structs + FFI exports) into OUT_DIR/generated_server.rs.
        // The source file is then pulled in via `include!` in server_gen/mod.rs.
        //
        // Set MBUS_SERVER_APP_CONFIG to the path of your YAML config file:
        //   MBUS_SERVER_APP_CONFIG=/path/to/server_app.yaml cargo build -p mbus-ffi --features c-server
        println!("cargo::rerun-if-env-changed=MBUS_SERVER_APP_CONFIG");
        // When MBUS_SERVER_APP_CONFIG is not set, fall back to the bundled
        // example YAML if it is present (i.e. we are inside the workspace).
        // This makes `cargo test --workspace --all-features` work without
        // extra environment setup.  A warning is emitted so the fallback is
        // never silent.  Production builds that extracted only `mbus-ffi`
        // won't have the example file and will still get the clear panic.
        let example_yaml = std::path::Path::new(&crate_dir)
            .join("examples/c_server_demo_yaml/mbus_server_app.example.yaml");
        let app_config_raw = std::env::var("MBUS_SERVER_APP_CONFIG").unwrap_or_else(|_| {
            if example_yaml.exists() {
                example_yaml.to_string_lossy().into_owned()
            } else {
                panic!(
                    "\n\nError: MBUS_SERVER_APP_CONFIG is not set.\n\
                     The `c-server` feature requires a YAML device config to generate the server app layer.\n\
                     Set the environment variable to the path of your server_app.yaml:\n\
                     \n\
                     MBUS_SERVER_APP_CONFIG=/path/to/server_app.yaml cargo build -p mbus-ffi --features c-server\n\
                     \n\
                     See mbus-ffi/examples/c_server_demo_yaml/mbus_server_app.example.yaml for the format.\n"
                )
            }
        });
        // Resolve relative paths against the workspace root (parent of the crate dir).
        let app_config_path = {
            let p = std::path::Path::new(&app_config_raw);
            if p.is_absolute() {
                p.to_path_buf()
            } else {
                std::path::Path::new(&crate_dir)
                    .parent()
                    .expect("CARGO_MANIFEST_DIR has no parent")
                    .join(p)
            }
        };
        println!("cargo::rerun-if-changed={}", app_config_path.display());
        let app_config_text = std::fs::read_to_string(&app_config_path).unwrap_or_else(|e| {
            panic!(
                "failed to read MBUS_SERVER_APP_CONFIG={}: {e}",
                app_config_path.display()
            )
        });
        let mut app_config = mbus_codegen::parse_yaml(&app_config_text)
            .unwrap_or_else(|e| panic!("invalid YAML in {}: {e}", app_config_path.display()));
        mbus_codegen::validate_config(&app_config)
            .unwrap_or_else(|e| panic!("config error in {}: {e}", app_config_path.display()));

        // Feature-gate memory sections: clear YAML sections whose corresponding
        // Cargo features are not enabled, so the generated code never references
        // types / trait impls behind disabled `#[cfg(feature = "...")]` gates.
        if std::env::var("CARGO_FEATURE_COILS").is_err() && !app_config.memory_map.coils.is_empty()
        {
            println!(
                "cargo::warning=YAML defines {} coil(s) but the `coils` feature is not enabled; coil handlers will NOT be compiled.",
                app_config.memory_map.coils.len()
            );
            app_config.memory_map.coils.clear();
        }
        if std::env::var("CARGO_FEATURE_DISCRETE_INPUTS").is_err()
            && !app_config.memory_map.discrete_inputs.is_empty()
        {
            println!(
                "cargo::warning=YAML defines {} discrete input(s) but the `discrete-inputs` feature is not enabled; discrete-input handlers will NOT be compiled.",
                app_config.memory_map.discrete_inputs.len()
            );
            app_config.memory_map.discrete_inputs.clear();
        }
        if std::env::var("CARGO_FEATURE_REGISTERS").is_err() {
            if !app_config.memory_map.holding_registers.is_empty() {
                println!(
                    "cargo::warning=YAML defines {} holding register(s) but the `registers` feature is not enabled; holding-register handlers will NOT be compiled.",
                    app_config.memory_map.holding_registers.len()
                );
                app_config.memory_map.holding_registers.clear();
            }
            if !app_config.memory_map.input_registers.is_empty() {
                println!(
                    "cargo::warning=YAML defines {} input register(s) but the `registers` feature is not enabled; input-register handlers will NOT be compiled.",
                    app_config.memory_map.input_registers.len()
                );
                app_config.memory_map.input_registers.clear();
            }
        }

        let rust_src = mbus_codegen::render_rust_dispatcher(&app_config);
        let gen_path = format!("{out_dir}/generated_server.rs");
        std::fs::write(&gen_path, rust_src)
            .unwrap_or_else(|e| panic!("failed to write {gen_path}: {e}"));
    }

    if std::env::var("CARGO_FEATURE_C_GATEWAY").is_ok() {
        let output_file = include_dir.join("modbus_rs_gateway.h");
        let config_path = format!("{crate_dir}/cbindgen_gateway.toml");
        let config = cbindgen::Config::from_file(&config_path)
            .unwrap_or_else(|err| panic!("failed to parse {config_path}: {err}"));

        cbindgen::Builder::new()
            .with_crate(&crate_dir)
            .with_language(cbindgen::Language::C)
            .with_define("feature", "c", "MBUS_FEATURE_C")
            .with_define("feature", "c-server", "MBUS_FEATURE_C_SERVER")
            .with_define("feature", "c-gateway", "MBUS_FEATURE_C_GATEWAY")
            .with_define("feature", "coils", "MBUS_FEATURE_COILS")
            .with_define("feature", "registers", "MBUS_FEATURE_REGISTERS")
            .with_define("feature", "discrete-inputs", "MBUS_FEATURE_DISCRETE_INPUTS")
            .with_define("feature", "fifo", "MBUS_FEATURE_FIFO")
            .with_define("feature", "file-record", "MBUS_FEATURE_FILE_RECORD")
            .with_define("feature", "diagnostics", "MBUS_FEATURE_DIAGNOSTICS")
            .with_config(config)
            .generate()
            .expect("cbindgen failed to generate gateway C header")
            .write_to_file(&output_file);

        prune_header(&output_file, |decl| {
            let code = strip_comments(decl);
            let trimmed = code.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                return true;
            }
            let mut mbus_seen = false;
            let mut mbus_kept = true;
            for tok in code.split(|c: char| !(c.is_alphanumeric() || c == '_')) {
                // Catch both function names (`mbus_...`) and struct/enum names (`Mbus...`)
                if tok.starts_with("mbus_") || tok.starts_with("Mbus") {
                    mbus_seen = true;
                    // Reject sibling API surface tokens.
                    if tok.starts_with("mbus_client_")
                        || tok.starts_with("mbus_tcp_client_")
                        || tok.starts_with("mbus_serial_client_")
                        || tok.starts_with("mbus_server_")
                        || tok.starts_with("mbus_tcp_server_")
                        || tok.starts_with("mbus_serial_server_")
                        || tok.starts_with("mbus_go_")
                        || tok.starts_with("MbusGo")
                        || tok.starts_with("mbus_dn_")
                        || tok.starts_with("MbusDn")
                    {
                        mbus_kept = false;
                    }
                    // Dynamically reject TCP/Serial tokens if the feature is disabled.
                    if !has_tcp && (tok.starts_with("mbus_tcp_") || tok.starts_with("MbusTcp")) {
                        mbus_kept = false;
                    }
                    if !has_serial
                        && (tok.starts_with("mbus_serial_") || tok.starts_with("MbusSerial"))
                    {
                        mbus_kept = false;
                    }
                    // Dynamically reject RTU/ASCII specific tokens if the corresponding feature is disabled.
                    if !has_serial_rtu && (tok.contains("_rtu") || tok.contains("Rtu")) {
                        mbus_kept = false;
                    }
                    if !has_serial_ascii && (tok.contains("_ascii") || tok.contains("Ascii")) {
                        mbus_kept = false;
                    }
                }
            }
            if mbus_seen {
                return mbus_kept;
            }
            true
        });
    }

    if std::env::var("CARGO_FEATURE_DOTNET").is_ok() {
        let output_file = include_dir.join("modbus_rs_dotnet.h");
        let config_path = format!("{crate_dir}/cbindgen_dotnet.toml");
        let config = cbindgen::Config::from_file(&config_path)
            .unwrap_or_else(|err| panic!("failed to parse {config_path}: {err}"));

        cbindgen::Builder::new()
            .with_crate(&crate_dir)
            .with_language(cbindgen::Language::C)
            .with_define("feature", "dotnet", "MBUS_FEATURE_DOTNET")
            .with_define("feature", "coils", "MBUS_FEATURE_COILS")
            .with_define("feature", "registers", "MBUS_FEATURE_REGISTERS")
            .with_define("feature", "discrete-inputs", "MBUS_FEATURE_DISCRETE_INPUTS")
            .with_config(config)
            .generate()
            .expect("cbindgen failed to generate .NET C header")
            .write_to_file(&output_file);

        prune_header(&output_file, |decl| {
            let code = strip_comments(decl);
            let trimmed = code.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                return true;
            }
            let mut mbus_seen = false;
            let mut mbus_kept = true;
            for tok in code.split(|c: char| !(c.is_alphanumeric() || c == '_')) {
                // Catch both function names (`mbus_...`) and struct/enum names (`Mbus...`)
                if tok.starts_with("mbus_") || tok.starts_with("Mbus") {
                    mbus_seen = true;
                    // Explicitly reject all non-.NET APIs so that generic shared models remain.
                    if tok.starts_with("mbus_client_")
                        || tok.starts_with("mbus_tcp_client_")
                        || tok.starts_with("mbus_serial_client_")
                        || tok.starts_with("mbus_server_")
                        || tok.starts_with("mbus_tcp_server_")
                        || tok.starts_with("mbus_serial_server_")
                        || tok.starts_with("mbus_gateway_")
                        || tok.starts_with("mbus_tcp_gateway_")
                        || tok.starts_with("mbus_serial_gateway_")
                        || tok.starts_with("mbus_go_")
                        || tok.starts_with("MbusGo")
                    {
                        mbus_kept = false;
                    }
                    // Dynamically reject TCP/Serial tokens if the feature is disabled.
                    if !has_tcp && (tok.starts_with("mbus_tcp_") || tok.starts_with("MbusTcp")) {
                        mbus_kept = false;
                    }
                    if !has_serial
                        && (tok.starts_with("mbus_serial_") || tok.starts_with("MbusSerial"))
                    {
                        mbus_kept = false;
                    }
                    // Dynamically reject RTU/ASCII specific tokens if the corresponding feature is disabled.
                    if !has_serial_rtu && (tok.contains("_rtu") || tok.contains("Rtu")) {
                        mbus_kept = false;
                    }
                    if !has_serial_ascii && (tok.contains("_ascii") || tok.contains("Ascii")) {
                        mbus_kept = false;
                    }
                }
            }
            if mbus_seen {
                return mbus_kept;
            }
            true
        });
    }

    if std::env::var("CARGO_FEATURE_GO").is_ok() {
        let output_file = include_dir.join("modbus_rs_go.h");
        let config_path = format!("{crate_dir}/cbindgen_go.toml");
        let config = cbindgen::Config::from_file(&config_path)
            .unwrap_or_else(|err| panic!("failed to parse {config_path}: {err}"));

        cbindgen::Builder::new()
            .with_crate(&crate_dir)
            .with_language(cbindgen::Language::C)
            .with_define("feature", "go", "MBUS_FEATURE_GO")
            .with_define("feature", "coils", "MBUS_FEATURE_COILS")
            .with_define("feature", "registers", "MBUS_FEATURE_REGISTERS")
            .with_define("feature", "discrete-inputs", "MBUS_FEATURE_DISCRETE_INPUTS")
            .with_define("feature", "fifo", "MBUS_FEATURE_FIFO")
            .with_define("feature", "file-record", "MBUS_FEATURE_FILE_RECORD")
            .with_define("feature", "diagnostics", "MBUS_FEATURE_DIAGNOSTICS")
            .with_config(config)
            .generate()
            .expect("cbindgen failed to generate Go C header")
            .write_to_file(&output_file);

        // ── Post-process: strip leaked sibling-binding declarations ──────
        //
        // cbindgen does not fully honour module-level `#[cfg(feature)]`
        // gates and ends up emitting C/dotnet function declarations
        // (e.g. `mbus_coils_value`, `mbus_dn_serial_client_*`) into the
        // Go header. cgo must compile the entire header, so any decl
        // that references a type we do not forward-declare causes a
        // build failure. Drop every `mbus_*` declaration whose name is
        // NOT in the Go ABI surface (i.e. `mbus_go_*`).
        prune_header(&output_file, |decl| {
            let code = strip_comments(decl);
            let trimmed = code.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                return true;
            }
            let mut mbus_seen = false;
            let mut mbus_kept = true;
            
            // Check for stray global variable definitions that cbindgen incorrectly generates
            // These look like: "uint16_t record_number;" or "const uint16_t *data;"
            // They should be struct fields but cbindgen puts them at top level
            let trimmed_lower = trimmed.to_lowercase();
            if (trimmed_lower.starts_with("uint") || trimmed_lower.starts_with("int") || trimmed_lower.starts_with("const")) 
                && trimmed.ends_with(';')
                && !trimmed.contains("typedef")
                && !trimmed.contains('{')
                && !trimmed.contains('}')
                && !trimmed.contains("mbus_")
                && !trimmed.contains("Mbus") {
                // This looks like a stray global variable definition
                return false;
            }
            
            for tok in code.split(|c: char| !(c.is_alphanumeric() || c == '_')) {
                // Catch both function names (`mbus_...`) and struct/enum names (`Mbus...`)
                if tok.starts_with("mbus_") || tok.starts_with("Mbus") {
                    mbus_seen = true;
                    // Explicitly reject all non-Go APIs so that generic shared models remain.
                    if tok.starts_with("mbus_client_")
                        || tok.starts_with("mbus_tcp_client_")
                        || tok.starts_with("mbus_serial_client_")
                        || tok.starts_with("mbus_server_")
                        || tok.starts_with("mbus_tcp_server_")
                        || tok.starts_with("mbus_serial_server_")
                        || tok.starts_with("mbus_gateway_")
                        || tok.starts_with("mbus_tcp_gateway_")
                        || tok.starts_with("mbus_serial_gateway_")
                        || tok.starts_with("mbus_dn_")
                        || tok.starts_with("MbusDn")
                    {
                        mbus_kept = false;
                    }
                    // Dynamically reject TCP/Serial tokens if the feature is disabled.
                    if !has_tcp && (tok.starts_with("mbus_tcp_") || tok.starts_with("MbusTcp")) {
                        mbus_kept = false;
                    }
                    if !has_serial
                        && (tok.starts_with("mbus_serial_") || tok.starts_with("MbusSerial"))
                    {
                        mbus_kept = false;
                    }
                    // Dynamically reject RTU/ASCII specific tokens if the corresponding feature is disabled.
                    if !has_serial_rtu && (tok.contains("_rtu") || tok.contains("Rtu")) {
                        mbus_kept = false;
                    }
                    if !has_serial_ascii && (tok.contains("_ascii") || tok.contains("Ascii")) {
                        mbus_kept = false;
                    }
                }
            }
            if mbus_seen {
                return mbus_kept;
            }
            true
        });

        // Fix MbusGoServerVtable definition - cbindgen doesn't handle conditional fields correctly
        let header_content = match std::fs::read_to_string(&output_file) {
            Ok(content) => content,
            Err(e) => {
                println!("cargo::warning=cannot read {} for vtable fix: {e}", output_file.display());
                return;
            }
        };
        
        // Replace the incomplete MbusGoServerVtable definition with a complete one
        let complete_vtable = r#"typedef struct MbusGoServerVtable {
    void *ctx;
    int32_t (*read_coils)(void*, uint16_t, uint16_t, uint8_t*, uint16_t*);
    int32_t (*write_single_coil)(void*, uint16_t, uint8_t);
    int32_t (*write_multiple_coils)(void*, uint16_t, const uint8_t*, uint16_t, uint16_t);
    int32_t (*read_discrete_inputs)(void*, uint16_t, uint16_t, uint8_t*, uint16_t*);
    int32_t (*read_holding_registers)(void*, uint16_t, uint16_t, uint16_t*, uint16_t*);
    int32_t (*read_input_registers)(void*, uint16_t, uint16_t, uint16_t*, uint16_t*);
    int32_t (*write_single_register)(void*, uint16_t, uint16_t);
    int32_t (*write_multiple_registers)(void*, uint16_t, const uint8_t*, uint16_t);
    int32_t (*mask_write_register)(void*, uint16_t, uint16_t, uint16_t);
    int32_t (*read_write_multiple_registers)(void*, uint16_t, uint16_t, uint16_t, const uint16_t*, uint16_t*);
    int32_t (*read_fifo_queue)(void*, uint16_t, uint16_t*, uint16_t*);
    int32_t (*read_file_record)(void*, uint16_t, uint16_t, uint16_t, uint16_t*, uint16_t*);
    int32_t (*write_file_record)(void*, uint16_t, uint16_t, uint16_t, const uint16_t*);
    int32_t (*read_exception_status)(void*, uint8_t*);
    int32_t (*diagnostics)(void*, uint16_t, uint16_t, uint16_t*, uint16_t*);
    int32_t (*get_comm_event_counter)(void*, uint16_t*, uint16_t*);
    int32_t (*get_comm_event_log)(void*, uint8_t*, uint16_t*);
    int32_t (*report_server_id)(void*, uint8_t*, uint16_t*);
} MbusGoServerVtable;"#;
        
        // Find and replace the MbusGoServerVtable definition
        // We need to find the pattern: "typedef struct MbusGoServerVtable {" ... "} MbusGoServerVtable;"
        // But there might be two definitions (one from after_includes, one generated).
        // We'll replace all occurrences.
        let mut fixed_content = header_content.clone();
        let mut replaced = false;
        
        // Simple pattern matching - find "typedef struct MbusGoServerVtable" and replace until "} MbusGoServerVtable;"
        let start_pattern = "typedef struct MbusGoServerVtable";
        let end_pattern = "} MbusGoServerVtable;";
        
        if let Some(start_idx) = fixed_content.find(start_pattern)
            && let Some(end_idx) = fixed_content[start_idx..].find(end_pattern) {
                let end_idx = start_idx + end_idx + end_pattern.len();
                fixed_content.replace_range(start_idx..end_idx, complete_vtable);
                replaced = true;
        }
        
        if replaced {
            if let Err(e) = std::fs::write(&output_file, fixed_content) {
                println!("cargo::warning=failed to write fixed header {}: {e}", output_file.display());
            }
        } else {
            println!("cargo::warning=could not find MbusGoServerVtable definition to fix in {}", output_file.display());
        }

        // Mirror the freshly-generated header into the Go module so
        // `go build` can find it without the user having to run a
        // separate copy step.  This keeps the vendored header in
        // `mbus-ffi/go/internal/cgo/include/` in sync with the Rust FFI
        // surface on every Cargo build.
        let go_include_dir = std::path::Path::new(&crate_dir)
            .join("go")
            .join("internal")
            .join("cgo")
            .join("include");
        if go_include_dir.exists() {
            let dst = go_include_dir.join("modbus_rs_go.h");
            if let Err(e) = std::fs::copy(&output_file, &dst) {
                println!(
                    "cargo::warning=failed to copy modbus_rs_go.h into Go module ({}): {e}",
                    dst.display()
                );
            }
        }
    }
}

/// Strip every top-level declaration from the generated header that
/// does not match the target's ABI surface.
///
/// We do this because cbindgen can leak declarations from sibling
/// FFI modules (the C, .NET and WASM bindings) even when their cfg
/// gates are disabled.
fn prune_header<F>(path: &std::path::Path, should_keep: F)
where
    F: Fn(&str) -> bool,
{
    let original = match std::fs::read_to_string(path) {
        Ok(s) => s,
        Err(e) => {
            println!(
                "cargo::warning=cannot read {} for pruning: {e}",
                path.display()
            );
            return;
        }
    };

    let mut chunks = Vec::new();
    let mut current_chunk = String::new();
    let mut chars = original.chars().peekable();

    let mut in_line_comment = false;
    let mut in_block_comment = false;
    let mut in_string = false;
    let mut in_char = false;
    let mut in_directive = false;

    while let Some(c) = chars.next() {
        current_chunk.push(c);

        if c == '\\' {
            if let Some(next) = chars.next() {
                current_chunk.push(next);
            }
            continue;
        }

        if in_line_comment {
            if c == '\n' {
                in_line_comment = false;
            }
            continue;
        }

        if in_block_comment {
            if c == '*'
                && let Some(&'/') = chars.peek()
            {
                current_chunk.push(chars.next().unwrap());
                in_block_comment = false;
            }
            continue;
        }

        if in_string {
            if c == '"' {
                in_string = false;
            }
            continue;
        }

        if in_char {
            if c == '\'' {
                in_char = false;
            }
            continue;
        }

        if in_directive {
            if c == '\n' {
                in_directive = false;
                chunks.push(std::mem::take(&mut current_chunk));
            }
            continue;
        }

        match c {
            '/' => {
                if let Some(&'/') = chars.peek() {
                    current_chunk.push(chars.next().unwrap());
                    in_line_comment = true;
                } else if let Some(&'*') = chars.peek() {
                    current_chunk.push(chars.next().unwrap());
                    in_block_comment = true;
                }
            }
            '"' => in_string = true,
            '\'' => in_char = true,
            '#' => {
                in_directive = true;
            }
            ';' => {
                chunks.push(std::mem::take(&mut current_chunk));
            }
            _ => {}
        }
    }

    if !current_chunk.is_empty() {
        chunks.push(current_chunk);
    }

    let mut output = String::with_capacity(original.len());
    for chunk in chunks {
        let code = strip_comments(&chunk);
        if should_keep(&code) {
            output.push_str(&chunk);
        }
    }

    // Post-process to fix MbusGoServerVtable for Go bindings
    // cbindgen doesn't handle #[cfg(feature = "...")] fields correctly in #[repr(C)] structs
    // There are TWO vtable definitions in the header:
    // 1. Manual definition at the top (from cbindgen_go.toml after_includes) - has all fields
    // 2. cbindgen-generated definition later - has only ctx field
    // We need to remove the second (incomplete) definition to avoid duplicate struct errors
    if path.to_string_lossy().contains("modbus_rs_go.h") {
        // Find all occurrences of "typedef struct MbusGoServerVtable"
        let mut positions = Vec::new();
        let mut search_pos = 0;
        let pattern = "typedef struct MbusGoServerVtable";
        
        while let Some(pos) = output[search_pos..].find(pattern) {
            let absolute_pos = search_pos + pos;
            positions.push(absolute_pos);
            search_pos = absolute_pos + pattern.len();
        }
        
        // If there are 2 or more occurrences, remove all but the first
        if positions.len() >= 2 {
            // Find the end of the second definition
            let second_start = positions[1];
            let end_pattern = "} MbusGoServerVtable;";
            if let Some(end_idx) = output[second_start..].find(end_pattern) {
                let second_end = second_start + end_idx + end_pattern.len();
                // Remove the second definition
                output.replace_range(second_start..second_end, "");
            }
        }
    }

    if let Err(e) = std::fs::write(path, output) {
        println!("cargo::warning=cannot write pruned {}: {e}", path.display());
    }
}

fn strip_comments(decl: &str) -> String {
    let mut code = String::with_capacity(decl.len());
    let bytes = decl.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if i + 1 < bytes.len() && bytes[i] == b'/' && bytes[i + 1] == b'*' {
            // Skip until '*/'.
            let mut j = i + 2;
            while j + 1 < bytes.len() && !(bytes[j] == b'*' && bytes[j + 1] == b'/') {
                j += 1;
            }
            i = (j + 2).min(bytes.len());
            continue;
        }
        if i + 1 < bytes.len() && bytes[i] == b'/' && bytes[i + 1] == b'/' {
            while i < bytes.len() && bytes[i] != b'\n' {
                i += 1;
            }
            continue;
        }
        code.push(bytes[i] as char);
        i += 1;
    }
    code
}
