fn main() {
    println!("cargo::rustc-check-cfg=cfg(cbindgen)");
    println!("cargo::rustc-check-cfg=cfg(has_unwind)");

    let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();

    // Link the C standard library for intrinsics (memcpy, memset, strlen, etc.)
    // These are generated by the compiler for no_std code and need libc implementations.
    // Windows MSVC has no "c" library; the CRT is linked automatically by rustc.
    let target_env = std::env::var("CARGO_CFG_TARGET_ENV").unwrap_or_default();
    if target_arch != "wasm32" && target_env != "msvc" {
        println!("cargo::rustc-link-lib=c");
    }

    // For macOS, suppress the undefined symbol error for _rust_eh_personality
    // by allowing undefined symbols in the dylib. The C side won't use unwinding anyway.
    #[cfg(target_os = "macos")]
    if target_arch != "wasm32" {
        println!("cargo::rustc-link-arg=-undefined");
        println!("cargo::rustc-link-arg=dynamic_lookup");
    }

    // Read CARGO_CFG_PANIC to detect if we are building with unwinding (e.g. during cargo test)
    if let Ok(panic_strat) = std::env::var("CARGO_CFG_PANIC")
        && panic_strat == "unwind"
    {
        println!("cargo::rustc-cfg=has_unwind");
    }

    // ── MBUS_MAX_TCP_CLIENTS ──────────────────────────────────────────────────
    //
    // Controls how many TCP client slots are pre-allocated in the static pool.
    // Default: 1. Valid range: [1, 255].
    // IDs 0x00xx index the TCP pool (high byte = 0x00).
    println!("cargo::rerun-if-env-changed=MBUS_MAX_TCP_CLIENTS");

    let max_tcp: usize = match std::env::var("MBUS_MAX_TCP_CLIENTS") {
        Ok(val) => {
            let n: usize = val.parse().unwrap_or_else(|_| {
                panic!("MBUS_MAX_TCP_CLIENTS must be a valid integer, got: \"{val}\"")
            });
            if n == 0 {
                panic!("MBUS_MAX_TCP_CLIENTS must be >= 1, got: 0");
            }
            if n > 255 {
                panic!("MBUS_MAX_TCP_CLIENTS must be <= 255, got: {n}");
            }
            n
        }
        Err(_) => 1, // default
    };

    // ── MBUS_MAX_SERIAL_CLIENTS ───────────────────────────────────────────────
    //
    // Controls how many Serial client slots are pre-allocated in each of the
    // RTU and ASCII sub-pools. Default: 1. Valid range: [1, 255].
    // IDs 0x01xx index the RTU pool, 0x02xx the ASCII pool.
    println!("cargo::rerun-if-env-changed=MBUS_MAX_SERIAL_CLIENTS");

    let max_serial: usize = match std::env::var("MBUS_MAX_SERIAL_CLIENTS") {
        Ok(val) => {
            let n: usize = val.parse().unwrap_or_else(|_| {
                panic!("MBUS_MAX_SERIAL_CLIENTS must be a valid integer, got: \"{val}\"")
            });
            if n == 0 {
                panic!("MBUS_MAX_SERIAL_CLIENTS must be >= 1, got: 0");
            }
            if n > 255 {
                panic!("MBUS_MAX_SERIAL_CLIENTS must be <= 255, got: {n}");
            }
            n
        }
        Err(_) => 1, // default
    };

    // ── MBUS_MAX_TCP_SERVERS ──────────────────────────────────────────────────
    //
    // Controls how many TCP server slots are pre-allocated in the static server pool.
    // Default: 1. Valid range: [1, 255].
    // IDs 0x10xx index the TCP server pool.
    println!("cargo::rerun-if-env-changed=MBUS_MAX_TCP_SERVERS");

    let max_tcp_servers: usize = match std::env::var("MBUS_MAX_TCP_SERVERS") {
        Ok(val) => {
            let n: usize = val.parse().unwrap_or_else(|_| {
                panic!("MBUS_MAX_TCP_SERVERS must be a valid integer, got: \"{val}\"")
            });
            if n == 0 {
                panic!("MBUS_MAX_TCP_SERVERS must be >= 1, got: 0");
            }
            if n > 255 {
                panic!("MBUS_MAX_TCP_SERVERS must be <= 255, got: {n}");
            }
            n
        }
        Err(_) => 1, // default
    };

    // ── MBUS_MAX_SERIAL_SERVERS ───────────────────────────────────────────────
    //
    // Controls how many Serial server slots are pre-allocated in the static server pool.
    // Default: 1. Valid range: [1, 255].
    // IDs 0x11xx index the Serial server pool.
    println!("cargo::rerun-if-env-changed=MBUS_MAX_SERIAL_SERVERS");

    let max_serial_servers: usize = match std::env::var("MBUS_MAX_SERIAL_SERVERS") {
        Ok(val) => {
            let n: usize = val.parse().unwrap_or_else(|_| {
                panic!("MBUS_MAX_SERIAL_SERVERS must be a valid integer, got: \"{val}\"")
            });
            if n == 0 {
                panic!("MBUS_MAX_SERIAL_SERVERS must be >= 1, got: 0");
            }
            if n > 255 {
                panic!("MBUS_MAX_SERIAL_SERVERS must be <= 255, got: {n}");
            }
            n
        }
        Err(_) => 1, // default
    };

    // ── MBUS_MAX_GATEWAYS ─────────────────────────────────────────────────────
    //
    // Controls how many gateway slots are pre-allocated in the static gateway pool.
    // Default: 1. Valid range: [1, 255].
    println!("cargo::rerun-if-env-changed=MBUS_MAX_GATEWAYS");

    let max_gateways: usize = match std::env::var("MBUS_MAX_GATEWAYS") {
        Ok(val) => {
            let n: usize = val.parse().unwrap_or_else(|_| {
                panic!("MBUS_MAX_GATEWAYS must be a valid integer, got: \"{val}\"")
            });
            if n == 0 {
                panic!("MBUS_MAX_GATEWAYS must be >= 1, got: 0");
            }
            if n > 255 {
                panic!("MBUS_MAX_GATEWAYS must be <= 255, got: {n}");
            }
            n
        }
        Err(_) => 1, // default
    };

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let config_path = format!("{out_dir}/pool_config.rs");
    std::fs::write(
        &config_path,
        format!(
            "/// Maximum number of TCP client slots (set via `MBUS_MAX_TCP_CLIENTS` env var, default 1).\n\
             #[allow(dead_code)]\n\
             pub(crate) const MAX_TCP_CLIENTS: usize = {max_tcp};\n\
             /// Maximum number of Serial client slots (set via `MBUS_MAX_SERIAL_CLIENTS` env var, default 1).\n\
             #[allow(dead_code)]\n\
             pub(crate) const MAX_SERIAL_CLIENTS: usize = {max_serial};\n\
             /// Maximum number of TCP server slots (set via `MBUS_MAX_TCP_SERVERS` env var, default 1).\n\
             #[allow(dead_code)]\n\
             pub(crate) const MAX_TCP_SERVERS: usize = {max_tcp_servers};\n\
             /// Maximum number of Serial server slots (set via `MBUS_MAX_SERIAL_SERVERS` env var, default 1).\n\
             #[allow(dead_code)]\n\
             pub(crate) const MAX_SERIAL_SERVERS: usize = {max_serial_servers};\n\
             /// Maximum number of gateway slots (set via `MBUS_MAX_GATEWAYS` env var, default 1).\n\
             #[allow(dead_code)]\n\
             pub(crate) const MAX_GATEWAYS: usize = {max_gateways};\n"
        ),
    )
    .expect("failed to write pool_config.rs");

    // ── cbindgen ──────────────────────────────────────────────────────────────

    // Only run cbindgen when the `c`, `c-server`, or `c-gateway` feature is enabled.
    if std::env::var("CARGO_FEATURE_C").is_err()
        && std::env::var("CARGO_FEATURE_C_SERVER").is_err()
        && std::env::var("CARGO_FEATURE_C_GATEWAY").is_err()
    {
        return;
    }

    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let workspace_root = std::path::Path::new(&crate_dir)
        .parent()
        .expect("CARGO_MANIFEST_DIR has no parent")
        .to_path_buf();
    let target_dir = std::env::var("CARGO_TARGET_DIR")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|_| workspace_root.join("target"));
    let include_dir = target_dir.join("mbus-ffi/include");

    // Rerun cbindgen if the configs or any source file changes.
    println!("cargo::rerun-if-changed=cbindgen_client.toml");
    println!("cargo::rerun-if-changed=cbindgen_server.toml");
    println!("cargo::rerun-if-changed=cbindgen_gateway.toml");
    println!("cargo::rerun-if-changed=src");
    std::fs::create_dir_all(&include_dir).expect("failed to create target include directory");

    if std::env::var("CARGO_FEATURE_C").is_ok() {
        let output_file = include_dir.join("modbus_rs_client.h");
        let config_path = format!("{crate_dir}/cbindgen_client.toml");
        let config = cbindgen::Config::from_file(&config_path)
            .unwrap_or_else(|err| panic!("failed to parse {config_path}: {err}"));

        cbindgen::Builder::new()
            .with_crate(&crate_dir)
            .with_language(cbindgen::Language::C)
            .with_define("feature", "c", "MBUS_FEATURE_C")
            .with_define("feature", "coils", "MBUS_FEATURE_COILS")
            .with_define("feature", "registers", "MBUS_FEATURE_REGISTERS")
            .with_define("feature", "discrete-inputs", "MBUS_FEATURE_DISCRETE_INPUTS")
            .with_define("feature", "fifo", "MBUS_FEATURE_FIFO")
            .with_define("feature", "file-record", "MBUS_FEATURE_FILE_RECORD")
            .with_define("feature", "diagnostics", "MBUS_FEATURE_DIAGNOSTICS")
            .with_config(config)
            .generate()
            .expect("cbindgen failed to generate C header")
            .write_to_file(output_file);
    }

    if std::env::var("CARGO_FEATURE_C_SERVER").is_ok() {
        let output_file = include_dir.join("modbus_rs_server.h");
        let config_path = format!("{crate_dir}/cbindgen_server.toml");
        let config = cbindgen::Config::from_file(&config_path)
            .unwrap_or_else(|err| panic!("failed to parse {config_path}: {err}"));

        cbindgen::Builder::new()
            .with_crate(&crate_dir)
            .with_language(cbindgen::Language::C)
            .with_define("feature", "c-server", "MBUS_FEATURE_C_SERVER")
            .with_config(config)
            .generate()
            .expect("cbindgen failed to generate server C header")
            .write_to_file(output_file);

        // ── Server app code generation ────────────────────────────────────────
        //
        // Reads a user-supplied YAML config and generates the Rust dispatcher
        // (model structs + FFI exports) into OUT_DIR/generated_server.rs.
        // The source file is then pulled in via `include!` in server_gen/mod.rs.
        //
        // Set MBUS_SERVER_APP_CONFIG to the path of your YAML config file:
        //   MBUS_SERVER_APP_CONFIG=/path/to/server_app.yaml cargo build -p mbus-ffi --features c-server
        println!("cargo::rerun-if-env-changed=MBUS_SERVER_APP_CONFIG");
        // When MBUS_SERVER_APP_CONFIG is not set, fall back to the bundled
        // example YAML if it is present (i.e. we are inside the workspace).
        // This makes `cargo test --workspace --all-features` work without
        // extra environment setup.  A warning is emitted so the fallback is
        // never silent.  Production builds that extracted only `mbus-ffi`
        // won't have the example file and will still get the clear panic.
        let example_yaml = std::path::Path::new(&crate_dir)
            .join("examples/c_server_demo_yaml/mbus_server_app.example.yaml");
        let app_config_raw = std::env::var("MBUS_SERVER_APP_CONFIG").unwrap_or_else(|_| {
            if example_yaml.exists() {
                example_yaml.to_string_lossy().into_owned()
            } else {
                panic!(
                    "\n\nError: MBUS_SERVER_APP_CONFIG is not set.\n\
                     The `c-server` feature requires a YAML device config to generate the server app layer.\n\
                     Set the environment variable to the path of your server_app.yaml:\n\
                     \n\
                     MBUS_SERVER_APP_CONFIG=/path/to/server_app.yaml cargo build -p mbus-ffi --features c-server\n\
                     \n\
                     See mbus-ffi/examples/c_server_demo_yaml/mbus_server_app.example.yaml for the format.\n"
                )
            }
        });
        // Resolve relative paths against the workspace root (parent of the crate dir).
        let app_config_path = {
            let p = std::path::Path::new(&app_config_raw);
            if p.is_absolute() {
                p.to_path_buf()
            } else {
                std::path::Path::new(&crate_dir)
                    .parent()
                    .expect("CARGO_MANIFEST_DIR has no parent")
                    .join(p)
            }
        };
        println!("cargo::rerun-if-changed={}", app_config_path.display());
        let app_config_text = std::fs::read_to_string(&app_config_path)
            .unwrap_or_else(|e| panic!("failed to read MBUS_SERVER_APP_CONFIG={}: {e}", app_config_path.display()));
        let app_config = mbus_codegen::parse_yaml(&app_config_text)
            .unwrap_or_else(|e| panic!("invalid YAML in {}: {e}", app_config_path.display()));
        mbus_codegen::validate_config(&app_config)
            .unwrap_or_else(|e| panic!("config error in {}: {e}", app_config_path.display()));
        let rust_src = mbus_codegen::render_rust_dispatcher(&app_config);
        let gen_path = format!("{out_dir}/generated_server.rs");
        std::fs::write(&gen_path, rust_src)
            .unwrap_or_else(|e| panic!("failed to write {gen_path}: {e}"));
    }

    if std::env::var("CARGO_FEATURE_C_GATEWAY").is_ok() {
        let output_file = include_dir.join("modbus_rs_gateway.h");
        let config_path = format!("{crate_dir}/cbindgen_gateway.toml");
        let config = cbindgen::Config::from_file(&config_path)
            .unwrap_or_else(|err| panic!("failed to parse {config_path}: {err}"));

        cbindgen::Builder::new()
            .with_crate(&crate_dir)
            .with_language(cbindgen::Language::C)
            .with_define("feature", "c", "MBUS_FEATURE_C")
            .with_define("feature", "c-server", "MBUS_FEATURE_C_SERVER")
            .with_define("feature", "c-gateway", "MBUS_FEATURE_C_GATEWAY")
            .with_define("feature", "coils", "MBUS_FEATURE_COILS")
            .with_define("feature", "registers", "MBUS_FEATURE_REGISTERS")
            .with_define("feature", "discrete-inputs", "MBUS_FEATURE_DISCRETE_INPUTS")
            .with_define("feature", "fifo", "MBUS_FEATURE_FIFO")
            .with_define("feature", "file-record", "MBUS_FEATURE_FILE_RECORD")
            .with_define("feature", "diagnostics", "MBUS_FEATURE_DIAGNOSTICS")
            .with_config(config)
            .generate()
            .expect("cbindgen failed to generate gateway C header")
            .write_to_file(output_file);
    }
}
