use std::path::Path;
use xshell::{cmd, Shell};

const ALL_FEATURES: &[(&str, &str)] = &[
    ("c-client", "MBUS_FEATURE_C_CLIENT"),
    ("c-server", "MBUS_FEATURE_C_SERVER"),
    ("c-gateway", "MBUS_FEATURE_C_GATEWAY"),
    ("coils", "MBUS_FEATURE_COILS"),
    ("holding-registers", "MBUS_FEATURE_HOLDING_REGISTERS"),
    ("input-registers", "MBUS_FEATURE_INPUT_REGISTERS"),
    ("discrete-inputs", "MBUS_FEATURE_DISCRETE_INPUTS"),
    ("fifo", "MBUS_FEATURE_FIFO"),
    ("file-record", "MBUS_FEATURE_FILE_RECORD"),
    ("diagnostics", "MBUS_FEATURE_DIAGNOSTICS"),
    ("traffic", "MBUS_FEATURE_TRAFFIC"),
    ("server-traffic", "MBUS_FEATURE_SERVER_TRAFFIC"),
    ("network-tcp", "MBUS_FEATURE_NETWORK_TCP"),
    ("serial-rtu", "MBUS_FEATURE_SERIAL_RTU"),
    ("serial-ascii", "MBUS_FEATURE_SERIAL_ASCII"),
];

pub fn generate_or_check_header(root: &Path, features: Option<&str>, fix: bool) -> Result<(), String> {
    let sh = Shell::new().map_err(|e| format!("Failed to create shell: {e}"))?;
    sh.change_dir(root);

    // Verify cbindgen is installed
    if cmd!(sh, "cbindgen --version").read().is_err() {
        return Err("ERROR: cbindgen not found. Install with: cargo install cbindgen --locked".to_string());
    }

    let header_dir = root.join("target/mbus-ffi/include");
    let header_file = header_dir.join("modbus_rs.h");
    let cbindgen_toml = root.join("mbus-ffi/cbindgen.toml");

    let tmp_dir = root.join(".tmp");
    sh.create_dir(&tmp_dir).map_err(|e| format!("Failed to create temp dir: {e}"))?;
    let tmpfile = tmp_dir.join("mbus_ffi_header.h");
    let metadata_tmp = tmp_dir.join("mbus_ffi_metadata.json");

    // Clean up old files
    let _ = sh.remove_path(&tmpfile);
    let _ = sh.remove_path(&metadata_tmp);

    // Run cbindgen
    if let Some(feats) = features {
        let res = cmd!(sh, "cargo metadata --format-version 1 --manifest-path mbus-ffi/Cargo.toml --features {feats} --no-default-features").read();
        let metadata = res.map_err(|e| format!("cargo metadata failed: {e}"))?;
        sh.write_file(&metadata_tmp, metadata).map_err(|e| format!("Failed to write metadata tmp: {e}"))?;

        cmd!(sh, "cbindgen --config {cbindgen_toml} --crate mbus-ffi --metadata {metadata_tmp} --output {tmpfile} --quiet")
            .run()
            .map_err(|e| format!("cbindgen failed: {e}"))?;
    } else {
        cmd!(sh, "cbindgen --config {cbindgen_toml} --crate mbus-ffi --output {tmpfile} --quiet")
            .run()
            .map_err(|e| format!("cbindgen failed: {e}"))?;
    }

    // Build the configuration block
    let mut config_block = String::from("\n/* Active feature configuration defines built into the library */\n");

    let active_features: Vec<&str> = features.map(|f| f.split(',').collect()).unwrap_or_default();

    for &(feat, macro_name) in ALL_FEATURES {
        let is_active = match features {
            None => true, // default to all if no features specified (or based on check_header.sh logic)
            Some(_) => active_features.contains(&feat),
        };

        if is_active {
            config_block.push_str(&format!("#define {} 1\n", macro_name));
        } else {
            config_block.push_str(&format!("/* #undef {} */\n", macro_name));
        }
    }
    config_block.push('\n');

    // Process the header file
    let content = sh.read_file(&tmpfile).map_err(|e| format!("Failed to read {}: {}", tmpfile.display(), e))?;
    
    let new_content = if content.contains("/* Auto-generated by cbindgen - DO NOT EDIT */") {
        content.replace(
            "/* Auto-generated by cbindgen - DO NOT EDIT */",
            &format!("/* Auto-generated by cbindgen - DO NOT EDIT */\n{}", config_block)
        )
    } else if content.contains("#pragma once") {
        content.replace(
            "#pragma once",
            &format!("#pragma once\n{}", config_block)
        )
    } else {
        format!("{}{}", config_block, content)
    };

    sh.write_file(&tmpfile, new_content).map_err(|e| format!("Failed to write {}: {}", tmpfile.display(), e))?;

    // Check if the header file exists
    if !header_file.exists() {
        sh.create_dir(&header_dir).map_err(|e| format!("Failed to create header dir: {e}"))?;
        sh.copy_file(&tmpfile, &header_file).map_err(|e| format!("Failed to copy file: {e}"))?;
        println!("Header bootstrapped: {}", header_file.display());
        return Ok(());
    }

    // Handle fix/check logic
    if fix {
        sh.create_dir(&header_dir).map_err(|e| format!("Failed to create header dir: {e}"))?;
        sh.copy_file(&tmpfile, &header_file).map_err(|e| format!("Failed to copy file: {e}"))?;
        println!("Header regenerated: {}", header_file.display());
        return Ok(());
    }

    let existing_content = sh.read_file(&header_file).map_err(|e| format!("Failed to read {}: {}", header_file.display(), e))?;
    let tmp_content = sh.read_file(&tmpfile).map_err(|e| format!("Failed to read {}: {}", tmpfile.display(), e))?;

    if existing_content != tmp_content {
        return Err(
            "\nERROR: modbus_rs.h is out of date with the Rust source.\nRun the following to fix it:\n\n  cargo run -p xtask -- check-client-header --fix\n".to_string()
        );
    }

    println!("OK: modbus_rs.h is up to date.");
    Ok(())
}
