//! Auto-discovery of C demo projects under `mbus-ffi/examples/`.
//!
//! Every subdirectory of `mbus-ffi/examples/` that contains a `demo.yaml` file
//! is treated as a demo project.  The manifest declares the name, binary,
//! required Rust features, an optional codegen step, and one or more named run
//! modes so that `run-c-demo` knows how to invoke the binary.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

// ── Manifest types ──────────────────────────────────────────────────────────

/// A named run mode for a demo binary.
#[derive(Debug, Deserialize)]
pub struct RunMode {
    /// Command-line arguments to pass to the binary for this mode.
    #[serde(default)]
    pub args: Vec<String>,
    /// Human-readable description shown in `list-c-demos` and help output.
    pub description: String,
}

/// `run:` block in `demo.yaml`.
#[derive(Debug, Deserialize)]
pub struct RunConfig {
    /// Map of mode name → mode definition.
    pub modes: BTreeMap<String, RunMode>,
    /// Mode to use when `--mode` is not specified on the command line.
    pub default_mode: String,
}

/// Optional `codegen:` block — runs `gen-server-app` before building.
#[derive(Debug, Deserialize)]
pub struct CodegenConfig {
    /// Path to the YAML device config, relative to the repo root.
    pub config: String,
    /// Output directory for generated Rust files, relative to the repo root.
    /// Optional: when absent the Rust dispatcher is generated by `build.rs` via
    /// `MBUS_SERVER_APP_CONFIG` instead of being written into the source tree.
    #[serde(default)]
    pub out_dir: Option<String>,
    /// Path for the generated C header, relative to the repo root.
    pub header: String,
}

/// Parsed `demo.yaml` manifest.
#[derive(Debug, Deserialize)]
pub struct DemoManifest {
    /// Short identifier used as the `--demo <name>` value (e.g. `c_server_demo_yaml`).
    pub name: String,
    /// One-line description shown in `list-c-demos`.
    pub description: String,
    /// CMake executable target name (and built binary filename).
    pub binary: String,
    /// Comma-separated Rust feature flags for `cargo build -p mbus-ffi`.
    pub rust_features: String,
    /// Optional codegen step run before `cargo build`.
    #[serde(default)]
    pub codegen: Option<CodegenConfig>,
    /// Optional run modes used by `run-c-demo`.
    #[serde(default)]
    pub run: Option<RunConfig>,
    /// Absolute path to the demo directory.  Populated after loading; not in YAML.
    #[serde(skip)]
    pub dir: PathBuf,
}

impl DemoManifest {
    /// Absolute path to the CMake build output directory.
    pub fn build_dir(&self, link_static: bool) -> PathBuf {
        self.dir.join(if link_static { "build-static" } else { "build" })
    }

    /// Absolute path to the compiled demo binary.
    pub fn binary_path(&self, link_static: bool) -> PathBuf {
        self.build_dir(link_static).join(&self.binary)
    }
}

// ── Discovery ───────────────────────────────────────────────────────────────

/// Scan `<root>/mbus-ffi/examples/*/demo.yaml` and return all parsed manifests
/// in stable alphabetical order by name.
pub fn discover_demos(root: &Path) -> Result<Vec<DemoManifest>, String> {
    let examples_dir = root.join("mbus-ffi/examples");
    let entries = fs::read_dir(&examples_dir)
        .map_err(|e| format!("failed to read {}: {e}", examples_dir.display()))?;

    let mut demos = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let manifest_path = path.join("demo.yaml");
        if !manifest_path.exists() {
            continue;
        }
        let src = fs::read_to_string(&manifest_path)
            .map_err(|e| format!("failed to read {}: {e}", manifest_path.display()))?;
        let mut manifest: DemoManifest = serde_yaml::from_str(&src)
            .map_err(|e| format!("failed to parse {}: {e}", manifest_path.display()))?;
        manifest.dir = path;
        demos.push(manifest);
    }

    demos.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(demos)
}

/// Find a demo by name, returning a user-friendly error if not found.
pub fn find_demo<'a>(demos: &'a [DemoManifest], name: &str) -> Result<&'a DemoManifest, String> {
    demos.iter().find(|d| d.name == name).ok_or_else(|| {
        let names: Vec<&str> = demos.iter().map(|d| d.name.as_str()).collect();
        format!(
            "demo '{name}' not found. Available: {}",
            names.join(", ")
        )
    })
}
