#![cfg_attr(not(doc), no_std)]
#![warn(missing_docs)]

//! Compile-time mapping foundations for `mbus-server`.
//!
//! Provides:
//! - derive-driven coil models with FC01 read / FC05 write
//! - derive-driven FC03 holding-register maps via `HoldingRegistersModel`
//! - derive-driven FC04 input-register maps via `InputRegistersModel`
//! - `modbus_app` address-range routing for FC03/FC04

extern crate self as mbus_server;

pub mod app;
pub mod services;

pub use app::{ForwardingApp, ModbusAppAccess, ModbusAppHandler};
#[cfg(feature = "traffic")]
pub use app::TrafficNotifier;
#[cfg(feature = "coils")]
pub use mbus_macros::CoilsModel;
#[cfg(feature = "holding-registers")]
pub use mbus_macros::HoldingRegistersModel;
#[cfg(feature = "input-registers")]
pub use mbus_macros::InputRegistersModel;
pub use mbus_macros::modbus_app;
pub use services::ServerServices;
pub use services::resilience::{
    ClockFn, OverflowPolicy, RequestPriority, ResilienceConfig, TimeoutConfig,
};

#[cfg(feature = "coils")]
pub use mbus_core::models::coil::*;
#[cfg(any(feature = "holding-registers", feature = "input-registers"))]
pub use mbus_core::models::register::*;

use mbus_core::errors::MbusError;

/// Trait implemented by user coil maps routed by `#[modbus_app]`.
#[cfg(feature = "coils")]
pub trait CoilMap {
    /// Lowest Modbus coil address declared on this map.
    const ADDR_MIN: u16;
    /// Highest Modbus coil address declared on this map.
    const ADDR_MAX: u16;
    /// Coil slots from `ADDR_MIN` to `ADDR_MAX` inclusive.
    const BIT_COUNT: usize;

    /// Encodes the coil window `[address, address + quantity)` into packed Modbus bit bytes.
    fn encode(&self, address: u16, quantity: u16, out: &mut [u8]) -> Result<u8, MbusError>;

    /// Writes a single coil value at `address`.
    fn write_single(&mut self, address: u16, value: bool) -> Result<(), MbusError>;

    /// Writes `quantity` packed coil values starting at `address` using `packed_bit_offset` into `values`.
    fn write_many_from_packed(
        &mut self,
        address: u16,
        quantity: u16,
        values: &[u8],
        packed_bit_offset: usize,
    ) -> Result<(), MbusError>;
}

// ---------------------------------------------------------------------------
// HoldingRegisterMap — used by #[derive(HoldingRegistersModel)] + #[modbus_app]
// ---------------------------------------------------------------------------

/// Trait implemented by `#[derive(HoldingRegistersModel)]`.
///
/// A register map struct where every field is a raw `u16` wire word.
/// Public getters and setters are generated by the derive macro.
/// Use `#[modbus_app]` on your application struct to wire this map to FC03.
#[cfg(feature = "holding-registers")]
pub trait HoldingRegisterMap {
    /// Lowest Modbus register address declared on this map.
    const ADDR_MIN: u16;
    /// Highest Modbus register address declared on this map.
    const ADDR_MAX: u16;
    /// Register word slots from `ADDR_MIN` to `ADDR_MAX` inclusive.
    const WORD_COUNT: usize;

    /// Encodes the register window `[address, address + quantity)` into `out`
    /// as consecutive big-endian 16-bit words.
    ///
    /// # Returns
    /// Byte count written (`quantity * 2`) on success.
    ///
    /// # Errors
    /// - [`MbusError::InvalidAddress`] if `quantity == 0` or the window falls
    ///   outside `[ADDR_MIN, ADDR_MAX]`.
    /// - [`MbusError::BufferTooSmall`] if `out.len() < quantity * 2`.
    fn encode(&self, address: u16, quantity: u16, out: &mut [u8]) -> Result<u8, MbusError>;

    /// Writes a single register word at `address`.
    fn write_single(&mut self, address: u16, value: u16) -> Result<(), MbusError>;

    /// Writes consecutive register words starting at `address`.
    fn write_many(&mut self, address: u16, values: &[u16]) -> Result<(), MbusError>;
}

// ---------------------------------------------------------------------------
// InputRegisterMap — used by #[derive(InputRegistersModel)] + #[modbus_app]
// ---------------------------------------------------------------------------

/// Trait implemented by `#[derive(InputRegistersModel)]`.
///
/// Input register maps are read-only from the Modbus protocol perspective (FC04).
/// No write methods are exposed on this trait.
#[cfg(feature = "input-registers")]
pub trait InputRegisterMap {
    /// Lowest Modbus register address declared on this map.
    const ADDR_MIN: u16;
    /// Highest Modbus register address declared on this map.
    const ADDR_MAX: u16;
    /// Register word slots from `ADDR_MIN` to `ADDR_MAX` inclusive.
    const WORD_COUNT: usize;

    /// Encodes the register window `[address, address + quantity)` into `out`
    /// as consecutive big-endian 16-bit words.
    fn encode(&self, address: u16, quantity: u16, out: &mut [u8]) -> Result<u8, MbusError>;
}

/// Common trait imports for ergonomic `mbus-server` usage.
pub mod prelude {
    #[cfg(feature = "coils")]
    pub use crate::CoilMap;
    #[cfg(feature = "holding-registers")]
    pub use crate::HoldingRegisterMap;
    #[cfg(feature = "input-registers")]
    pub use crate::InputRegisterMap;
}
